### ISSUE TITLE
[BUG] - Extremely slow downloads that fail quickly

### ISSUE THREAD

**Issue by Oman395** [ebkr/r2modmanPlus#1004]
**Describe the bug**
This might be an issue with my ethernet card; I've recently switched back to windows for gaming from linux, and I've noticed that it's pretty much impossible to install certain mods (most of the modul series of guns for H3VR, for example). Any workarounds I can do? I've tried pretty much everything I can on the ethernet card side short of an RMA, so I'm pretty much out of ideas.

**To Reproduce**
Attempt to install a mod (I only have h3vr, this behavior happens when installing the FTW series of mods as well as the modul weapons; the PMC_Pete_Content pack has a lot of the offending mods

**Expected behavior**
The downloads to proceed normally.

**Additional context**
Connected via ethernet to fios router, 1gbps up/down consistently. No issues on linux whatsoever-- I don't think it's possible for the cable to be at fault. Of note is the fact that r2 also uses no internet while it says it is downloading; this issue appears to be persisting on thunderstore MM as well.

**Comment by MythicManiac** [comment]
Does the download itself fail, or does it get seemingly "stuck" at the very end? I'm asking because installation progress is not shown anywhere on the UI currently, and some larger mods can take quite a while for that to finish.

If you have an error message to share, that'd also help of course.

**Comment by Oman395** [comment]
Some mods download fine, others immediately stop progressing the bar-- after a while, the bar turns red, and it says the download failed.

**Comment by Oman395** [comment]
![image](https://user-images.githubusercontent.com/77183348/229938482-9fa55d37-1357-429f-a202-4a9aad6ab834.png)
This is pretty much what happens. Downloads normally to a certain percentage, then stops using Ethernet entirely and hangs at a certain percentage.

**Comment by Oman395** [comment]
Definitely a hardware issue, just installed a PCI network card and it's working flawlessly now. Best guess for the source of the issue on the side of r2 is that it can't handle issues while downloading-- but I'm not sure how resolvable that is, given that even bloody firefox has the same issue. Closing for now, but this could cause problems for people with unstable internet.
