### ISSUE TITLE
[BUG] - Quill editor sets cursor to index 0 after every change

### ISSUE THREAD

**Issue by sheybey** [ebkr/r2modmanPlus#1008]
**Describe the bug**
When you are editing a config file, every change moves the cursor to the first character of the buffer, making it extremely difficult to type anything in.

**To Reproduce**
1. Select a mod profile for any game that has installed mods with config files
2. Click on "Config editor"
3. Find a config file that isn't parsed by r2modman (any JSON should do)
4. Click "Edit config"
5. Try to type in a word

**Expected behavior**
The edit is made and the cursor stays where it is

**Additional context**
This is caused by keeping the entire content of the buffer as a component prop and calling setText on every update. The quill documentation implies that it manufactures a minimal delta and keeps other state, but in reality it is just generating a delete(...).insert(newValue) Delta, which causes the cursor to move to index 0 every time.

This can be worked around by saving the selection and manually restoring it after every update (PR incoming.)

**Comment by ebkr** [comment]
Closing as merged
