### ISSUE TITLE
[BUG] - Bypass for filtered profile characters

### ISSUE THREAD

**Issue by xFaraday** [ebkr/r2modmanPlus#1030]
**Describe the bug**
If the profile directories are manually created in the respective game profile directory then r2modman will accept the profiles.  It will deny the same profile with special characters when made through the app.

**To Reproduce**
1. Go to the game profile path (EX: /home/user/.config/r2modmanPlus-local/ROUNDS/profiles
2. Create a directory with respective characters(EX: <!(>/ ) 
3. Reload available profiles

**Expected behavior**
Profiles with potentially bad characters should not load

**Screenshots**
![badprofiles](https://github.com/ebkr/r2modmanPlus/assets/28304747/1cbcde84-23e4-4130-87d7-28e17f750974)

**Additional context**
This could potentially lead to a vulnerability.

**Comment by ebkr** [comment]
This isn't strictly a bug and is instead due to different filesystems not accepting certain characters. Rather than support several formats or all the allowed strings, it's easier to whitelist only certain ones.

I don't think it needs to be resolved as the text is escaped prior to rendering.
