### ISSUE TITLE
Launching RoR2 opens 2 consoles

### ISSUE THREAD

**Issue by 15kalind** [ebkr/r2modmanPlus#1033]
### Discussed in https://github.com/ebkr/r2modmanPlus/discussions/1032

<div type='discussions-op-text'>

<sup>Originally posted by **15kalind** June  4, 2023</sup>
Hello all,

I've been using r2modman for a few weeks, and this only just started happening within the last couple of days. It's not the end of the world, as I can just close one of the consoles (usually they're even duplicates of each other), but it's just a bit annoying. Does anyone know why?

Thanks!</div>

**Comment by xiaoxiao921** [comment]
May sound like a dumb question, but can you screenshot them?

**Comment by 15kalind** [comment]
![image](https://github.com/ebkr/r2modmanPlus/assets/20620237/53140c79-b093-49ce-a96a-42b04421e182)

**Comment by 15kalind** [comment]
![image](https://github.com/ebkr/r2modmanPlus/assets/20620237/435b9596-5cef-437a-8d2c-cb208b2a7d7b)
Yep!

**Comment by xiaoxiao921** [comment]
If that's not too much to ask,
- can you please navigate to r2modman settings,
- click on "Browse profile folder",
- it should open a file explorer,
- in the bar where you can change the folder,
- type in it `cmd`, once the command prompt open,
- type in it `tree /f`,
- and copy paste the output in there?

I made a video below that should visualy represent what I just explained, thanks

https://github.com/ebkr/r2modmanPlus/assets/837334/55c51283-608b-4594-9b30-81613a0557f5

**Comment by 15kalind** [comment]
C:.
│   .doorstop_version
│   changelog.txt
│   doorstop_config.ini
│   mods.yml
│   winhttp.dll
│
├───BepInEx
│   │   LogOutput.log
│   │
│   ├───cache
│   │       chainloader_typeloader.dat
│   │       harmony_interop_cache.dat
│   │
│   ├───config
│   │   │   BepInEx.cfg
│   │   │   BepInEx.DO_NOT_MODIFY.cfg
│   │   │   BepInEx.GUI.cfg
│   │   │   BetterUI-AdvancedIcons.cfg
│   │   │   BetterUI-Buffs.cfg
│   │   │   BetterUI-CommandImprovements.cfg
│   │   │   BetterUI-Components.cfg
│   │   │   BetterUI-DPSMeter.cfg
│   │   │   BetterUI-ItemCounters.cfg
│   │   │   BetterUI-Misc.cfg
│   │   │   BetterUI-Sorting.cfg
│   │   │   BetterUI-StatsDisplay.cfg
│   │   │   com.bepis.bepinex.configurationmanager.cfg
│   │   │   com.Moffein.EliteReworks.cfg
│   │   │   com.Moffein.ItemStats.cfg
│   │   │   com.pixeldesu.pingprovements.cfg
│   │   │   com.rune580.riskofoptions.cfg
│   │   │   com.TeamMoonstorm.Starstorm2.cfg
│   │   │   Faust.QoLChests.cfg
│   │   │   Felda.ActuallyFaster.cfg
│   │   │   FixPluginTypesSerialization.cfg
│   │   │   HookGenPatcher.cfg
│   │   │   Red.PingItemDescription.cfg
│   │   │   ___riskofthunder.RoR2BepInExPack.cfg
│   │   │
│   │   ├───com.RiskyLives.RiskyMod
│   │   │       RiskyMod_General.cfg
│   │   │       RiskyMod_Items.cfg
│   │   │       RiskyMod_Monsters.cfg
│   │   │       RiskyMod_Spawnpools.cfg
│   │   │       RiskyMod_Survivors.cfg
│   │   │
│   │   ├───Moonstorm Shared Utils
│   │   │       MSU.Events.cfg
│   │   │       MSU.General.cfg
│   │   │
│   │   └───Starstorm 2
│   │           SS2.Artifacts.cfg
│   │           SS2.Items.cfg
│   │           SS2.Main.cfg
│   │           SS2.Miscellaneous.cfg
│   │           SS2.Survivors.cfg
│   │
│   ├───core
│   │       0Harmony.dll
│   │       0Harmony.xml
│   │       0Harmony20.dll
│   │       BepInEx.Bootstrap.dll
│   │       BepInEx.dll
│   │       BepInEx.Harmony.dll
│   │       BepInEx.Harmony.xml
│   │       BepInEx.Preloader.dll
│   │       BepInEx.Preloader.xml
│   │       BepInEx.xml
│   │       HarmonyXInterop.dll
│   │       Mono.Cecil.dll
│   │       Mono.Cecil.Mdb.dll
│   │       Mono.Cecil.Pdb.dll
│   │       Mono.Cecil.Rocks.dll
│   │       MonoMod.RuntimeDetour.dll
│   │       MonoMod.RuntimeDetour.xml
│   │       MonoMod.Utils.dll
│   │       MonoMod.Utils.xml
│   │
│   ├───patchers
│   │   ├───BepInExGUI
│   │   │   ├───Patcher
│   │   │   │       BepInEx.GUI.Patcher.dll
│   │   │   │
│   │   │   └───rust
│   │   │       └───windows_x64
│   │   │               bepinex_gui.exe
│   │   │
│   │   ├───FixPluginTypesSerialization
│   │   │       FixPluginTypesSerialization.dll
│   │   │
│   │   ├───RiskofThunder-BepInEx_GUI
│   │   │   └───BepInEx.GUI
│   │   │           BepInEx.GUI.Loader.dll
│   │   │           bepinex_gui.exe
│   │   │
│   │   ├───RiskofThunder-FixPluginTypesSerialization
│   │   │   └───FixPluginTypesSerialization
│   │   │           FixPluginTypesSerialization.dll
│   │   │
│   │   └───RiskofThunder-HookGenPatcher
│   │       └───Bepinex.MonoMod.HookGenPatcher
│   │               BepInEx.MonoMod.HookGenPatcher.dll
│   │               Bepinex.Monomod.HookGenPatcher.pdb
│   │               MonoMod.exe
│   │               MonoMod.RuntimeDetour.HookGen.exe
│   │               MonoMod.RuntimeDetour.HookGen.xml
│   │               MonoMod.xml
│   │
│   └───plugins
│       ├───BetterPing-PingItemDescription
│       │       icon.png
│       │       manifest.json
│       │       PingItemDescription.dll
│       │       README.md
│       │
│       ├───Bubbet-BubbetsItems
│       │       BubbetsItems.bnk.old
│       │       BubbetsItems.dll.old
│       │       icon.png.old
│       │       mainassetbundle.old
│       │       manifest.json.old
│       │       NCalc.dll.old
│       │       README.md.old
│       │
│       ├───Bubbet-SkipIntro
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │       SkipIntroCutscene.dll
│       │
│       ├───Faustvii-QoLChests
│       │       BetterUnityPlugin.dll
│       │       icon.png
│       │       manifest.json
│       │       QoLChests.dll
│       │       README.md
│       │
│       ├───Felda-Actually_Faster
│       │       ActuallyFaster.dll
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │
│       ├───IFixYourRoR2Mods-Bepinex_ConfigurationManager
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───ConfigurationManager
│       │           ConfigurationManager.dll
│       │           ConfigurationManager.xml
│       │           LICENSE.txt
│       │
│       ├───KingEnderBrine-LobbySkinsFix
│       │   │   CHANGELOG.md
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───LobbySkinsFix
│       │           LobbySkinsFix.dll
│       │
│       ├───KingEnderBrine-ProperSave
│       │   │   CHANGELOG.md
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───ProperSave
│       │       │   ProperSave.dll
│       │       │
│       │       └───Language
│       │           ├───en
│       │           │       tokens.json
│       │           │
│       │           ├───fr
│       │           │       tokens.json
│       │           │
│       │           ├───ru
│       │           │       tokens.json
│       │           │
│       │           ├───UA
│       │           │       tokens.json
│       │           │
│       │           └───zh-CN
│       │                   tokens.json
│       │
│       ├───MMHOOK
│       │       MMHOOK_RoR2.dll
│       │
│       ├───Moffein-EliteReworks
│       │       EliteReworks.dll
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │
│       ├───Moffein-ItemStats
│       │       icon.png
│       │       ItemStats.dll
│       │       manifest.json
│       │       README.md
│       │
│       ├───Moonlol-SeerPing
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │       SeerPing.dll
│       │
│       ├───rainyuu-Pingprovements
│       │       icon.png
│       │       manifest.json
│       │       Pingprovements.dll
│       │       README.md
│       │
│       ├───RiskofThunder-BepInEx_GUI
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │
│       ├───RiskofThunder-FixPluginTypesSerialization
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │
│       ├───RiskofThunder-HookGenPatcher
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───MMHOOK
│       │           MMHOOK_Assembly-CSharp.dll
│       │
│       ├───RiskofThunder-R2API_ArtifactCode
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.ArtifactCode
│       │           R2API.ArtifactCode.dll
│       │           R2API.ArtifactCode.xml
│       │
│       ├───RiskofThunder-R2API_Colors
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Colors
│       │           R2API.Colors.dll
│       │           R2API.Colors.xml
│       │
│       ├───RiskofThunder-R2API_CommandHelper
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.CommandHelper
│       │           R2API.CommandHelper.dll
│       │           R2API.CommandHelper.xml
│       │
│       ├───RiskofThunder-R2API_ContentManagement
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.ContentManagement
│       │           R2API.ContentManagement.dll
│       │           R2API.ContentManagement.xml
│       │
│       ├───RiskofThunder-R2API_Core
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Core
│       │           R2API.Core.dll
│       │           R2API.Core.xml
│       │
│       ├───RiskofThunder-R2API_DamageType
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.DamageType
│       │           R2API.DamageType.dll
│       │           R2API.DamageType.xml
│       │
│       ├───RiskofThunder-R2API_Deployable
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Deployable
│       │           R2API.Deployable.dll
│       │           R2API.Deployable.xml
│       │
│       ├───RiskofThunder-R2API_Difficulty
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Difficulty
│       │           R2API.Difficulty.dll
│       │           R2API.Difficulty.xml
│       │
│       ├───RiskofThunder-R2API_Director
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Director
│       │           R2API.Director.dll
│       │           R2API.Director.xml
│       │
│       ├───RiskofThunder-R2API_Dot
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Dot
│       │           R2API.Dot.dll
│       │           R2API.Dot.xml
│       │
│       ├───RiskofThunder-R2API_Elites
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Elites
│       │           R2API.Elites.dll
│       │           R2API.Elites.xml
│       │
│       ├───RiskofThunder-R2API_Items
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Items
│       │           R2API.Items.dll
│       │           R2API.Items.xml
│       │
│       ├───RiskofThunder-R2API_Language
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Language
│       │           R2API.Language.dll
│       │           R2API.Language.xml
│       │
│       ├───RiskofThunder-R2API_Loadout
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Loadout
│       │           R2API.Loadout.dll
│       │           R2API.Loadout.xml
│       │
│       ├───RiskofThunder-R2API_LobbyConfig
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.LobbyConfig
│       │           R2API.LobbyConfig.dll
│       │           R2API.LobbyConfig.xml
│       │
│       ├───RiskofThunder-R2API_Networking
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Networking
│       │           R2API.Networking.dll
│       │           R2API.Networking.xml
│       │
│       ├───RiskofThunder-R2API_Orb
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Orb
│       │           R2API.Orb.dll
│       │           R2API.Orb.xml
│       │
│       ├───RiskofThunder-R2API_Prefab
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Prefab
│       │           R2API.Prefab.dll
│       │           R2API.Prefab.xml
│       │
│       ├───RiskofThunder-R2API_RecalculateStats
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.RecalculateStats
│       │           R2API.RecalculateStats.dll
│       │           R2API.RecalculateStats.xml
│       │
│       ├───RiskofThunder-R2API_SceneAsset
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.SceneAsset
│       │           R2API.SceneAsset.dll
│       │           R2API.SceneAsset.xml
│       │
│       ├───RiskofThunder-R2API_Skins
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Skins
│       │           R2API.Skins.dll
│       │           R2API.Skins.xml
│       │
│       ├───RiskofThunder-R2API_Sound
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Sound
│       │           R2API.Sound.dll
│       │           R2API.Sound.xml
│       │
│       ├───RiskofThunder-R2API_TempVisualEffect
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.TempVisualEffect
│       │           R2API.TempVisualEffect.dll
│       │           R2API.TempVisualEffect.xml
│       │
│       ├───RiskofThunder-R2API_Unlockable
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Unlockable
│       │           R2API.Unlockable.dll
│       │           R2API.Unlockable.xml
│       │
│       ├───RiskofThunder-RoR2BepInExPack
│       │   │   CHANGELOG.md
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───RoR2BepInExPack
│       │           RoR2BepInExPack.dll
│       │           RoR2BepInExPack.xml
│       │
│       ├───Risky_Lives-RiskyMod
│       │   │   Full Changelog.txt
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───Risky_Lives-RiskyMod
│       │       │   RiskyMod.dll
│       │       │
│       │       └───language
│       │           ├───en
│       │           │       Equipment.txt
│       │           │       Interactors.txt
│       │           │       Items.txt
│       │           │       Keywords.txt
│       │           │       Survivors.txt
│       │           │
│       │           └───zh-CN
│       │                   Equipment.txt
│       │                   Interactors.txt
│       │                   Items.txt
│       │                   Keywords.txt
│       │                   Survivors.txt
│       │
│       ├───RoR2BepInExPack
│       │       RoR2BepInExPack.dll
│       │       RoR2BepInExPack.xml
│       │
│       ├───Rune580-Risk_Of_Options
│       │       icon.png
│       │       manifest.json
│       │       README.md
│       │       RiskOfOptions.dll
│       │
│       ├───TeamMoonstorm-MoonstormSharedUtils
│       │   │   CHANGELOG.md
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   MoonstormSharedUtils.dll
│       │   │   MoonstormSharedUtils.pdb
│       │   │   README.md
│       │   │
│       │   └───assetbundles
│       │           MoonstormSharedUtils.manifest
│       │           msuassets
│       │           msuassets.manifest
│       │
│       ├───TeamMoonstorm-Starstorm2
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │   Starstorm2.dll
│       │   │   Starstorm2.dll.mdb
│       │   │
│       │   ├───assetbundles
│       │   │       ss2artifacts
│       │   │       ss2artifacts.manifest
│       │   │       ss2base
│       │   │       ss2base.manifest
│       │   │       ss2dev
│       │   │       ss2dev.manifest
│       │   │       ss2equipments
│       │   │       ss2equipments.manifest
│       │   │       ss2events
│       │   │       ss2events.manifest
│       │   │       ss2executioner
│       │   │       ss2executioner.manifest
│       │   │       ss2executioner2
│       │   │       ss2executioner2.manifest
│       │   │       ss2items
│       │   │       ss2items.manifest
│       │   │       ss2main
│       │   │       ss2main.manifest
│       │   │       ss2nemcommando
│       │   │       ss2nemcommando.manifest
│       │   │       ss2nemmando
│       │   │       ss2nemmando.manifest
│       │   │       ss2shared
│       │   │       ss2shared.manifest
│       │   │       ss2vanilla
│       │   │       ss2vanilla.manifest
│       │   │       Starstorm2.manifest
│       │   │
│       │   ├───soundbanks
│       │   │       Starstorm2.pck
│       │   │
│       │   └───SS2Lang
│       │       ├───en
│       │       │       SS2Lang_Artifacts_en.json
│       │       │       SS2Lang_Difficulties_en.json
│       │       │       SS2Lang_Elites_en.json
│       │       │       SS2Lang_Equip_en.json
│       │       │       SS2Lang_Events_en.json
│       │       │       SS2Lang_Expansion_en.json
│       │       │       SS2Lang_Interactables_en.json
│       │       │       SS2Lang_ItemsBoss_en.json
│       │       │       SS2Lang_ItemsLunar_en.json
│       │       │       SS2Lang_ItemsT1_en.json
│       │       │       SS2Lang_ItemsT2_en.json
│       │       │       SS2Lang_ItemsT3_en.json
│       │       │       SS2Lang_NonSurvivorBodies_en.json
│       │       │       SS2Lang_Skins_en.json
│       │       │       SS2Lang_SurvivorBorg_en.json
│       │       │       SS2Lang_SurvivorChirr_en.json
│       │       │       SS2Lang_SurvivorExecutioner2_en.json
│       │       │       SS2Lang_SurvivorExecutioner_en.json
│       │       │       SS2Lang_SurvivorMULE_en.json
│       │       │       SS2Lang_SurvivorNemCaptain_en.json
│       │       │       SS2Lang_SurvivorNemCommando_en.json
│       │       │       SS2Lang_SurvivorNemmando_en.json
│       │       │       SS2Lang_SurvivorPyro_en.json
│       │       │       SS2Lang_UnlocksArtifacts_en.json
│       │       │       SS2Lang_UnlocksBorg_en.json
│       │       │       SS2Lang_UnlocksChirr_en.json
│       │       │       SS2Lang_UnlocksEquips_en.json
│       │       │       SS2Lang_UnlocksExecutioner_en.json
│       │       │       SS2Lang_UnlocksItems_en.json
│       │       │       SS2Lang_UnlocksNemmando_en.json
│       │       │       SS2Lang_UnlocksPyro_en.json
│       │       │       SS2Lang_UnlocksVanilla_en.json
│       │       │
│       │       ├───es-ES
│       │       │       SS2Language_es-419.json
│       │       │
│       │       ├───FR
│       │       │       SS2Language_FR.json
│       │       │
│       │       ├───pt-BR
│       │       │       SS2Lang_Artifacts_pt.json
│       │       │       SS2Lang_Difficulties_pt.json
│       │       │       SS2Lang_Elites_pt.json
│       │       │       SS2Lang_Equip_pt.json
│       │       │       SS2Lang_Events_pt.json
│       │       │       SS2Lang_Expansion_pt.json
│       │       │       SS2Lang_Interactables_pt.json
│       │       │       SS2Lang_ItemsBoss_pt.json
│       │       │       SS2Lang_ItemsLunar_pt.json
│       │       │       SS2Lang_ItemsT1_pt.json
│       │       │       SS2Lang_ItemsT2_pt.json
│       │       │       SS2Lang_ItemsT3_pt.json
│       │       │       SS2Lang_NonSurvivorBodies_pt.json
│       │       │       SS2Lang_Skins_pt.json
│       │       │       SS2Lang_SurvivorBorg_pt.json
│       │       │       SS2Lang_SurvivorChirr_pt.json
│       │       │       SS2Lang_SurvivorExecutioner_pt.json
│       │       │       SS2Lang_SurvivorMULE_pt.json
│       │       │       SS2Lang_SurvivorNemExecutioner_pt.json
│       │       │       SS2Lang_SurvivorNemmando_pt.json
│       │       │       SS2Lang_SurvivorPyro_pt.json
│       │       │       SS2Lang_UnlocksArtifacts_pt.json
│       │       │       SS2Lang_UnlocksBorg_pt.json
│       │       │       SS2Lang_UnlocksChirr_pt.json
│       │       │       SS2Lang_UnlocksEquips_pt.json
│       │       │       SS2Lang_UnlocksExecutioner_pt.json
│       │       │       SS2Lang_UnlocksItems_pt.json
│       │       │       SS2Lang_UnlocksNemmando_pt.json
│       │       │       SS2Lang_UnlocksPyro_pt.json
│       │       │       SS2Lang_UnlocksVanilla_pt.json
│       │       │
│       │       ├───RU
│       │       │       SS2Lang_Artifacts_RU.json
│       │       │       SS2Lang_Difficulties_RU.json
│       │       │       SS2Lang_Elites_RU.json
│       │       │       SS2Lang_Equip_RU.json
│       │       │       SS2Lang_Events_RU.json
│       │       │       SS2Lang_Expansion_RU.json
│       │       │       SS2Lang_Interactables_RU.json
│       │       │       SS2Lang_ItemsBoss_RU.json
│       │       │       SS2Lang_ItemsLunar_RU.json
│       │       │       SS2Lang_ItemsT1_RU.json
│       │       │       SS2Lang_ItemsT2_RU.json
│       │       │       SS2Lang_ItemsT3_RU.json
│       │       │       SS2Lang_NonSurvivorBodies_RU.json
│       │       │       SS2Lang_Skins_RU.json
│       │       │       SS2Lang_SurvivorBorg_RU.json
│       │       │       SS2Lang_SurvivorChirr_RU.json
│       │       │       SS2Lang_SurvivorExecutioner_RU.json
│       │       │       SS2Lang_SurvivorMULE_RU.json
│       │       │       SS2Lang_SurvivorNemExecutioner_RU.json
│       │       │       SS2Lang_SurvivorNemmando_RU.json
│       │       │       SS2Lang_SurvivorPyro_RU.json
│       │       │       SS2Lang_UnlocksArtifacts_RU.json
│       │       │       SS2Lang_UnlocksBorg_RU.json
│       │       │       SS2Lang_UnlocksChirr_RU.json
│       │       │       SS2Lang_UnlocksEquips_RU.json
│       │       │       SS2Lang_UnlocksExecutioner_RU.json
│       │       │       SS2Lang_UnlocksItems_RU.json
│       │       │       SS2Lang_UnlocksNemmando_RU.json
│       │       │       SS2Lang_UnlocksPyro_RU.json
│       │       │       SS2Lang_UnlocksVanilla_RU.json
│       │       │
│       │       ├───tr
│       │       │       SS2Language_tr.json
│       │       │
│       │       └───zh-CN
│       │               SS2Lang_Artifacts_zh-CN.json
│       │               SS2Lang_Difficulties_zh-CN.json
│       │               SS2Lang_Elites_zh-CN.json
│       │               SS2Lang_Equip_zh-CN.json
│       │               SS2Lang_Events_zh-CN.json
│       │               SS2Lang_Expansion_zh-CN.json
│       │               SS2Lang_Interactables_zh-CN.json
│       │               SS2Lang_ItemsBoss_zh-CN.json
│       │               SS2Lang_ItemsT1_zh-CN.json
│       │               SS2Lang_ItemsT2_zh-CN.json
│       │               SS2Lang_ItemsT3_zh-CN.json
│       │               SS2Lang_NonSurvivorBodies_zh-CN.json
│       │               SS2Lang_Skins_zh-CN.json
│       │               SS2Lang_SurvivorBorg_zh-CN.json
│       │               SS2Lang_SurvivorChirr_zh-CN.json
│       │               SS2Lang_SurvivorExecutioner_zh-CN.json
│       │               SS2Lang_SurvivorMULE_zh-CN.json
│       │               SS2Lang_SurvivorNemExecutioner_zh-CN.json
│       │               SS2Lang_SurvivorNemmando_zh-CN.json
│       │               SS2Lang_SurvivorPyro_zh-CN.json
│       │               SS2Lang_UnlocksArtifacts_zh-CN.json
│       │               SS2Lang_UnlocksBorg_zh-CN.json
│       │               SS2Lang_UnlocksChirr_zh-CN.json
│       │               SS2Lang_UnlocksEquips_zh-CN.json
│       │               SS2Lang_UnlocksExecutioner_zh-CN.json
│       │               SS2Lang_UnlocksItems_zh-CN.json
│       │               SS2Lang_UnlocksNemmando_zh-CN.json
│       │               SS2Lang_UnlocksPyro_zh-CN.json
│       │               SS2Lang_UnlocksVanilla_zh-CN.json
│       │
│       ├───TheRealElysium-EmptyChestsBeGone
│       │   │   icon.png.old
│       │   │   manifest.json.old
│       │   │   README.md.old
│       │   │
│       │   └───ECBG
│       │           EmptyChestsBeGone.dll.old
│       │
│       ├───tristanmcpherson-R2API
│       │   │   icon.png
│       │   │   manifest.json
│       │   │   README.md
│       │   │
│       │   └───R2API.Legacy
│       │           R2API.dll
│       │           R2API.Skins.dll
│       │           R2API.Skins.xml
│       │
│       └───XoXFaby-BetterUI
│           │   icon.png
│           │   manifest.json
│           │   README.md
│           │
│           └───BetterUI
│               │   BetterUI.dll
│               │   BetterUnityPlugin.dll
│               │
│               └───Languages
│                       en.json
│                       ru.json
│                       UA.json
│                       zh-CN.json
│
└───_state
        installation_state.yml

**Comment by xiaoxiao921** [comment]
Should hopefully be fixed if you update to `BepInExPack v5.4.2113` and `BepInEx_GUI v3.0.2`

Sadly i'm still not sure of the exact cause of why it happened, for future reference:

Either the bepinex/core files were somehow not the one from BepInExPack v5.4.2112 but the dependencies were (the tree /f output show that the 2112 dependencies were correctly installed) or somehow File.Delete / Directory.Delete from BepInEx.Preloader.dll were getting denied in someway by Windows

Anyway i've added two more fail safe in case old files were still present. So this definitly should not happen anymore (I hope)

**Comment by 15kalind** [comment]
Yep it looks fixed so far! Thanks for the quick followup.

**Comment by ebkr** [comment]
Closing as it seems to be fixed
