### ISSUE TITLE
[BUG] - wrong executable for BoneLab Oculus

### ISSUE THREAD

**Issue by Rick007110** [ebkr/r2modmanPlus#1036]
**Describe the bug**
When you select "Oculus Store" for BoneLab and try to select the executable, you need to select BONELAB_Steam_Windows64 for some reason instead of BONELAB_Oculus_Windows64. This results in a error telling you to ensure that the game directory has been set correctly in the settings, which is impossible right now. Making people with Oculus unable to use r2mm for BoneLab.

**To Reproduce**
1. Go to 'Bonelab'
2. Click on 'Oculus Store'
3. Click on 'Settings'
4. Click on 'Locations'
5. Click on 'Change BONELAB directory'
6. Navigate to where the executable is
7. You will see that it shows BONELAB_Steam_Windows64.exe instead of BONELAB_Oculus_Windows64.exe

**Expected behavior**
r2mm should be looking for the BONELAB_Oculus_Windows64.exe, not BONELAB_Steam_Windows64.exe

**Screenshots**
![image](https://github.com/ebkr/r2modmanPlus/assets/71711131/11b5bc0b-bb60-4c19-8560-6b56b4394764)
![image](https://github.com/ebkr/r2modmanPlus/assets/71711131/9e8a94a0-f64a-43b3-bc3b-727f3bda5db0)

**Comment by ebkr** [comment]
This should be fixed as of 3.1.42

**Comment by Rick007110** [comment]
> 

Hi there! It wasn't fixed in 3.1.42. I still have this issue and it's pretty annoying. Could you please do another attempt on fixing this? It's been nearly 2 months. Thanks!

**Comment by capjoan74** [comment]
did you find any fix for this? currently having the same issue
