### ISSUE TITLE
Steam launch command not working

### ISSUE THREAD

**Issue by LeagueRaINi** [ebkr/r2modmanPlus#109]
**Issue:** 
Risk of Rain 2 launches without BepInEx beeing run

**What i have tried:**
- Setting the Steam and Risk of Rain 2 directory again in the mod launcher
- Writing the full Risk of Rain 2 path into the Steam launch command

**What does work:**
- Adding Risk of Rain 2 as non steam game and appending the following launch command:
`--doorstop-enable true --doorstop-target r2modman\BepInEx\core\BepInEx.Preloader.dll`
- Using `targetAssembly=r2modman\BepInEx\core\BepInEx.Preloader.dll` in`doorstop_config.ini` in the Risk of Rain 2 directory and launching `Risk of Rain 2.exe` manually

**Possible solution:**
Since you ask the user for the Risk of Rain 2 directory anyways why not launch the `Risk of Rain 2.exe` with the `--doorstop-enable true --doorstop-target r2modman\BepInEx\core\BepInEx.Preloader.dll ` parameters directly instead of launching it through steam

**OS:**
Win10 - 1909 [18363.657]

**Other:**
I got Steam on my nvme [`C:\`] and my Steam games on my hdd [`D:\`]

**Comment by ebkr** [comment]
Thanks for the detailed information.

Are you trying to launch the game through the r2modman exe? If you are, does an error overlay appear?

I don't launch the game directly using the EXE because Steam has a warning appear about custom parameters.

**Comment by LeagueRaINi** [comment]
> Are you trying to launch the game through the r2modman exe? If you are, does an error overlay appear?

Yes i'm trying to start it through your mod manager [[clip](https://streamable.com/gjwva)]

> Can you also try running it as an administrator?

Doesnt seem to make a difference

**Comment by ebkr** [comment]
Could you try re-installing the game? Ensure everything is gone from the Risk of Rain 2 folder before redownloading.

**Comment by LeagueRaINi** [comment]
> Could you try re-installing the game? Ensure everything is gone from the Risk of Rain 2 folder before redownloading.

Still doesnt work

**Comment by ebkr** [comment]
Can you try switching to legacy mode in the manager?

**Comment by LeagueRaINi** [comment]
> Can you try switching to legacy mode in the manager?

its not he symlink that doesnt work its starting the game through steam with the doorstop params

**Comment by ebkr** [comment]
I'm not sure, this hasn't happened before, there doesn't appear to be any errors, and the game still launches. I'll look in to it, and it'll likely involved a config option to launch using the EXE directly.

**Comment by ebkr** [comment]
For something to test, could you try fully quitting steam prior to launching through the manager?

**Comment by LeagueRaINi** [comment]
> For something to test, could you try fully quitting steam prior to launching through the manager?

same bug

**Comment by ebkr** [comment]
Does this work if you run it through PowerShell?
`Start-Process "steam://run/632360//--doorstop-enable true --doorstop-target r2modman\\BepInEx\\core\\BepInEx.Preloader.dll"`

**Comment by LeagueRaINi** [comment]
> Does this work if you run it through PowerShell?
> `Start-Process "steam://run/632360//--doorstop-enable true --doorstop-target r2modman\\BepInEx\\core\\BepInEx.Preloader.dll"`
> 
> Steam will have a warning popup prior to launching the game.

doesnt work either

**Comment by ebkr** [comment]
And if you replace the backslashes with single backslashes, same result?

If it is, it's weird that manually adding it as a non steam game works, as it's doing the exact same stuff.

**Comment by ebkr** [comment]
Someone else has just reported having this issue on the Thunderstore Discord server.

The solution was to uninstall the manager, and then clear out all folders relating to r2modman under AppData subdirectories.

You'll then have to manually remove the r2modman folder under Risk of Rain 2.

After that, you should be able to reinstall the manager, and everything should be fine.

If you have a profile you want to keep, you can export it through the settings, and move the exported file to a different location.

**Comment by LeagueRaINi** [comment]
ok so i uninstalled r2modman & cleaned the RoR2 folder and removed the 2 r2modman folders from appdata and it still doesnt work

**Comment by LeagueRaINi** [comment]
funny enough i just looked at the startup params of RoR2 and saw that it started from `C:\`, what happened is that instead of using my game copy on `D:\Games\Steam\<RoR2>` like it did for every other game i have there it silently installed a new copy on `C:\`
