### ISSUE TITLE
Add support for a portable mode

### ISSUE THREAD

**Issue by ebkr** [ebkr/r2modmanPlus#110]

**Comment by Deide** [comment]
Is this supported now? How do I enable portable mode? Everything I do still relies on (non-portable) appdata. Portable mode should be completely self contained to its own folder.

**Comment by ebkr** [comment]
You can change the directory by going to Settings -> Change data directory.
Simply change this location to an empty folder next to the exe.

This issue was for the non-setup exe.

**Comment by Deide** [comment]
That changes the `appdata/r2modman-local` directory, right? But that configuration itself is stored in the `appdata/r2modman` directory. I suppose there's no way around this?

**Comment by ebkr** [comment]
Yeah, nothing I can really do about that AFAIK, pretty sure it’s an electron restriction.

**Comment by Deide** [comment]
This might be asking for too much, but would it be possible for the portable release's data-local folder to default to the same directory as the executable?
At the moment, changing to an already populated data-local folder from within the settings complains about there already being files and folders within it, which means you have to fiddle around with moving the contents to somewhere else before changing the setting, and then moving them all back.

Thanks for your time regardless.

**Comment by ebkr** [comment]
Just make a folder next to the executable and point it to that. It’s intentionally designed to be empty.

**Comment by Deide** [comment]
I'm sorry for not elaborating earlier and I'm not necessarily expecting you to fix it. The following is for anyone that stumbles across this with questions/confusion over the portability as of version 3.1.17.

Okay, so when the `$appdata/r2modman` folder is not present, it gets generated with the default "data-local" folder being set to `$appdata/r2modman-local`. If you switch between different computers (or OS versions), you run into trouble - ie. it's not portable in the usual sense of the word. As far as I can tell, there is no way to programmatically set a default configuration.
It also makes it difficult to support in-place whole external updates, which is another of my use cases.
