### ISSUE TITLE
[FEATURE REQUEST] - "Lethal Company" Support

### ISSUE THREAD

**Issue by nurdism** [ebkr/r2modmanPlus#1100]
**What problem does the feature request solve?**
Lethal Company Support https://store.steampowered.com/app/1966720/Lethal_Company/

**Comment by nurdism** [comment]
was added to https://thunderstore.io/c/lethal-company/

**Comment by Pieman492** [comment]
Merged in #1101

**Comment by KlutzyBubbles** [comment]
Can this be put in a release?

**Comment by KlutzyBubbles** [comment]
Temporary solution for people who don't know how to build https://github.com/KlutzyBubbles/r2modmanPlus/releases 

I have created a fork to build the develop branch using the same workflow as the releases in this repo. I don't believe this will affect any existing profiles when updating but cannot be sure

**Comment by KlutzyBubbles** [comment]
This can now be closed as a new release has been made https://github.com/ebkr/r2modmanPlus/releases/tag/v3.1.45
