### ISSUE TITLE
[BUG] - Not Showing Launch Arguments For Proton Games

### ISSUE THREAD

**Issue by SaltSouls** [ebkr/r2modmanPlus#1129]
**Describe the bug**
After looking at the launch arguments for one game, it no longer displays them for any other games

**To Reproduce**
1. Launch R2
2. Select game
3. See launch arguments
4. Exit R2
5. Launch R2
6. Select game
7. Don't see launch arguments
8. ???
9. Profit

**Expected behavior**
Should show launch arguments or at least have an option somewhere that brings them up

**Comment by forslu** [comment]
@SaltSouls I'm unable to recreate this issue. 

In step 3, where are you seeing the launch arguments? I'm able to see them by going to Settings>Debugging>Set Launch Parameters. 
Is that the missing option you are referring to?

**Comment by SaltSouls** [comment]
Yeah, sorry. It was late at night when I found this and I realized later that you don't use the launch arguments for games running using proton. I just forgot to close the issue.
