### ISSUE TITLE
[FEATURE REQUEST] - New Icon

### ISSUE THREAD

**Issue by Enderteck** [ebkr/r2modmanPlus#1135]
**What problem does the feature request solve?**

The Icon looks out of Windows XP

**Example mock-up (optional)**

Example of a replacement Icon I made in 2 minutes, needs feedback and adjustments.

https://raw.githubusercontent.com/Enderteck/Papitela/2aec713c6c10040f4dfbce901936ee299158da0e/Added%20icons%20and%20Templates/Created%20icons/r2modman.svg

**Additional information (optional)**

The square icons looks really out of place and outdated. I'm willing to create one to replace it !

**Comment by bubin7766** [comment]
Font is different to it’s iconic look and it *looks* off center
Other than changing the font and icon shape this does not feel _new_ in any way whatsoever
