### ISSUE TITLE
[FEATURE REQUEST] - Add Capcom games mod support; can't "like" or "dislike" some mods

### ISSUE THREAD

**Issue by CoolLKKPS** [ebkr/r2modmanPlus#1139]
**What problem does the feature request solve?**
Add Capcom games mod support if u can able to contact official;
specially, "Monster Hunter" and "Resident Evil", capcom don't know what is the player really need.

idk i should can able to post this in here? idk where to find the support page, forgive me.

**Comment by codakairos** [comment]
I think r2modman only offers support for Unity Games. Capcom games are most likely made using a proprietary engine... you can use nexus mods instead

**Comment by CoolLKKPS** [comment]
ok
