### ISSUE TITLE
Appimage or Deb won't launch. Nvidia Issue?  [BUG] - Issue title

### ISSUE THREAD

**Issue by KellyDerg** [ebkr/r2modmanPlus#1156]
r2modman will open a window and hang in place before abrubtly closing.

How to recreate -

Attempt to open the Deb or App image.

How to fix.

Add --no-sandbox to the .desktop file's arguments (For Deb)

GPU on system is Nvidia 1660GTX

**Comment by DeltaNachos** [comment]
Getting same issue with both app image and ebuild.

Gentoo x86_64 6.1.67
Plasma 5.27.10
Nvidia RTX 4090 on driver 535.146.02

**Comment by Atomic2ds** [comment]
Getting same issue with specs below

Ryzen 5 3600x
GTX 1660 Super
16GB DDR4 RAM

Adding --no-sandbox also fixed it for me

**Comment by neilunger** [comment]
Dupe of #978

**Comment by dnkmmr69420** [comment]
ah thank you so much. This allows me to run it on a NVIDIA powered system
