### ISSUE TITLE
[FEATURE REQUEST] - Enable right-click or add a "Copy" button for launch parameters.

### ISSUE THREAD

**Issue by Guessed8822** [ebkr/r2modmanPlus#1158]
**What problem does the feature request solve?**
The app as a whole and the "Launching the game from mod manager" section in particular doesn't respond when right-clicked, which makes copying the parameters on a Steam Deck an enormous hassle. Adding a button to copy to clipboard or just enabling right-click would be very helpful.

**Comment by aph3rson** [comment]
+1, I had to modify my steam controller configuration to add dedicated copy/paste binds to my controller. Not ideal.
