### ISSUE TITLE
[BUG] - Failed to export as code

### ISSUE THREAD

**Issue by YuroKashine** [ebkr/r2modmanPlus#1164]
Describe the bug
The moment i try to export my lethal company profile as a code it gives me an error about not able to read properties of undefined (reading 'key') and i have no clue what that might be. Please fix

To Reproduce

Go to 'settings'
Click on 'export profile as a code'
See error below
Expected behavior
Ofcourse i expect thunderstore to make a code like usual that i can give to my friends to play together.

Screenshots
![image](https://github.com/ebkr/r2modmanPlus/assets/156379068/ce5f78b2-cb52-43f3-b667-630b0121824c)

Additional context
Im doing configurations in the mod config files. just the settings, nothing with codes and such. i do what i always do in the configs and exporting as a code always worked untill 30 minutes ago and i even removed the configs i made to reset them and it still didnt work.

**Comment by YuroKashine** [comment]
Also for the brief moment it worked yesterday i sent my friend a code and he said this morning he got this error message when trying to import it.

![image](https://github.com/ebkr/r2modmanPlus/assets/156379068/4bfa4c41-1b3c-4e37-8758-634a50d3d375)

Either way exporting and importing profiles as a code does not work

**Comment by codakairos** [comment]
same here
