### ISSUE TITLE
[BUG] - Crashing when trying to generate share code

### ISSUE THREAD

**Issue by Agent-bonio** [ebkr/r2modmanPlus#1197]
**Describe the bug**
Launcher crashes when clicking on "Share" button
**To Reproduce**
1. Select (in my case) 'Lethal Company' on game selection tab
2. Select profile
3. Click on 'Share'
4. See launcher crash

**Expected behavior**
Launcher shouldn't crash, instead it should generate code to share your mods

**Screenshots**
Not revelant
**Additional context**
In my case, I have some mods for Lethal Company. The problem is that after exceeding about 60 mods, the "Share" button started crashing the launcher, while exporting in file still works

**Comment by ArchOwlen** [comment]
There seems to be some performance issues between R2Modman/Thunderstore with Lethal Company specifically, so keep that in mind when modding 

I myself have had issues when generating a code (it took over 5-10 minutes for it to generate with 200+ mods)

So my recommendation for now is to click generate code only once, and leave it be until it can try generating a code
Clicking multiple times may increase the chances of it crashing, or the amount of time it takes to generate in the first place

**Comment by mdsmendes94** [comment]
Valheim Thunderstore also has the same issue

**Comment by ebkr** [comment]
There was recently a limit on the file size for exporting as a code. Are you still able to replicate the crash?
