### ISSUE TITLE
[BUG] - The UI is painfully slow when updating state

### ISSUE THREAD

**Issue by juls0730** [ebkr/r2modmanPlus#1211]
**Describe the bug**
The UI is painfully slow when updating the state of profiles that have lots of mods and games that contain profiles.

**To Reproduce**
1. open Lethal Company
2. make a new profile
3. download a heavy modpack, for example, BleasdalePack

**Expected behavior**
The UI should be snappy, like in most other places in the application.

**Screenshots**

https://github.com/ebkr/r2modmanPlus/assets/62722391/7c23a93e-cc7e-4141-96df-0828a419348d

**Additional context**
I would love to help out with solving this, but the project is too much of a pain to get working, unfortunately (screw electron), but I believe the lag has to do with the application storing an excess amount of information, thus why installing one or two mods is fine, but if you install 10 or 20, it multiplies. I might try to contribute if I can get a working project, I hope I can see improvement on this, I know Lethal Company players have uncovered a slew of issues that have been patched pretty quickly thanks to the speed of the amazing maintainers. Running on Arch Linux 6.7.2-arch1-1

**Comment by juls0730** [comment]
although maybe my assumption is completely wrong, who knows

**Comment by Dreadrith** [comment]
Same here. I've been putting up with this but It's kind of too much. Often times had friends wait on me ages to make some changes before we can play due to the amount of time each interaction takes.

**Comment by MythicManiac** [comment]
Just commenting to note that performance in games & profiles that have large amounts of mods is something that's being actively worked on. Proper fixes will require larger changes that will take a while to get done, but there's several smaller improvements that we've been able to work through already with significant improvements.

**Comment by FranseFrikandel** [comment]
Release 3.1.47 already seems to make very major improvements in this front, so if anyone happens to stumble across this issue I'd definetly recommend updating.

**Comment by Dreadrith** [comment]
Just updated. It's SO much better now. Thank you for the improvements!

**Comment by rayzr522** [comment]
+1, id vote for this issue to be closed as it now seems plenty fast enough to not be a noticeable issue anymore. I'm sure future refactors could bring greater improvements but as it stands it's already a non issue imo :)

**Comment by juls0730** [comment]
oh yes, this was solved in the 3.1.46 update thanks to the great contributors on that update. I had this open a few days ago and was going to close it, but it must've gotten away from me >~<
