### ISSUE TITLE
[FEATURE REQUEST] - u cannot login account while using r2modman or Thunderstore mod manager? and u even cannot leave comment or message to mod dev?

### ISSUE THREAD

**Issue by CoolLKKPS** [ebkr/r2modmanPlus#1214]
**What problem does the feature request solve?**
topic

**Example mock-up (optional)**
topic

**Additional information (optional)**
i really want to choose label to bug, bcz even modworkshop are already support this for idk over 3 years? how tf u guys still not support that. how i can contact with mod dev if don't have comment/message function and they didn't leave any info to contact?

**Comment by ebkr** [comment]
This is more related to the site than it is to the manager. I'll close this. Happy to re-open if you can make it more manager-oriented.
