### ISSUE TITLE
[DOCUMENTATION REQUEST] - Manual installation r2modman recommendation

### ISSUE THREAD

**Issue by iwanPlays** [ebkr/r2modmanPlus#1255]
I just started using r2modman with https://thunderstore.io/c/receiver-2/ but for example https://github.com/BepInEx/BepInEx.ConfigurationManager is not uploaded/maintained there, nor ist UnityExplorer, just to list two popular packages.

What would be the best way to manually install mods? Is there a recommendation from r2modman perspective?

I went to the location of **settings/browse data folder** and put it there. This works. but in the end it could lead to the kind of cluttering that drove me to using r2modman in the first place (putting files/folders into game folder structures that mix with original game data and game config files leading to error messages and out of date packages.

Perhaps a FAQ section "How do I manually install plugins/mods?" could be added.

Perhaps a "list all files that are not part of packages" or even "nuke data folder" feature could be added for cleanup.

**Comment by ebkr** [comment]
Settings -> Import local mod
