### ISSUE TITLE
[FEATURE REQUEST] - Draggin' mods inna profiles ta move position!

### ISSUE THREAD

**Issue by Flloppis** [ebkr/r2modmanPlus#1281]
**What problem does the feature request solve?**
There issa new feature in Thunderstore Modsi Launcher which allows ya ta drag ta move mods inna yer My mods page!

**Example mock-up (optional)**
Drag ta move position inna Mymods! 

**Additional information (optional)**
![image](https://github.com/ebkr/r2modmanPlus/assets/157853816/293de0ef-b209-443c-a61d-007b4eac3b77)

**Comment by ebkr** [comment]
This is already a thing?

**Comment by Flloppis** [comment]
:O YIPEEEEEEE!!!!!!!
