### ISSUE TITLE
[FEATURE REQUEST] - Addin' Content Warnin'!

### ISSUE THREAD

**Issue by Flloppis** [ebkr/r2modmanPlus#1284]
**What problem does the feature request solve?**
Thunderstore Manager hassa Content Warnin' but-- R2Modman doesnt.

**Example mock-up (optional)**
Addin' Content Warnin' ta R2Modman

**Additional information (optional)**
![image](https://github.com/ebkr/r2modmanPlus/assets/157853816/2532a642-7e0c-4b71-8efb-06626c1131d8)
![image](https://github.com/ebkr/r2modmanPlus/assets/157853816/ab10f5ff-f3d9-4775-9c87-1b2fb939cfde)

**Comment by antv199** [comment]
Mentioned already here #1283 .

It'll probably take a while, though

**Comment by M1n-74316D65** [comment]
You can fork it and go to the 'Actions' tab. From there, click on 'Release' and select 'Run Workflow'. Wait for the process to complete, then go to the 'Release' section on the fork's main page to access the updated version.

Alternatively, you can download it from [my fork](https://github.com/M1n-74316D65/r2modmanPlus/releases/tag/untagged-dee07249246da839d874), where I have already done it.

**Comment by vikingnope** [comment]
Already added
