### ISSUE TITLE
[BUG] - missing 32bit libraries (.Appimage) or wont start at all (.pacman) ("Arch"/EndeavourOS)

### ISSUE THREAD

**Issue by Falclairen** [ebkr/r2modmanPlus#1296]
**Describe the bug**
The .pacman App wont open after install and the Appimage is missing 32bit libraries

**To Reproduce**
- .pacman file
1. sudo pacman -U "file_path"
2. try to run the .desktop file (via an app launcher or the file itself, doesnt matter)
3. seems to open properly but crashes a few seconds after (I dont even get to click on anything)
4. gives no error (even when setting the Terminal argument to "true" in the .desktop file doesnt seem to help)

- .Appimage file
1. manually creates the .desktop file (or using a tool to do so)
2. starts the desktop file
3. selects my games
4. selects my mods
5. indicate which directories to use (if necessary)
6. clicks on start modded, gives me an error (image 1)
7. it still tries to proceed, gives me an other error (image 2)

**Expected behavior**
I expected the Appimage to have all the dependencies and the Pacman to just work I guess

**Screenshots**

Image 1
![image 1](https://github.com/ebkr/r2modmanPlus/assets/144671478/fa4e9d0d-1855-4fd8-befc-7aec7d2b16e1)
Image 2
![image 2](https://github.com/ebkr/r2modmanPlus/assets/144671478/f2945480-944d-4bed-b848-5b2e470030e5)

**Additional context**
I have the 32 bit structure enabled (or at least I should) so I dont really know how/why Id be missing those libraries and for the Pacman app I have no idea

**Comment by ebkr** [comment]
These are requirements from the Steam executable when using the `--applaunch` args from command line. This is not a manager issue and I'd consider this a Steam issue as it isn't installing base libraries that are required (as shown in your screenshot) by the Steam application itself.
