### ISSUE TITLE
[BUG] - Doesnt launch properly on archlinux

### ISSUE THREAD

**Issue by cytoplasmoid** [ebkr/r2modmanPlus#1297]
R2modman fails to launch at all ( tried appimage, tar.gz, binary from aur)

Outputs the following message if run from command prompt:
 
> $ r2modman
> starting server on  /tmp/app.r2mm 
> starting TLS server false
> starting server as Unix || Windows Socket
> [7607:0415/181006.354307:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
> Trace/breakpoint trap (core dumped)

Download appimage from the releases page
Set as executable
Run

Expected behavior:
App opens and functions

Screenshots:
![image](https://github.com/ebkr/r2modmanPlus/assets/164794099/fe022f54-c293-4219-92a5-39b1ca5cfbdb)

Opens like this for about 2 seconds before closing ^

Additional context: Running up to date archlinux, nvidia 1070 card

**Comment by axcel34** [comment]
This works on Nobara as well!

**Comment by ebkr** [comment]
Duplicated of #978
