### ISSUE TITLE
[BUG] - Steam / Steam Overlay not opening when starting a game.

### ISSUE THREAD

**Issue by leon-emilio** [ebkr/r2modmanPlus#1324]
**Describe the bug**
I'm trying to open the steam overlay but it doesn't work, I cannot make screenshots either.

**To Reproduce**
1. Open r2modman
2. Start the game (in this case lethal company)
3. Press Shift + tab

Instead of the steam overlay opening, nothing happens.

**Comment by ebkr** [comment]
This is related to BepInEx. It is not a manager issue.
