### ISSUE TITLE
[BUG] - tbh worse update that even more slowing me down from managing modlist

### ISSUE THREAD

**Issue by CoolLKKPS** [ebkr/r2modmanPlus#1390]
**Describe the bug**
see `Expected behavior`

**To Reproduce**
see `Expected behavior`

**Expected behavior**
Disable modlist refresh automatically, instead add button to manually refresh modlist
Refreshing modlist won't crash the client

Original are already send to: https://github.com/electron/electron/issues/42729

**Screenshots**
None.

**Additional context**
see `Expected behavior`

**Comment by CoolLKKPS** [comment]
Let me use my native dialect to tell u guys how mad i am with this update rn:
连MOD管理器都做不清楚：连续崩溃5次以上，还占用资源（特指没妈设计的`自动刷新模组列表功能`）

**Comment by CoolLKKPS** [comment]
i don't care now, i will use windows firewall block `modman` connection to make sure my progress isn't effect, no auto refresh modlist

**Comment by MythicManiac** [comment]
Hey, there's a significant performance improvement for the mod sync being worked on, currently it looks like we should have a release with it included sometime next month.
