### ISSUE TITLE
[FEATURE REQUEST] - Add "Other" manager option for BombRush Cyberfunk

### ISSUE THREAD

**Issue by RobotZGalaxy** [ebkr/r2modmanPlus#1411]
I'm using the Gig games installation of the game on my Linux laptop and I'm unsure of how to alter the directories the launcher is using to get it to work. Would be nice to have a more simple way of doing it.

**Comment by ebkr** [comment]
Apologies for the late reply, what is the name of the exe for BRC?

**Comment by RobotZGalaxy** [comment]
> Apologies for the late reply, what is the name of the exe for BRC?

Sorry for the even later reply lol, it is Bomb Rush Cyberfunk.exe
