### ISSUE TITLE
[BUG] - Changing game directory doesn't work as expected.

### ISSUE THREAD

**Issue by asaguda** [ebkr/r2modmanPlus#1434]
Due to the lukewarm (if generous) reception of Seekers of the Storm's launch, I decided I didn't want anything to do with it, and I downloaded an older version of Risk of Rain 2 via Steam depots to keep playing an older version with mods.
I then use the 'Change Risk of Rain 2 directory' option in r2modman to point it at the downloaded depot version's .exe file. However, r2modman seems to always launch the installed Steam copy, instead of adhering to the directory I've just pointed it at.

1. I followed the guide to download the older version on Reddit, the first option involving the steam_appid.txt. https://www.reddit.com/r/riskofrain/comments/1f4klin/psa_how_to_downgrade_the_game_on_steam/
2. In r2modman, I changed the directory to point at the depot version .exe.
3. Clicking run modded or vanilla, it launches the live version .exe.

The expected behaviour is that it would launch the depot version .exe I've pointed it at.
While testing I've found the steam_appid.txt doesn't appear to be necessary for me for whatever reason, launching the depot .exe manually gives me the correct old version. But with/without the steam_appid.txt, with the game and depot version on the same or different drives, r2modman always launches the Steam version.

![image](https://github.com/user-attachments/assets/f754e825-11f3-48a1-adcb-8c63f7197909)

**Comment by ebkr** [comment]
This is due to the way the manager launches games.

The games are launched using Steam.exe and not the game executable which has two benefits:
1. Anti piracy
2. Resolves an issue where Steamworks may not be initialised

I don't consider this a bug but I can see how it's potentially confusing.

**Comment by asaguda** [comment]
That's fair enough, closing.
