### ISSUE TITLE
[BUG] - ENOENT: no such file or directory, open: compatdata/632360/pfx/user.reg

### ISSUE THREAD

**Issue by Reishimanfr** [ebkr/r2modmanPlus#1452]
**Describe the bug**
Launching Risk of Rain 2 with mods installed **on linux** fails with the following error:
```
ENOENT: no such file or directory, open '/mnt/hdd/Steam/steamapps/compatdata/632360/pfx/user.reg'
```

**To Reproduce**
1. Install some mods
2. Open the vanilla game first
3. Close the game and attempt to run modded

**Expected behavior**
For the game to launch just fine

**Additional context**
So far I've tried manually creating the file and deleting the `632360` directory in `compatdata`. As you may've guessed neither of those worked

**Comment by Reishimanfr** [comment]
Forgot to mention, I'm running arch with hyprland as my DE of choice but I don't think the latter one is very relevant

**Comment by Reishimanfr** [comment]
Welp, looks like it was a path issue all along! Sorry for the useless bug report

**Comment by SteamRex25** [comment]
how did you get it fixed?
