### ISSUE TITLE
Refresh r2modman

### ISSUE THREAD

**Issue by otjamin** [ebkr/r2modmanPlus#1507]
Since the r2modman repository has been around for a few years, I thought it was time to modernize the application. Some of the outdated versions already lead to errors (e.g. Electron 11 #1395). But also many other dependencies have not been updated for a long time. It also looks like there are a some orphaned files and dependencies.

Please let me know if this is a task that, if done well, would be welcome before I start. @ebkr 

I am also grateful and open to suggestions and ideas on this topic.

**Comment by candroid-man** [comment]
I would LOVE to see r2modman on Flathub, or perhaps even distro repositories for popular distros like Fedora, Arch, etc.

**Comment by otjamin** [comment]
I'm closing this, since r2modman has been updated (at least the Electron version) and my problem with Linux is solved for now.

There are still many outdated packages, but unfortunately I don't have the time at the moment.
