### ISSUE TITLE
interface improvement

### ISSUE THREAD

**Issue by aerao** [ebkr/r2modmanPlus#152]
hi! congratulations on your mod.
I have a suggestion,

In the  mod/installed interface :

1. I wanted to know if, by default, it would be possible to disable collapse (or add an option in the parameters) to better see the list of mods and updates, to avoid scrolling.

2. Allow activation and deactivation of mods more quickly.

Thx!

Here is an example, without collapse, by default:
![ror2](https://user-images.githubusercontent.com/20991213/79123584-c7475d80-7d9a-11ea-828b-6699c4235168.jpg)

**Comment by ebkr** [comment]
Hi, both already exist in some form!
1. Go to settings, and expand cards. It'll expand cards on both the installed and online tabs.
2. Settings allows you to disable/enable all mods at a time, however if you know you want to bulk disable a couple of mods, disabling a dependency will also disable the dependent mods.

EG: Disabling R2API will disable all mods that need (or indirectly need) R2API.
To see what dependencies and dependents a mod has, in the card on the installed tab, click the View associated button.

In regards to disabling, it's not often that you'd need to bulk disable. If you find yourself disabling multiple mods to play with other people, I'd recommend you export your current profile, and reimport as a new profile. You can then uninstall the mods you aren't using at that time.

**Comment by aerao** [comment]
oh sorry i didn't understand "expand cards". there maybe confusion.
Thx you for the explanations! :)
