### ISSUE TITLE
[BUG] - ADM-ZIP Entry Doesn't Exist

### ISSUE THREAD

**Issue by MadMan247** [ebkr/r2modmanPlus#1556]
Hello. I apologize if this is an ill-formed issue.

I upgraded to r2modman 3.1.53, and I was unable to import a file for a profile that I got. It was able to be installed just moments ago on a thunderstore install on my other pal's computer. The error I got was ADM-ZIP: entry doesn't exist. In this particular case, I was installing a pack for the game Rounds.

It is interesting, since the file could clearly be read; the list of mods would show, and the import button was able to be clicked. It then went from 0% -> 100%, and the next step threw the error (before showing any percentage increment.)

**To Reproduce**
1. Go to import profile from file
2. Select file to import
3. First section completes to 100%, before extracting configs, then error appears

**Expected behavior**
File Imports

**Screenshots**
![image](https://github.com/user-attachments/assets/1a268fdb-4f29-4fbc-90de-0d15b62d7e12)

**Additional context**
Installing 3.1.52 resolved this issue.

Please let me know if you need further information.

Looks like it may be related to this recent commit: https://github.com/ebkr/r2modmanPlus/commit/42f71e2bf274ae418813876246e6d816ecc5d232

**Comment by CloudAlb** [comment]
I confirm this bug happens with me in version 3.1.53, but it doesn't in 3.1.52.
I'm not sure if the OS has an impact on this, but I'm on Windows 11 24H2 (which released fairly recently).
For now I'll be rolling back to 3.1.52.

**Comment by MadMan247** [comment]
I am using windows 10.

**Comment by MadMan247** [comment]
resolved with 3.1.54. Thank you for your dedication!
