### ISSUE TITLE
[FEATURE REQUEST] - GAME: Among Us

### ISSUE THREAD

**Issue by KlutzyBubbles** [ebkr/r2modmanPlus#1561]
**What problem does the feature request solve?**
Thunderstore app has among us, wondering if its possible to get it added to r2modman

**Comment by MadMan247** [comment]
![image](https://github.com/user-attachments/assets/2be32e93-ff36-46fc-a307-6a338fd8aafc)
?
This release (3.1.54) was released 3 days prior to this feature request. Please update if you haven't already.

**Comment by KlutzyBubbles** [comment]
> ![image](https://private-user-images.githubusercontent.com/54383546/389185802-2be32e93-ff36-46fc-a307-6a338fd8aafc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjUxMzgsIm5iZiI6MTczMjQyNDgzOCwicGF0aCI6Ii81NDM4MzU0Ni8zODkxODU4MDItMmJlMzJlOTMtZmYzNi00NmZjLWEzMDctNmEzMzhmZDhhYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDA1MDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjZjOTQxOTM0YzcxMGQxZGUzZjA2ZTM2YWM4NmVkNTFhNGVjOWY0MjM5NTUwNzQxZTI2NDkzNzY2NWM4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jKipbZA-JFBU6ScReguxRPqbXrM2c9W-ifQhChqfc3g) ? This release (3.1.54) was released 3 days prior to this feature request. Please update if you haven't already.

Sorry I downloaded from r2modman.net thinking it was this, feel so stupid now. Sorry for wasting your time.

**Comment by ebkr** [comment]
The .net site is an unofficial site and I do not recommend downloading any releases from there.

The only legitimate places are this repository and Thunderstore, under the Ebkr author
