### ISSUE TITLE
Native Linux Support

### ISSUE THREAD

**Issue by ebkr** [ebkr/r2modmanPlus#177]
For the most part, it's just a case of replacing all `powershell` calls with something that can run under Linux.

Best solution is to create a new class that can divert calls to platform specific applications.

**Potential issues:** 
- I might have to replace the launch method to call the EXE directly.
- Symlinks aren't guaranteed to work. Best solution is to remove the r2modman folder from the Risk of Rain 2 install directory, and point doorstop to use the absolute profile path.
- Anything that opens `explorer` can potentially be an issue. `xdg-open` is a viable replacement, however still lacks support on all distros.

**Comment by SirHamburger** [comment]
At the moment it's possible to start the mod manager with wine.
For that install it and afterwards run 
```winetricks atmlib corefonts gdiplus msxml3 msxml6 vcrun2008 vcrun2010 vcrun2012 fontsmooth-rgb gecko``` 
to install the dependencys (i don't know if everything is necessary). Then you've to fake an windows installation of Steam. For that copy the steam installation as steam.exe (for ubuntu run ```sudo cp /usr/games/steam /usr/games/steam.exe```). Then run the application with wine. 

In the application you've to specify the path to the steam and risk of rain 2 directory and enable installation via syslinks.

It still crashes after launching the game but the mod manager works.
So you just have to start it again if you want to change anything.

**Comment by ebkr** [comment]
There are some performance issues when running under Wine, so it'd be nice to fix at some point.

Either way, thanks for posting the method you've used to get it to work! I'm sure it'll help someone else in the mean time.

**Comment by vickyorlo** [comment]
I managed to get it to run, but it does not actually seem to apply any mods, legacy mode or otherwise.

**Comment by SirHamburger** [comment]
Do the mods work if you copy them normaly?
If not you've to run

1. ```protontricks --gui```
2. Select ROR2
3. Click Ok
4. Click Ok (choose standard wineprefix)
5. Select install Windows-DLL
6. Select winhttp 
7. Click ok
Maybe you have to also add it in the winecfg under libaries.
(my system is in german so i don't know the exact names)

**Comment by vickyorlo** [comment]
Installing winhttp seems to have solved it, thanks!

**Comment by vickyorlo** [comment]
Heads up - 3.0.20 does not crash on launching the game anymore! Other than some weird font rendering, it works more or less perfectly.

**Comment by ebkr** [comment]
Completely unintentional, but that's great news!
The manager no longer calls powershell to start Steam, and instead uses the built-in NodeJS exec command as of 3.0.20.

**Comment by cj360** [comment]
> `winetricks atmlib corefonts gdiplus msxml3 msxml6 vcrun2008 vcrun2010 vcrun2012 fontsmooth-rgb gecko`
> to install the dependencys (i don't know if everything is necessary). Then you've to fake an windows installation of Steam. For that copy the steam installation as steam.exe (for ubuntu run `sudo cp /usr/games/steam /usr/games/steam.exe`). Then run the application with wine.

For some reason vcrun2008 & vcrun2010 just error out when I try to install them via winetricks on my arch install. r2modman would also just launch at as a black window. Disabling libglesv2 in winecfg's libraries tab let it display correctly. 

@SirHamburger did you make a syslink to steam.sh to replace steam.exe?

**Comment by SirHamburger** [comment]
If I recall correctly it's necessary to have a windows installation of steam with the .exe ending. So I just du a normal copy with cp to have a steam.exe link in that folder.

**Comment by Amar1729** [comment]
@cj360 where'd you find `libglesv2` ? Since I'm running this under proton, I opened winecfg via `protontricks 632360 winecfg`, but the Libraries tab doesn't have `libglesv2` in the list of installed libraries.
And same for me with vcrun2008/2010 erroring.

**Comment by cj360** [comment]
I believe I found it under a wine bug report for nexus mod manager. It wasn't listed I just added it and set it as disabled.

**Comment by Amar1729** [comment]
Interesting ... So I didn't do anything in wine, but just deleted both versions of `libGLESv2.dll` I could find (one under the root directory of r2modman, and one under `swiftshader`). That seems to work for me with one odd exception: if i mouse away from the window and then mouse back to it (i.e. it regains focus) r2modman immediately crashes.

**Comment by ebkr** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2228187072

**Comment by AryToNeX** [comment]
> I might have to replace the launch method to call the EXE directly.
@ebkr Node's child process will do just fine!

Also,
> Anything that opens explorer can potentially be an issue. xdg-open is a viable replacement, however still lacks support on all distros.

If you intend to open files externally, Electron has a method for that, but it might be hit and miss, so I would recommend to write a simple function that uses `explorer` or `xdg-open` based on the `process.platform` property.

Finally,
> Symlinks aren't guaranteed to work. Best solution is to remove the r2modman folder from the Risk of Rain 2 install directory, and point doorstop to use the absolute profile path.

Symlinks are guaranteed to work even if we're symlinking on an NTFS drive or cross-symlinking EXT4-NTFS drives. They won't work on file systems which don't support them, but that's a general issue, not a Linux specific one.

**Comment by ebkr** [comment]
> Node's child process will do just fine on both systems!

@AryToNeX Can you explain this a little more? Looking for Steam.exe wouldn't work via Linux right? Not without the user having to install the windows version of Steam at least.

> If you intend to open files externally, Electron has a method for that, but it might be hit and miss, so I would recommend to write a simple function that uses explorer or xdg-open based on the process.platform property.

I was also looking in to using node's file open stuff. It should at least be a fairly minor change, and hopefully better than what we currently have.

> Symlinks are guaranteed to work even if we're symlinking on an NTFS drive or cross-symlinking EXT4-NTFS drives. They won't work on file systems which don't support them, but that's a general issue, not a Linux specific one.

Ah, I wasn't sure how EXT2-4 handle symlinks. Not that it should matter anyway though as symlink creation is handled through fs-extra, a wrapper around node's fs module.

------

On a side note, it'd be nice to be able to handle things like protontricks too, however for now I think I'll have to leave that part up to the end user.

**Comment by AryToNeX** [comment]
> On a side note, it'd be nice to be able to handle things like protontricks too, however for now I think I'll have to leave that part up to the end user.


I fail to see the reason behind this. Protontricks isn't needed as RoR2 starts fine without user modifications.
Yes, it could be useful if mods start to require stuff the base game doesn't, but even then, it really should be the last thing you'd want to implement.

**Comment by StarrKiss** [comment]
Does anyone have any update on this?

**Comment by ebkr** [comment]
In theory the only thing left is to get the game starting through a Linux native version of Steam.

**Comment by AryToNeX** [comment]
>In theory the only thing left is to get the game starting through a Linux native version of Steam.
So, what about making the last step? Is something blocking it?

**Comment by ebkr** [comment]
Yes. I don't have a Linux install.

**Comment by AryToNeX** [comment]
Oh, fair. Well, before making this launcher viable on native Linux, I guess that more cross-compatibilty work is needed, as some code still directly calls PowerShell. It could just be a day or two of work to refactor those calls so that there are Linux equivalents just in case; but I see the point, without a proper Linux install, it will be difficult.

**Comment by ebkr** [comment]
As far as PowerShell is concerned, the only code should be related to locating the path automatically.
I'm not sure if there's an easy way to do it on Linux.
Either way, it's not essential for a Linux port.

The main things that need to be sorted are:
1. Platform detection
2. Steam execution
3. Steam directory manual setting.

**Comment by AryToNeX** [comment]
1. Platform detection
if(process.platform === "win32") and you're done basically.

2. Steam execution
child_process.execFile("steam", arguments) //OR// child_process.exec("steam <arguments>")

3. Steam directory manual setting
I don't know if you're saying this about the executable or about the steamapps/ folder

**Comment by ebkr** [comment]
Steam installation folder.
I mean if you can fork and make these edits, test and make sure it all works correctly, then feel free to make a PR.

**Comment by AryToNeX** [comment]
Oh, the steam installation folder?
Well, if you need it for the steam executable then there's actually no need to even pull it, because the executable is exported in the system's PATH so child_process' exec will call it from there.
If you need it for other stuff, then it is path.resolve(os.homedir(), ".local", "share", "Steam")

**Comment by ebkr** [comment]
I'd expect the user to manually set the executable location.
It's also not guaranteed to be exported if installed manually right?
(http://repo.steampowered.com/steam/archive/precise/steam_latest.tar.gz)

**Comment by StarrKiss** [comment]
If anyone needs testing or help, I have 3 Linux systems running Manjaro, Pop!_OS and Fedora, so that's 3 of the major distros. I can try whatever you want

**Comment by AryToNeX** [comment]
> It's also not guaranteed to be exported if installed manually right?
> (http://repo.steampowered.com/steam/archive/precise/steam_latest.tar.gz)

I mean, nothing is guaranteed to be true on Linux, but that's 99% the case

**Comment by StarrKiss** [comment]
yeah, nobody manually installs shit on Linux like this -everyone installs stuff like Steam through their package manager.

**Comment by AryToNeX** [comment]
The concept of "manual installing" almost always implies putting the executables in a place exported in $PATH anyway; nobody likes running stuff in uncomfortable ways, especially in Linux

**Comment by ebkr** [comment]
Does Steam have an export that isn't $PATH?
Is there some sort of $STEAMPATH export or something?
Searching exclusively for a path ending with /Steam would be pretty stupid.

Allowing users to manually select their directory will stay regardless. It's literally in no one's interest to half implement something.

**Comment by StarrKiss** [comment]
You could just look through the areas exported by the PATH for a file named 'steam' all lower case, and also allow the user to choose manually.

**Comment by AryToNeX** [comment]
> Does Steam have an export that isn't $PATH?
> Is there some sort of $STEAMPATH export or something?
> Searching exclusively for a path ending with /Steam would be pretty stupid.

The Steam user data folder in Linux is always $HOME/.local/share/Steam because that's just how Steam works in Linux and users cannot move it out. Different stuff applies to the games folder, which follows the same ruleset as in Windows.

In Linux, every correctly installed program has its executable exported in $PATH. This means that every other process can launch it simply by calling it. Again, Node's Child Process can do the same and there is no need at all to overengineer stuff to create major points of failure. Linux is not Windows and it works this way.
 
> Allowing users to manually select their directory will stay regardless. It's literally in no one's interest to half implement something.

If you mean "manually select their GAMES directory" aka the steamapps folder, then I could see why. Other folders are handled by the system and Steam itself and they cannot be modified by the user.

But Linux support, of course, is not that simple. There are two (and only two) special cases that need to be handled, but that's a fairly minor issue and it usually consists of just specifying where to find Steam's user data folder in those cases. Plus, those cases can be handled entirely by some code so there's, again, no (real) need to make the user choose their data folder.
But you can still implement it, for the 0.0000000001% of people who screwed up their distros so badly they have really niche special needs about Steam.

Anyway, I would try to replace every explorer.exe call to open folders with electron.shell.openExternal(), just to lay down more cross-plat support that will offload a lot of logic handling to Electron's inner workings.

**Comment by vickyorlo** [comment]
I'm just going to chime in saying that if someone has Steam installed, they will have it in PATH. If they don't, they obviously know what they're doing, they've done it on purpose, they understand that they're doing something weird and uncommon, and they'll figure out that r2modman requires Steam in their PATH and how to fix it. As for the data folders, there is as others have said the main one in ~/.local/share/Steam, but do remember that games can be in multiple places due do being able to create more steamapps libraries. So of course being able to find the ROR2 executable is still required.

**Comment by AryToNeX** [comment]
> do remember that games can be in multiple places due do being able to create more steamapps libraries.

I guess r2modman simply parses Steam's vdf files to find the steamapps folder (I may be wrong)

**Comment by ebkr** [comment]
It does parse the VDF files. (GameDirectoryResolver.ts)

Saying that they obviously know what they're doing if it's not in the path is wrong and is more likely that they don't know what they're doing. That's also one of the main reasons you'd use a mod manager.

Keeping the current functionality it'd probably be best to check for a single entry of `/Steam` in the path. If there's two or more just make it manual.

**Comment by AryToNeX** [comment]
fixed FOR REAL in #378
