### ISSUE TITLE
After searching and downloading a mod, the installed mods view is borked

### ISSUE THREAD

**Issue by hovrawl** [ebkr/r2modmanPlus#196]
After searching and downloading a mod, the installed mods view is borked, can be reset by going to config editor and back

**Comment by ebkr** [comment]
I'm going to need more information.

Are there any visual bugs?
Can you get a screenshot or gif?

**Comment by hovrawl** [comment]
Ah sorry I forgot to explain how it was borked. 
![image](https://user-images.githubusercontent.com/12554055/82312479-761a3180-9a0a-11ea-869e-f5c814862b8e.png)
Even though there is no search filter applied to this, it is only showing that value, I searched for "fast" I believe; the search bar also doesnt function in this state

**Comment by ebkr** [comment]
I'll take a look in to at later today and I'll see what's causing it. Thanks!

**Comment by ebkr** [comment]
Quick update, I can confirm that the search isn't working at all for installed mods. I'll fix that and likely release an update later today.

I can't replicate the single mod appearing though. If you have steps to reproduce, that'd be helpful.

**Comment by hovrawl** [comment]
I'd run a search in the browse mods and it seems whatever that search is was applying to installed mods, I expect that fixing search for installed mods will fix this symptomatically

**Comment by ebkr** [comment]
An update was released last night, it should fix this issue, let me know if you're still getting that problem
