### ISSUE TITLE
Manager does not install update.

### ISSUE THREAD

**Issue by Dwismas** [ebkr/r2modmanPlus#198]
When I close the manager, it prompts UAC to uninstall the old one, but the update does not install at all. The installer for the update can be found in the Roaming folder, which I would manually install from.

**Comment by ebkr** [comment]
AFAIK this is something out of my control, as the installed used is NSIS.
However, it sounds like you've installed the manager as admin, and that's potentially what's failing.
If that's the case, you can uninstall from the control panel, and this time, run the installer as a regular user.
Can you try downloading 3.0.18 without elevated privileges, and letting it update to 3.0.19?

**Comment by ebkr** [comment]
I'll close this issue for now, let me know how it goes!
