### ISSUE TITLE
Check for Risk of Rain executable in set game dir

### ISSUE THREAD

**Issue by McFow1er** [ebkr/r2modmanPlus#199]
Run a check for Risk of Rain's executable in the directory set for the game to tell people that what they're doing wont work for if they incorrectly set their game path.

**Comment by ebkr** [comment]
Should be released in the next update

![image](https://user-images.githubusercontent.com/10426228/83349076-d9209800-a329-11ea-8fd9-2ab1f2d66091.png)
![image](https://user-images.githubusercontent.com/10426228/83349078-daea5b80-a329-11ea-9a35-764f0f4fbb9b.png)
