### ISSUE TITLE
Small UI Bugs 

### ISSUE THREAD

**Issue by skourismanolis** [ebkr/r2modmanPlus#206]
Hello! I've recently discovered this mod manager and I have notice some small, nit-picky issues like:
- buttons have selectable text that turns blue when you click them
- the "Go back" arrow in the config editor is not clickable while the text is
- settings' buttons don't have hover and active states and it's not completely obvious that they are buttons

These are just some of the small issues I found of the top of my head, would you be open to me submitting a PR fixing them? If not, I can write a more detailed list. If yes, should I submit a big PR with all the small changes or lots of small ones?

Thanks again on the amazing mod manager! Cheers!

**Comment by ebkr** [comment]
Hi, thanks for leaving some feedback!

In regards to the buttons, that absolutely sounds like something I should look in to. 
Would it be possible to also have a gif of the issue?

The "go back" arrow is also a problem, although that should be a fairly straightforward fix.

In terms of the settings page, do you have any suggestions on how to make it clearer? Buttons on their own don't have the same kind of effect, and look slightly odd.

For any PRs, individual issues are preferred, as the issues themselves aren't related.
