### ISSUE TITLE
UI Text is selectable

### ISSUE THREAD

**Issue by skourismanolis** [ebkr/r2modmanPlus#207]
Various UI elements like buttons and section titles can be selected like normal text.
[Like this](https://gyazo.com/0b7d614e30b8f21f59f5a903875de1ba.gif)

This can be avoided by using the [user-select property](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) on all elements and then having a css class that overrides this for some fields that it makes sense.

Personally, I think the only selectable fields should be: 
- Mod names and descriptions
- Code blocks such as in the default Launch parameters

`user-select` doesn't affect input fields, so that won't be an issue, and the config values keys' are input fields so they are also selectable

If you think there should be more selectable fields feel free to chime in.

I'll be preparing a PR for this.

**Comment by ebkr** [comment]
It'd also be best to allow modals to have their text selectable too.
