### ISSUE TITLE
[FEATURE REQUEST] - Check For Mod Updates

### ISSUE THREAD

**Issue by vizthex123** [ebkr/r2modmanPlus#240]
I can't find this anywhere, and would like for there to be a way to check for mod updates.

Auto-downloading new ones would be nice, but at least being able to click a button and check would be nice

**Comment by ebkr** [comment]
Hi,
You can actually test this out for yourself by downloading an older version of a mod. There'll be a cloud icon on the card, and once expanded you'll be able to see an "Update" button on the right within the installed section.
Auto-downloading is a no-go though I'm afraid, as a mod could potentially be broken or malicious.
I'll keep this open for a bit so you can confirm the ability to update.

**Comment by ebkr** [comment]
I have just confirmed that this is definitely still working on 3.0.24.

![image](https://user-images.githubusercontent.com/10426228/89014385-5e660000-d30d-11ea-8e56-4b2900041775.png)

**Comment by vizthex123** [comment]
Ah ok, you have to do it per-mod then. Well, it does tell you at least so that's fine. Hope we can auto-update in the future.
