### ISSUE TITLE
[FEATURE REQUEST] - Config and mod sorting and filtering, refresh

### ISSUE THREAD

**Issue by fwenny** [ebkr/r2modmanPlus#251]
**What problem does the feature request solve?**
Refreshing the Online tab instead of relaunching the program
Filter Installed mods by disabled and enabled 
Sort config by latest added mods so mods can easily be configured right after install

Thank you.

**Comment by ebkr** [comment]
Hi, thanks for the suggestions!

The Online mod tab refreshing has already been added and will be out in the next release. It will be possible to do via the settings screen.

Filtering installed mods is a nice idea, although how do you expect it to work? Just something to show/hide any disabled mod entries or move disabled mods to the bottom?

Sorting configs is also a good idea.

**Comment by fwenny** [comment]
Yeah I find it a bit annoying to install a mod, launch the game, then going to the folder and sorting by last created to figure out whats the name of the config to be edited, so stream lining it will be great. ^^

Regarding filter, why not use something similar to the Online tab? Add a combo box to the right with a label "Filter" and options All, Enabled, Disabled.

and regarding refresh, adding it to Settings is completely fine, though adding a small button between the search text box and "Sort" label could also work.

**Comment by ebkr** [comment]
One thing to note about the config filter is that the configs are currently searchable. It's usually enough to search for a mod's name. It doesn't mean there shouldn't be filtering, but there also shouldn't necessarily be a need to go in to the folder.

I think that mod list filter will work, sounds like a good idea.

Not 100% on the button on the search bar, it's already fairly busy as-is, and is currently strictly only for filtering the list. I also don't think it's necessarily needed as you won't be filtering often (mod releases aren't too frequent).

**Comment by fwenny** [comment]
Yeah I know about the searching, just often I forgot the name of the author / mod, or theres some weird naming convention. Mostly my fault though.

And yeah fair point, button is simply to reduce the need to go to the Settings menu for a refresh but it is true releases arent frequent. =)

**Comment by ebkr** [comment]
# Screenshots
## Installed tab
### Overview
![image](https://user-images.githubusercontent.com/10426228/90837314-97f8bc80-e349-11ea-8648-49a320012ef1.png)
---
### Sort options
![image](https://user-images.githubusercontent.com/10426228/90837331-a515ab80-e349-11ea-99c2-5687ac03afc7.png)
---
### Ordering
![image](https://user-images.githubusercontent.com/10426228/90837344-aa72f600-e349-11ea-8866-0bc18c74024b.png)
---
### Disabled mod filters
![image](https://user-images.githubusercontent.com/10426228/90837352-afd04080-e349-11ea-86c8-8a77e09be2f7.png)
---
## Config editor
### Overview
![image](https://user-images.githubusercontent.com/10426228/90837438-f160eb80-e349-11ea-8944-3176aebeb915.png)
---
### Sort options (ordering next to field is identical to installed tab)
![image](https://user-images.githubusercontent.com/10426228/90837453-ffaf0780-e349-11ea-9e13-c453e4f36562.png)

**Comment by fwenny** [comment]
looks great, thank you!
