### ISSUE TITLE
[FEATURE REQUEST] - Mod categories

### ISSUE THREAD

**Issue by arisinwonderland** [ebkr/r2modmanPlus#283]
Being able to filter mods according to a few preset categories would make searching for specific kinds of mods much easier. At present, while searching for a specific feature isn't hard, searching for some type of mod without any particular one in mind is much moreso. As an example, looking for all mods that add new characters can only be done by randomly inputting keywords such as "character", "new", etc. Examples of other potential mod categories would include skin mods, overarching gameplay changes, UI tweaks, and whatever else the dev team sees fit. Allowing mods to be placed in multiple categories or none of them could potentially be a useful feature as well.

**Comment by ebkr** [comment]
This is something planned, however category information is not available on the Thunderstore API, so I can't actually access that information.

It will eventually come to the API, could be a few weeks though.
