### ISSUE TITLE
[FEATURE REQUEST] - Improve mod list clarity

### ISSUE THREAD

**Issue by ChiriCuddles** [ebkr/r2modmanPlus#296]
**What problem does the feature request solve?**
There were some issues with the clarity of the mod list.

**Example mock-up**
Author bylines differentiated from mod names:
![image](https://user-images.githubusercontent.com/6081834/92620783-664e9200-f306-11ea-8011-46a6669aab5a.png)

Disabled mods are more transparent than enabled mods:
![image](https://user-images.githubusercontent.com/6081834/92622008-e6292c00-f307-11ea-85bd-34d3e27b7db2.png)

Mod footer buttons don't have borders anymore that make it hard to tell which card they belong to:
![image](https://user-images.githubusercontent.com/6081834/92621006-a877d380-f306-11ea-871a-cc36f018ef33.png)

Mod footer buttons have a similar appearance to navigation buttons on the left side of the application:
![image](https://user-images.githubusercontent.com/6081834/92621081-bb8aa380-f306-11ea-9fde-9c41d29fea9d.png)

The version link has the same click region & appearance as the other footer buttons:
![image](https://user-images.githubusercontent.com/6081834/92621184-d8bf7200-f306-11ea-92d6-2fedcb3f2a23.png)

**Additional information**
This "mockup" is actually implemented on my end, but I wasn't sure if I should jump straight into making pull requests for all of it, and how much I should break it up for said PRs, so I figured I'd make an issue first. 

Lemme know your thoughts! (I'm in the Discord as well btw, my username is Chirichirichiri. If you wanna discuss things via DM)

**Comment by ebkr** [comment]
Hi, thanks for raising it!
It's best to keep them appearing as clickable (rather than only on hover), so having them blend in isn't ideal.
Possibly adding vertical borders might be better?

How does it appear for light theme?

**Comment by Yuudaari** [comment]
Borders don't really read to me as "clickable", they read to me as "table". (Especially given that the mod link previously wasn't clickable for the full size of the button.) Generally I find that "clickable" can be inferred through different colours, which is a thing in both themes (though it's more clear in the light theme given that the text is blue rather than grey.)

Sorry about not uploading light theme, forgot:
![image](https://user-images.githubusercontent.com/6081834/92623394-8469c180-f309-11ea-9132-1f6ad21e9df1.png)

**Comment by ebkr** [comment]
Yeah, you're right that they don't appear clickable in the dark theme. The blue definitely helps with that. I think the borders are fine to leave.

I'm actually pretty impressed with how that's turned out. Feel free to submit a PR and I'll take a look.

Thanks!
