### ISSUE TITLE
r2modman can't find steam directory even though i set it up

### ISSUE THREAD

**Issue by kurtis717** [ebkr/r2modmanPlus#299]
r2modman won't boot up and keeps telling me to find the steam directory even though i set it up in settings
![unknown](https://user-images.githubusercontent.com/71281412/93114144-3a296d00-f688-11ea-9a96-00c56b5baf76.png)

**Comment by ebkr** [comment]
Well that doesn't look like a Steam install folder.

The Steam.exe is inside of it right?

ENOENT means that the file doesn't exists, and it sounds like D:/kurtis/WindowsTMP isn't a valid folder.

**Comment by kurtis717** [comment]
ok here you go
![unknown (1)](https://user-images.githubusercontent.com/71281412/93118053-ad81ad80-f68d-11ea-88df-0bb3ea1f0795.png)

**Comment by ebkr** [comment]
> r2modman won't boot up and keeps telling me to find the steam directory even though i set it up in settings

Well that's not your Steam folder.
Set it up properly. The folder will contain a file called Steam.exe.

![image](https://user-images.githubusercontent.com/10426228/93118365-1da52900-f6b8-11ea-8fd3-2a6f66f512ad.png)

**Comment by kurtis717** [comment]
but that's not where i told it to check for the steam directory here is where i told it to check
![unknown (2)](https://user-images.githubusercontent.com/71281412/93118700-aad38800-f68e-11ea-8b51-1506ed06b31b.png)

**Comment by ebkr** [comment]
Ah okay, can you try running the manager as admin?

**Comment by kurtis717** [comment]
it didn't work

**Comment by ebkr** [comment]
Can you screenshot the contents of the mods.yml folder?
(Settings -> Browse data folder -> config folder)

**Comment by kurtis717** [comment]
it this it?
![unknown (3)](https://user-images.githubusercontent.com/71281412/93120301-246c7580-f691-11ea-8dee-17c8638212c4.png)

**Comment by ebkr** [comment]
The contents of the mods.yml file.

**Comment by kurtis717** [comment]
ok sorry i got it this time
![unknown (4)](https://user-images.githubusercontent.com/71281412/93122475-88dd0400-f694-11ea-96e6-7ff74c614688.png)

**Comment by ebkr** [comment]
Something is going very wrong with your install.
The file should look similar to this:

![image](https://user-images.githubusercontent.com/10426228/93122635-c060a600-f6be-11ea-8aaf-87211f8ebabe.png)

**Comment by ebkr** [comment]
Can you give this a go?
https://github.com/ebkr/r2modmanPlus/wiki/Clearing-the-config

For step 8, relaunch as admin.

**Comment by kurtis717** [comment]
still did not work

**Comment by ebkr** [comment]
Then I have no idea. It's definitely something to do with your system.

Did you download it from Thunderstore?
Has it ever worked?

**Comment by kurtis717** [comment]
i did download it off of thunderstore and it has never worked

**Comment by ebkr** [comment]
Delete the r2modmanPlus-local folder, and then try this:
https://github.com/ebkr/r2modmanPlus/releases/download/v3.0.28/r2modman-3.0.28.exe

If this still doesn't work, I'm not sure what to do.
This isn't something I can replicate.

**Comment by kurtis717** [comment]
still did not work damn

**Comment by ebkr** [comment]
At this point all I can really recommend is to try an alternative mod manager. Maybe that'll work fine?

**Comment by kurtis717** [comment]
ok i'll try thanks for the help
