### ISSUE TITLE
[BUG] - Mod Manager Can't Connect

### ISSUE THREAD

**Issue by Tactical-Shrubbery** [ebkr/r2modmanPlus#317]
The manager fails to connect to Thunderstore.io every time I run it.

To reproduce the bug all I have to do is launch the program.

![image](https://user-images.githubusercontent.com/39163107/94583885-f6b82c80-024b-11eb-9419-258ca589739e.png)

**Comment by ebkr** [comment]
Hi, this is not a mod manager issue. The current solution is to try again in around 5-10 minutes.

The Thunderstore API goes down somewhat frequently, and has a fix expected to be out later this week.

As this is related to Thunderstore and not the manager, there's nothing neither me nor you can do other than wait.
