### ISSUE TITLE
[BUG] - Can only start in offline mod despite internet connection ok, and thunderstore.io up

### ISSUE THREAD

**Issue by maeln** [ebkr/r2modmanPlus#319]
**Describe the bug**
The r2modman client refuse to start in online mod, always output: 
"Failed to get mods from Thunderstore".

The computer is connected to the internet, thunderstore.io is up, r2modman.exe is allowed in the firewall.
Running in admin mode doesn't solve the issue.

**To Reproduce**
1. Install r2modman
2. Start r2modman
3. The first screen will show a loading bar, then quickly display "Failed to get mods from Thunderstore"
4. Clicking on the "try to reconnect" while repeat the same behavior

**Expected behavior**
Start r2modman and properly connect to the store.

**Screenshots**
https://maeln.com/pub/bug.png

**Console output**
```
PS D:\various\ror2mod> .\r2modman.exe
PS D:\various\ror2mod>
starting server on  /tmp/app.r2mm
starting TLS server false
starting server as Unix || Windows Socket
Checking for update
Update for version 3.0.31 is not available (latest version: 3.0.31, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by ebkr** [comment]
See #317
