### ISSUE TITLE
[BUG] - r2modman uninstalled itself when updating

### ISSUE THREAD

**Issue by BLucky-gh** [ebkr/r2modmanPlus#334]
**Describe the bug**
A clear and concise description of what the bug is:

when I closed r2modman it wasa updating but after the update finished the installation directory was empty.

**To Reproduce**
1. wait for new update to be available
2. open r2modman
3. play a bit of ror2
4. close modman
5. idk, it was at this point when I noticed the shortcut lost it's icon

**Expected behavior**
r2modman updates properly

**Comment by ebkr** [comment]
See #269
