### ISSUE TITLE
[FEATURE REQUEST] - Save Filter categories between launches

### ISSUE THREAD

**Issue by fwenny** [ebkr/r2modmanPlus#341]
**What problem does the feature request solve?**
Not needing to set Filters everytime.

**Additional information (optional)**
Similar to how Sort options are saved between launches, it would be great if Filter categories would be saved as well (NSFW checkbox, categories picked, and which one of the 3 radio choices is selected).

**Comment by ebkr** [comment]
I'm not 100% on this idea.

Someone may forget that they've filtered out specific mods and might not realised that they don't have the complete mod list.

There are ways around this, but none that I can think of that don't intrude on screen space.

**Comment by fwenny** [comment]
in that case put a checkbox in the filter categories window to "save preferences". 
it is up to you, but I dont understand why wouldnt you add this as an option. more choices is always better, and user error shouldnt be the reason to not implement something.

**Comment by ebkr** [comment]
Preventing user error is a perfectly good reason not to implement something. The more things that can go wrong mean that I'll receive more issue reports.

Adding options to a screen is also iffy because you run the risk of making screens overly complicated. Granted in this case it isn't necessarily bad, but it's something I'll need to think about prior to implementing.

**Comment by fwenny** [comment]
alrighty, ill leave it up to you to figure out how you want to approach this, if at all.
i just get tired of having the list spammed with modpacks and skins, things i have zero interest in, and having to redo the filtering over and over. 
i get annoyed too easily by repetition, and almost always try an automate things if i can. so maybe its more my problem. -shrug-

**Comment by ebkr** [comment]
Looks like I solved this a long time ago and just forgot to close the issue 👀 
Closing now, if there's any issues let me know!
