### ISSUE TITLE
[FEATURE REQUEST] - Move/duplicate "update all mods" button to the main page

### ISSUE THREAD

**Issue by iskawhiskers** [ebkr/r2modmanPlus#354]
**What problem does the feature request solve?**
_The current button to update all outdated mods is currently buried in the settings page, and isn't obvious to new/inexperienced modders.  Moving or duplicating the button to the main menu would be an easy, accessible way to update your modpack, while still offering the option to update mods individually._

**Example mock-up (optional)**
![Mockup, using the button from the Settings page](https://i.imgur.com/T1qZkuy.png)

**Additional information (optional)**
_The button to update all the mods could also be inserted at the top of the page, with the search and sort functions, or inline with the mods at the top of the modlist._

**Comment by ebkr** [comment]
Hi,

Short answer to the suggested way is no.

Here's a more detailed reason:
That left panel is strictly for navigation purposes. You could argue that the launching options aren't navigation, however they also aren't manager actions themselves. They are closer to something navigation related as it changes the context from manager to game.

Moving the update all option to the installed section would work, however in the current state it has no place sitting amongst filter options. This also relates as there are currently no bulk-actions that can be performed on this screen.
A new line of actions could be added, but then there'd only be a single action, and it would take up valuable screen space.

The decision given is focused at two main points. One for modpacks and one for inexperienced modders. The primary focus of the manager is for inexperienced modders, and modpacks creators are of less concern. If a user uses a modpack, updating the modpack itself would update all dependencies. For the modpack creator, it's inconvenient, but people can help on how to find the action to update all.

Update all is not an action that will always be used, and is in fact less recommended compared to singular updates for security reasons. 

If you have any alternative suggestions or questions, I'd be happy to hear them.
