### ISSUE TITLE
[FEATURE REQUEST] - Launch game without connecting to Thunderstore

### ISSUE THREAD

**Issue by LouieK22** [ebkr/r2modmanPlus#373]
**What problem does the feature request solve?**
When Thunderstore is down, modded RoR2 cannot be launched, even if I don't want to install or update any mods.

**Example mock-up (optional)**
The loading screen could have an "offline" option or the client could connect to Thunderstore in the background after launching.

**Comment by ebkr** [comment]
It already does. Eventually your request will timeout.
It performs 5 attempts to connect to Thunderstore, otherwise a "Continue offline" button will appear.
You can test this yourself by disconnecting from the internet.
