### ISSUE TITLE
Antivirus detected Mailware

### ISSUE THREAD

**Issue by krismoellegaard** [ebkr/r2modmanPlus#403]
so fist off let me say this my system is running in Danish so the alert is in danish i done my best to translate it to english

> Suspicious file: r2modman-Setup-3.1.5.exe
> 
> Malware:  Drop.Win32.LocalAppSelfCopy.29413
> Path: C:\Users\********\Downloads\ebkr-r2modman-3.1.5\r2modman-Setup-3.1.5.exe\r2modman-Setup-3.1.5.exe
> 
> 
> Details
> •    [23840] C:\Users\********\Downloads\ebkr-r2modman-3.1.5\r2modman-Setup-3.1.5.exe
> 
> Files changed
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\WinShell.dll
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\nsis7z.dll
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\app-64.7z
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\nsDialogs.dll
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\modern-wizard.bmp
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\StdUtils.dll
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\UAC.dll
> •    C:\Users\********\AppData\Local\Temp\nss6E91.tmp\System.dll
> •    C:\Users\********\AppData\Local\Temp\nsx6E13.tmp
> 

i am assuming that it is false positive

the antivirus in question is Bullguard

if you need any thing more pleas let me know

**Comment by ebkr** [comment]
It's a false positive.
`LocalAppSelfCopy` doesn't really sound like it's detected as anything nasty either though.

Not too much I can do about it unfortunately.

You should be able to allow it through BullGuard (it might quarantine the file?)

**Comment by krismoellegaard** [comment]
i dit report it to bullguard but i thaurt i make a bug report in case any one els ran in to the problem

i know bullguard generate a compleat log file and i will atemt to see if i can find it the one above is joust from the intial popup it lack a lot of details
