### ISSUE TITLE
[BUG] - modman and thunderstore return different results for the same keyword

### ISSUE THREAD

**Issue by Therzok** [ebkr/r2modmanPlus#422]
**Describe the bug**
modman does not search into the plugin's description when looking up plugins, it looks only in the title. This is different from thunderstore's behaviour.

**To Reproduce**
Steps to reproduce the behavior, try on both Dyson Sphere Program modman and thunderstore:
1. Go to Online
2. Write 'sort' in search
3. Observe `OrderSaves` is not in modman, but appears in thunderstore

**Expected behavior**
Both modman and thunderstore should have the same results. This is problematic because tags do not exist.

**Comment by ebkr** [comment]
r2modman is not thunderstore.
The search is handled internally.

**Comment by Therzok** [comment]
I completely understand and that's not a big deal. I was just trying to find out if this is intended or not, especially given tags not existing so there's no way to add more descriptive titles to plugins, unless you put a really long description as the name.

**Comment by MythicManiac** [comment]
even though it's currently unrelated, our next API will have a search endpoint which would likely be relied on by r2modman and other similar tools for searching. After this has been implemented, it should be consistent across tools.
