### ISSUE TITLE
[BUG] - BepInEx for Valheim is not installed correctly on Linux

### ISSUE THREAD

**Issue by Khrona98** [ebkr/r2modmanPlus#423]
**Describe the bug**
It looks like the folder "BepInEx" where plugins/mods reside is not present at the game's directory on Steam when installed on Linux with m2modman. Creating a symlink to it there solved the problem and allowed mods to be loaded.

**To Reproduce**
1. Install "BepInEx" for Valheim with r2modman on Linux;
2. Install any other mod/plugin like "BetterUI by Masa", for example;
3. Launch the game and enter a world;
4. The mod isn't loaded/doesn't work.

**Expected behavior**
The folder "BepInEx" should be copied or symlinked to the game's directory just like the other files from the mod/framework that are correctly there.

**Screenshots**
1. _r2modman Default profile folder:_
![Screenshot from 2021-03-01 18:21:37](https://user-images.githubusercontent.com/9277125/109561142-8859ed80-7abb-11eb-951b-dd7df1710891.png)
 
2. _Steam game directory (with symlinked "BepInEx" folder):_
![Screenshot from 2021-03-01 18:21:47](https://user-images.githubusercontent.com/9277125/109561220-a0ca0800-7abb-11eb-84a0-38465c5980dd.png)

**Additional context**
For reference I'm using r2modman 3.1.7 (latest at the time of writing) on Solus.

**Comment by ebkr** [comment]
No, this is expected behaviour.

r2modman launches BepInEx using the `--doorstop-target` parameter.
Native Linux support is not yet supported, however should be out relatively soon. 

In the meantime you can either use your symlink, or switch to the Proton version.
