### ISSUE TITLE
[BUG] All buttons stop working upon using dropdown menus

### ISSUE THREAD

**Issue by xdreaper15** [ebkr/r2modmanPlus#432]
Once you are in your profile, go to Online. As soon as you click the Sort dropdown, all buttons (except start modded/vanilla) stop functioning.

I have tried un/re-installing the application, but to no avail.

Video of the issue: https://youtu.be/uv95bqXG0Hs

**Comment by ebkr** [comment]
Hi, thanks for raising this!
I’ll take a look into it when I next can

**Comment by ebkr** [comment]
So investigating this a little and it seems likely due to a duplicate package appearing on TS.
I should have a fix out soon.
