### ISSUE TITLE
[BUG] - "Mod does not exist" (but it does)

### ISSUE THREAD

**Issue by GregariousJB** [ebkr/r2modmanPlus#434]
r2modman v3.1.9
Chrome v88

![image](https://i.imgur.com/Q3yk8Cu.png)

1. Click "install with mod manager" button on mod page
2. See above screenshot

- r2modman rebooted several times
- system rebooted
- "Clean mod cache" used
- "Refresh online mod list" used
- Same problem using Firefox v86

**Comment by SavageCore** [comment]
Same issue and [this](https://valheim.thunderstore.io/package/bdew/QuickConnect/) new mod just uploaded will not show up so cannot install by searching in the online section as I usually do.

**Comment by ebkr** [comment]
Thanks for raising this.
I’ve been aware of it and it’s due to the Thunderstore sub domains (should work when using RoR2)

I’ll look for a fix but in the mean time the online list is the pretty easy workaround.

**Comment by strzelecki-maciek** [comment]
Just FYI, 2 years later this bug still happens ;-)

**Comment by ebkr** [comment]
> Just FYI, 2 years later this bug still happens ;-)

Not really, they’re different things.

The original bug was an issue with actual uploads that the manager detected as the protocol used was being handled incorrectly and so it happened for every single mod.

Your equivalent was that the manager hadn’t refreshed the mod list. If you’d have waited 5-10 minutes then it would have refreshed.

**Comment by trgedz222** [comment]
> > Just FYI, 2 years later this bug still happens ;-)
> 
> Not really, they’re different things.
> 
> The original bug was an issue with uploads that the manager recognised however the protocol used was being handled incorrectly and so it happened for every single mod.
> 
> Your equivalent was that the manager hadn’t refreshed the mod list. If you’d have waited 5-10 minutes then it would have refreshed.

So when uploading a modpack for a game, this just takes a few minutes for it to get past this error? just making sure as it has already been 15 mins.

**Comment by MichelleAthens** [comment]
Im having the same issue on my end. I have tried uploading 3 different modpacks on different days and no luck

**Comment by MichelleAthens** [comment]
It does not appear at all in the modlist

**Comment by MythicManiac** [comment]
FYI a lot of lethal community modpack uploads are being actively rejected from the site due to re-uploading DLL files from other mods or distribution of copyrighted content.

Make sure the packages you're uploading are not redistributing DLLs (use dependencies for those in the manifest.json) and they shouldn't be getting rejected.

**Comment by Kakaka999** [comment]
same problem here, i uploaded a tvpack using their pack creator. I can locate it on thunderstore web, but the modmanager does not show the mod on the list

**Comment by jawmack23** [comment]
Yeah Iam still getting this too

**Comment by ITCMD** [comment]
Also having this issue with a tv pack mod. No reused dlls. No reused description. Couple of reused videos as well as new ones. Been 15 minutes and still "Mod does not exist" https://thunderstore.io/c/lethal-company/p/W1BTR/W1BTR_TV/

How can I tell if the mod is being "rejected?" if it's still on the website?

**Comment by MythicManiac** [comment]
> How can I tell if the mod is being "rejected?" if it's still on the website?

There will be a message on the mod page on the website if it's rejected

**Comment by TheRealAlexV** [comment]
Took about 45 minutes for r2modman to finally see the upload on thunderstore. There seems to be a large delay in thunderstore updating their API.

**Comment by Sc0r** [comment]
Is this getting even slower?
Updated a modpack. Almost instant on the website, about an hour on the client until it showed the new version. 
Is there any way to speed this up? clearing mod cache didn't help.

**Comment by ebkr** [comment]
This is Thunderstore API related. The manager has no control over this and is the same regardless of the manager you use.

**Comment by Annabxlla** [comment]
I feel this issue is just getting slower and slower. It has been 2 hours after I uploaded my mod to Thunderstore and R2 shows it as not  found.

**Comment by Jack1424** [comment]
I'm also having this problem. I uploaded a modpack to Thunderstore over two hours ago, and R2 still says that it doesn't exist. I've manually refreshed the online mod list and restarted R2 multiple times.

This does not appear to be an issue with Thunderstore API, however.

If I make a GET request to `https://thunderstore.io/api/v1/package-metrics/[team]/[mod name]/` with my modpack's team and name, I get a 200 response with the accurate downloads, rating score, and latest version. I have also tested making requests to `https://thunderstore.io/api/cyberstorm/package/[team]/[mod name]/latest/readme/` and 

I'm not quite sure how R2 makes its API requests, but wouldn't this indicate that the Thunderstore API isn't the issue?

**Comment by TheRealSomeRando** [comment]
Having this issue today still, uploaded a TV pack mod to thunderstore 2+ hours ago and has still not shown up on the mod manager. Was not rejected. I keep refreshing the manager, still not there. I didn't reuse any files except for some video files for the tv.

**Comment by matejzm2019** [comment]
Still happening, about 30 minutes ago i uploaded it and the mod manager still cannot seem to find it.
