### ISSUE TITLE
Problem - Dyson sphere program directory file doesn't show up in r2modman file explorer

### ISSUE THREAD

**Issue by BombSquad000** [ebkr/r2modmanPlus#437]
I am unable to select or view the directory for DSP in r2modman but if I can find it when I use windows file explorer. i have tried reinstalling the game and modman but it still doesn't show up.
![Capture1](https://user-images.githubusercontent.com/80447166/110748814-1ee18980-81f5-11eb-911c-f75fb10d85ad.PNG)

**Comment by ebkr** [comment]
The folder you’re in is what you select. It’s asking for you to select the directory, not the exe
