### ISSUE TITLE
[BUG] - Can't load Native dll 

### ISSUE THREAD

**Issue by bluedoom** [ebkr/r2modmanPlus#438]
Can't load NativeDll by [DynDllImort].

Install https://dsp.thunderstore.io/package/bluedoom/CompressSave/ by r2modman  (with BepinEx) => didn't work and raise exception
Unzip file to game folder (with BepinEx) => work

Source code:
https://github.com/bluedoom/DSP_Mod/blob/27e7af1bc66d16d598a3262ace99c857d1b03afe/LZ4Wrap/LZ4Wrap.cs#L22

The error:
 https://github.com/bluedoom/DSP_Mod/issues/1

**Comment by ebkr** [comment]
How have you packaged your zip and how would you expect it to be installed?

**Comment by bluedoom** [comment]
> How have you packaged your zip and how would you expect it to be installed?
> 
> Note that nothing will be placed in the root of the plugins folder

[bluedoom-CompressSave-0.1.2.zip](https://github.com/ebkr/r2modmanPlus/files/6122608/bluedoom-CompressSave-0.1.2.zip)
![image](https://user-images.githubusercontent.com/29087010/110780803-11cda480-82a0-11eb-9b1d-f28fc81cd03b.png)
LZ4.dll is a c lib. it seems not to be loaded.

**Comment by bluedoom** [comment]
I figure out by replacing assembly location dynamically.
`           string root = Path.GetDirectoryName(System.Reflection.Assembly.GetAssembly(typeof(LZ4API)).Location);`

            var map = new Dictionary<string, List<DynDllMapping>>
            {
                { "lz4.dll" ,new List<DynDllMapping>{
                    "LZ4.dll",
                    "X64/LZ4.dll",
                    Path.Combine(root,"X64/LZ4.dll"),
                    Path.Combine(root,"LZ4.dll")
                } },
            };`
