### ISSUE TITLE
[BUG] - Drag 'n' Drop install does not maintain mod file structure

### ISSUE THREAD

**Issue by NeonCarbide** [ebkr/r2modmanPlus#439]
**Description**
If a mod whos file structure contains, say, a folder of assets to use is installed by drag and drop, the folder is unpacked and its contents are copied over but the folder is not copied over

**Expected behavior**
Simply put, if there's a folder in a mod with stuff in it, it should be copied over as is rather than unpacking the contents

**Screenshots**
Mod structure
![image](https://i.imgur.com/fVe46vO.png)

Mod folder in profile after Drag 'n' Drop install
![image](https://i.imgur.com/jQhPZtG.png)

**Additional context**
To be fair, I'm not sure how much use a bugfix for this would have considering the only use I've found so far is bundling the [Custom Textures](https://www.nexusmods.com/valheim/mods/48) mod with textures, but it would be a nice convenience thing for people who would like to make texture packs for private use

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/wiki/Structuring-your-Thunderstore-package

I’ll leave this open if you have any questions

**Comment by NeonCarbide** [comment]
Fair enough, I should've checked the wiki :/

Thanks for the pointer o7
