### ISSUE TITLE
[BUG] - "Mod does not exist" (but it does #2) 

### ISSUE THREAD

**Issue by GregariousJB** [ebkr/r2modmanPlus#446]
Repeat of issue #434. Not sure why it was closed. This bug is extremely easy to reproduce/test since it happens 100% of the time.

![image](https://i.imgur.com/pFGdhl9.png)

Clicking "Install with mod manager" on the website results in the following error, even though it exists - it's visible in the mod manager in the screenshot above.

**Comment by ebkr** [comment]
It was closed because it’s been fixed. The fix is however not yet released, however will most likely come out within the next few days.

You should be able to find a linked pull request on the other issue

**Comment by GregariousJB** [comment]
Oh crap. Sorry. And thank you.
