### ISSUE TITLE
 Any way to filter out modpacks when searching?

### ISSUE THREAD

**Issue by acwartz** [ebkr/r2modmanPlus#452]
![image](https://user-images.githubusercontent.com/55237717/112354377-ae9b3380-8cdd-11eb-9809-719e80b44d30.png)

**Comment by ebkr** [comment]
Whilst this was instantly closed, a reason/solution would probably be good for anyone else looking:

![image](https://user-images.githubusercontent.com/10426228/112363966-f7e38700-8ccd-11eb-9090-39162cc7bdd3.png)

![image](https://user-images.githubusercontent.com/10426228/112364042-09c52a00-8cce-11eb-9072-cd19417cdde5.png)
