### ISSUE TITLE
[FEATURE REQUEST] - A I18N support will be charming, need help?

### ISSUE THREAD

**Issue by cjzcpsyx** [ebkr/r2modmanPlus#454]
**What problem does the feature request solve?**
I advertise r2modman a lot in my videos, but a great part of my channel viewer cant read english
Probably adding an i18n support would be great

**Example mock-up (optional)**
_If you are able to provide a mock-up, please do so here_

**Additional information (optional)**
I can help do the translation, but need some guide on where are all the vue page/components have fixed text that need to add to i18n mapping

**Comment by ebkr** [comment]
Hey, it’s quite a hefty change however most text is done via the Vue files under /src/pages.

There’s also the navbar which, off the top of my head, is in something like /src/components/navigation.

I have a translation issue in my backlog to do, it’s just that other features and games keep taking priority.

**Comment by ebkr** [comment]
Going to merge this with #273 as this is a duplicate.
