### ISSUE TITLE
[FEATURE REQUEST] - Windows Shortcuts to start a specific profile

### ISSUE THREAD

**Issue by frenchiveruti** [ebkr/r2modmanPlus#456]
**What problem does the feature request solve?**
Save a few clicks

**Example mock-up (optional)**
Simply add the posibility to specify a profile in a shortcut, and start r2modman managed game right away. 
Say, 
r2modman.exe  --game "Valheim" --profile "Default"  
That would start Valheim under Default profile.

**Additional information (optional)**
Maybe check for updates of the mods automagically?

**Comment by ebkr** [comment]
Hey, this is a duplicate of #448

**Comment by frenchiveruti** [comment]
Yes, I saw it today and was like "oh shoot"
