### ISSUE TITLE
Won't connect to thunderstore

### ISSUE THREAD

**Issue by Hawkeye112** [ebkr/r2modmanPlus#470]
My modman will not connect to the ror2 thunderstore at all, I've tried both reinstalling modman and restating my pc, when I press "try to reconnect" It just instantly jumps back to "You may be offline" But my internet is not offline and is working fine, has anyone experienced this?
![offline](https://user-images.githubusercontent.com/13158901/113770859-acc76c00-96f0-11eb-86e5-e80be4bc5f74.png)

**Comment by CloseProximity4** [comment]
Same Issue Here

**Comment by ebkr** [comment]
![2B89919E-7A5A-4D76-BFF1-39CC27FA4702](https://user-images.githubusercontent.com/10426228/113772050-1315b400-971c-11eb-9387-59fc15ba3700.png)
