### ISSUE TITLE
[BUG] - "Error Mod does not exist" when installing "new" mod

### ISSUE THREAD

**Issue by Vl4dimyr** [ebkr/r2modmanPlus#472]
**The bug**
When trying to install a mod that was just uploaded to thunderstore.io, using the "Install with Mod Manager" button, r2modman shows an error message:

```
Error
Mod does not exist

Unable to resolve <MOD_NAME> to a suitable Thunderstore mod

Suggestion
Relaunch the manager to update the mod list
```

The suggestion does not help since r2modman does not update its mod list from thunderstore.io immediately.

**To Reproduce**
1. Create/upload a new mod on [thunderstore.io](https://thunderstore.io)
2. Click on the 'Install with Mod Manager' button on the mod page
3. (optional) confirm opening r2modman

**Expected behavior**
Even though the mod is not in r2modman's mod list the very fact that we try to install it via `ror2mm://v1/install/thunderstore.io/...` should allow r2modman to try to pull the mod and install it.

**Note**
Yes this is an edge case, and it's not of high priority, I know but still I wanted to report it.

**Comment by ebkr** [comment]
Yeah it’s not really a manager issue because the API has a timed cache on it, so there’s nothing I can really do about it
