### ISSUE TITLE
[BUG] - Broken local mod list

### ISSUE THREAD

**Issue by frenchiveruti** [ebkr/r2modmanPlus#473]
**Describe the bug**
Basically this:
![imagen](https://user-images.githubusercontent.com/1095997/114048284-c982b180-9860-11eb-92fc-82003f4f0b0d.png)
As you can see, I have 23 mods, none appears on screen.

**To Reproduce**
1. Create a mod zip
2. Set up manifest.json as stated in the valheim thunderstore
3. Try to import locally to test it
4. Fail, manifest V2 needed
5. Set up manifest V2
6. Import to list
7. ??? (This is where the bug is located)
8. Nothing happens, mod is not added to list.
9. Restart application.
10. Everything fails horrendously.
11. 

**Expected behavior**
ModList should show new mod and also previous ones.

**Screenshots**

**Additional context**
I tried to make a zip file for this mod:  
https://www.nexusmods.com/valheim/mods/40

Here's my zipfile now (can't be imported to the app due to Manifest v1, convert manifest to V2 and it **will** fail)
[Craft-From-Containers.zip](https://github.com/ebkr/r2modmanPlus/files/6279558/Craft-From-Containers.zip)
Also here's my profile file:
[Broken profile frenchiveruti.zip](https://github.com/ebkr/r2modmanPlus/files/6279561/Broken.profile.frenchiveruti.zip)

Important notice, the mod imported IS in the list named mods.yml, although it's using manifestV2.
(renamed for upload to GitHub)
[mods.txt](https://github.com/ebkr/r2modmanPlus/files/6279570/mods.txt)

**Comment by ebkr** [comment]
> although it's using manifestV2.
It's not.

![image](https://user-images.githubusercontent.com/10426228/114187527-02458800-9940-11eb-8811-58ec068a8656.png)

You have this:
![image](https://user-images.githubusercontent.com/10426228/114187550-0a052c80-9940-11eb-8c4e-b2eed379f448.png)

It's also case-sensitive, so you need to completely re-structure it.

Regarding it breaking, I'll keep this issue open as a reminder to sort that out.

**Comment by frenchiveruti** [comment]
> It's not.

It is!  (well, it was, I had to delete it)
Check the mods.txt in the main post:
![imagen](https://user-images.githubusercontent.com/1095997/114196746-08c80580-9928-11eb-92fd-abeb8d561b05.png)

**Comment by frenchiveruti** [comment]
> It's also case-sensitive, so you need to completely re-structure it.

This was never stated, specially here:
https://github.com/ebkr/r2modmanPlus/wiki/Installing-mods-locally#what-does-a-manifestv2-look-like  
There's no comment on how each line should be formatted, I know that JSON doesn't allow comments but for a wiki without the way to write each line makes it really hard to know the correct formatting, string limit, etc.

**Comment by ebkr** [comment]
JSON itself is case-sensitive. It's somewhat implied.

> but for a wiki without the way to write each line

That's the entire point in the **What does a ManifestV2 look like?** section.
The code block showing the example manifest v2 is exactly how you should write it.

**Comment by SirHamburger** [comment]
I've more or less the same problem with the following Zip-File under Linux:
[ArtifactOfDoomR2Modman.zip](https://github.com/ebkr/r2modmanPlus/files/6292582/ArtifactOfDoomR2Modman.zip)

The mod is added successfully but afterwords every mod including the locally installed disappears.
![image](https://user-images.githubusercontent.com/32701157/114318169-15a54e80-9b0c-11eb-867c-bd2c23e81334.png)

**Comment by ebkr** [comment]
@SirHamburger Your dependencies field is lowercase which doesn't match the Manifest V2 format.
![image](https://user-images.githubusercontent.com/10426228/114325358-99b8ff80-9b27-11eb-8779-bd653c5b38cf.png)

**Comment by SirHamburger** [comment]
Well i thought i checked it. 
Thank you very much for the fast reply. That fixed it for me.
Would it perhaps be possible for you to make an error message if the manifest was not parsed successful?

**Comment by ebkr** [comment]
Yeah I keep meaning to, but I’m also planning on overhauling it soon to no longer require a manifest v2. It’ll either just be an additional author field, or a mix of inferred + manual typing in-app.

**Comment by ebkr** [comment]
Closing this issue as the next release will contain an update to import mods easily without the need for a manifest file.
