### ISSUE TITLE
[BUG] - Deleted files appear again after importing the same version.

### ISSUE THREAD

**Issue by SirHamburger** [ebkr/r2modmanPlus#481]
**Describe the bug**

If you install a local mod and change the name of a file or delete a file it appears again after you import a new version since it's still in cache. 
I'm using r2modman-3.1.10.AppImage

**To Reproduce**
1. Import a local mod e.g. [ArtifactOfDoom1.zip](https://github.com/ebkr/r2modmanPlus/files/6292620/ArtifactOfDoom1.zip)
2. Rename a file and import it again e.g. [ArtifactOfDoom2.zip](https://github.com/ebkr/r2modmanPlus/files/6292623/ArtifactOfDoom2.zip)
3. View the local profile folder and the contents of the plugins folder
4. See all files including the deleted

**Expected behavior**
Deleted files stay deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/32701157/114318601-07f0c880-9b0e-11eb-99e0-01e2036fbb4b.png)

**Comment by ebkr** [comment]
You should increase the version number, or uninstall and run the clean mod cache setting.

**Comment by SirHamburger** [comment]
Thanks for your fast answer
Sure that would work. But in case of installing local mods for debugging purposes you don't want to always increase the version number. And if you've more than one profile with the same mod the clean cache don't work.
Maybe it's more a feature request for disabling the caching for local installed mods.

**Comment by ebkr** [comment]
Can you toggle the download cache to disabled?

**Comment by SirHamburger** [comment]
I can toggle it but the old files still get added.

**Comment by ebkr** [comment]
Alright, I’ll take a look

**Comment by ebkr** [comment]
Sorry it took so long to fix. All sorted for the next release now though!
