### ISSUE TITLE
geting an error when enableing mods

### ISSUE THREAD

**Issue by Freedom16789** [ebkr/r2modmanPlus#486]
Error reading directory in BepInExTree build for directory: C:/Users/Freedom16789/AppData/Roaming/Thunderstore Mod Manager/DataFolder/Valheim/profiles/Default/BepInEx/plugins/ValheimEventEnhancer - v0.2-154-0-2-1614515966/ValheimEventEnhancer - v0.2-154-0-2-1614515966/ValheimEventEnhancer/config
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. at System.IO.PathHelper.GetFullPathName() at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths) at System.IO.Path.GetFullPathInternal(String path) at System.IO.FileInfo.Init(String fileName, Boolean checkHost) at r2io.FileOperations.<>c.<ReadDir>b__17_1(String s) at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Linq.Buffer`1..ctor(IEnumerable`1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) at r2io.FileOperations.<>c__DisplayClass17_0.<ReadDir>b__0() at r2io.Utilities.RunSafe(String appName, Int32 appId, String path, Func`1 runFunc)

Suggestion
Relaunch the manager as admin, directory failed to be read.

**To Reproduce**
1. click Enable 
2. See error

the this is all reddy in admin mode any help would be appreciated

**Comment by ebkr** [comment]
You manually added `ValheimEventEnhancer` right?
Can you rename it something shorter? The error is telling you that name to get to it is too long.
I'd say rename your `ValheimEventEnhancer - v0.2-154-0-2-1614515966` to `ValheimEventEnhancer`

If you added this using the ManifestV2 method, please fix the Name field in the manifest.
