### ISSUE TITLE
[BUG] - Cant install ZIP files 

### ISSUE THREAD

**Issue by Drakcain** [ebkr/r2modmanPlus#487]
**Describe the bug**
When attempting to install mods using a zip file an error comes back saying "No file found in zip with name "manifest.json". Contact the mod author, or create your own."

In addition, Drag & Drop doesn't work either and gives a (/) icon over the r2modman windows.

**To Reproduce**
1. Go to 'settings'
2. Click on 'profile"
3. Scroll down to 'import local mod'

**Comment by ebkr** [comment]
Yeah, there’s a link that tells you how to set them up.

https://github.com/ebkr/r2modmanPlus/wiki/Installing-mods-locally#developers
