### ISSUE TITLE
[BUG] - r2Modmanager white screen

### ISSUE THREAD

**Issue by Greyscar** [ebkr/r2modmanPlus#488]
I have no clue how this happened or how to fix it, but I can't get my R2Modmanager to load. It loads up to a blank white screen and I have tried to uninstall and reinstall a few times but nothing is working. I don't know what to do with it. 
![Modmanager won't load](https://user-images.githubusercontent.com/59831536/115804880-802a7a00-a3a9-11eb-9c65-7ce263805dcf.PNG)

**Comment by ebkr** [comment]
Have you tried running as admin?
Has your antivirus killed it?

If neither of those are the case, press ctrl+shift+i and go to the console tab.
Send a screenshot of any errors.

**Comment by bluemoon654** [comment]
my friend is having the same problem we still cant figure it out

**Comment by ebkr** [comment]
@bluemoon654 Can you do the things I sent above?

**Comment by ebkr** [comment]
@bluemoon654 @Greyscar If there's no update in two days I'll go ahead and close this issue.

You should be able to reply to this issue still, however if not feel free to make a new one.
If you do make a new one, please do what I asked above and include that in your new issue.
