### ISSUE TITLE
dyson sphere program directory error

### ISSUE THREAD

**Issue by spookyspaghett** [ebkr/r2modmanPlus#507]
error dyson sphere program directory not found

![image](https://user-images.githubusercontent.com/83368393/116454130-f3c3ff80-a85f-11eb-9856-691ec3965321.png)
![image](https://user-images.githubusercontent.com/83368393/116454165-fcb4d100-a85f-11eb-9bab-2bc0a87e9873.png)

idk much abt pcs or mods so pls help

**Comment by spookyspaghett** [comment]
this happens as well when i try to open the vanilla game

**Comment by ebkr** [comment]
Give this a go
https://github.com/ebkr/r2modmanPlus/wiki/Why-aren%27t-my-mods-working%3F

**Comment by spookyspaghett** [comment]
thx it worked
