### ISSUE TITLE
Lock the left sidebar while scrolling (in the installed tab)

### ISSUE THREAD

**Issue by breadguy69** [ebkr/r2modmanPlus#527]
**What problem does the feature request solve?**
not having to scroll back up to the top to see all the buttons

**Example mock-up (optional)**
![image](https://user-images.githubusercontent.com/21149431/118059746-453fb480-b35f-11eb-84ea-51404ce730f2.png)

**Comment by ebkr** [comment]
I fixed that in an update a few versions ago, no idea why it broke again 🤔
