### ISSUE TITLE
Game crashes if Steam is not started

### ISSUE THREAD

**Issue by ebkr** [ebkr/r2modmanPlus#53]

**Comment by Angular-Angel** [comment]
So, I think I ran into a varient of this, and it caused me a fair bit of grief - I ran r2modman on linux, and while I pointed it to my risk of rain folder, it was not pointed to my steam folder, and therefore risk of rain was already crashing, despite the fact that I already had steam running. This applied even to when I ran ror2 from my library, and even after uninstalling it, deleting the game folder, and reinstalling, which was very concerning. But, once I pointed r2modman to the steam folder, things started working again. Especially problematic, however, is that it was a silent crash - it went to a black screen, like normal for ror2 start up, and then the game just disappeared with no message. If r2modman could catch this and show a message, something along the lines of "Set steam folder to stop your game crashing", that would be very nice. -_-

**Comment by ebkr** [comment]
@Angular-Angel The game wouldn’t have started through the manager had it not been pinned to your steam folder. This PR changed the way game execution worked so that the game now starts using:
./steam -applaunch <gameid> …


This means that Steam handles game loading, not the manager anymore.
