### ISSUE TITLE
[FEATURE REQUEST] - Back button

### ISSUE THREAD

**Issue by eankeen** [ebkr/r2modmanPlus#535]
**What problem does the feature request solve?**
After choosing a profile, the only way to go back to the profile selection screen is to press the middle mouse button (Alt + Left does not work) To make it easier to re-choose a profile without relaunching the whole app I propose that a back button should be added

**Example mock-up (optional)**
![image](https://user-images.githubusercontent.com/24364012/119273140-02040200-bbf9-11eb-9d67-b6d8e28e7fc3.png)

**Additional information (optional)**
If you want any changes, let me know (I wouldn't know what you would want it to look like). I just wanted to throw this out there

**Comment by ebkr** [comment]
You can change profile by going to Settings -> Change profile

**Comment by eankeen** [comment]
haha apologies, should have read the settings first

have a good day,
edwin
