### ISSUE TITLE
[BUG] - Application starts but does not work ! (Valheim)

### ISSUE THREAD

**Issue by Daimonicon** [ebkr/r2modmanPlus#539]
**Describe the bug**
No connection at all can be established at the start. (see pic_01)

Only after I went to Settings -> Debugging -> "Run preloader fix" I was able to find out that the Valheim directory was not recognised at all, even without question it is correctly specified. (see animated_gif)

**To Reproduce**

It already doesn't work at startup on Windows 10 (2004+20H1+21H1) what steps can I describe ?

**Expected behavior**
I select the game, in my case "Valheim", and the programme starts with an online connection for downloading mods. Then it manage the mods.

**Screenshots**
![pic_01](https://user-images.githubusercontent.com/84905652/119807020-05daa180-bee3-11eb-9984-578733fa1c56.PNG)

![animated_gif](https://user-images.githubusercontent.com/84905652/119807090-18ed7180-bee3-11eb-811a-6ba11237e756.gif)

**Additional context**
And finally - When you close the app it hangs as a task every time and I have to kill it manually.
There is no log file except for the output after "Run preloader fix".

**Comment by ebkr** [comment]
These are two unrelated issues.

The preloader fix isn't available for Valheim, and is broken in the current version anyway (fixed for the next release though).

Regarding your connection issue, it's likely that you just need to allow the manager through your firewall.
If you can access this site, it's either your firewall or antivirus that's prevent the manager from connecting: https://valheim.thunderstore.io/api/v1/package/

**Comment by Daimonicon** [comment]
The preloader fix was not directly mentioned as a problem, but I thought it was a hint that the Valheim path was not found at all.

The app can start Valheim via Steam, so the path can be found. However, no mods are recognised and there are some available. Even a manual import does not work.

The app is unblocked in the firewall and the r2modman folder is excluded from monitoring by Defender.

I can call up the page mentioned.
![url](https://user-images.githubusercontent.com/84905652/119814999-5c4bde00-beeb-11eb-8c0c-79377961da7a.PNG)

**Comment by ebkr** [comment]
Are you still having trouble connecting to Thunderstore now that it's allowed through your firewall?

> However, no mods are recognised

Are the mods in the `<profile folder>/BepInEx`, or `<game dir>/BepInEx` ?

**Comment by Daimonicon** [comment]
> Are you still having trouble connecting to Thunderstore now that it's allowed through your firewall?

Yes, still no connection can be established.

> Are the mods in the <profile folder>/BepInEx, or <game dir>/BepInEx ?

Currently the mods are still under "~\steamapps\common\Valheim\BepInEx\plugins", because I have installed them manually so far.

**Comment by ebkr** [comment]
The manager won't load any mods under `~\steamapps\common\Valheim\BepInEx\plugins`. It maintains it's own independent from other installed mods.
To access to folder, go to `Settings -> Browse profile folder`.

What distro are you running?

**Comment by Daimonicon** [comment]
> The manager won't load any mods under ~\steamapps\common\Valheim\BepInEx\plugins. It maintains it's own independent from other installed mods. This is intended because people forget they have manually installed mods, which may break in an update, and it's not easily diagnosable.
To access to folder, go to Settings -> Browse profile folder.

Ok that means I would have to copy my mod selection to "~\r2modman\data_folder\Valheim\profiles\Mods_Complete\BepInEx" ? I copied a mod to the folder mentioned above as a test and it is not recognised.

> What distro are you running?

What is meant by Distro ? Game version, r2modman version ?

**Comment by ebkr** [comment]
> I copied a mod to the folder mentioned above as a test and it is not recognised.
It won't appear in the manager if manually installed, however will be loaded upon starting the game.

> What is meant by Distro ? Game version, r2modman version ?
I assumed you were running Linux since you said the path was `~\steamapps\common\Valheim\BepInEx\plugins`. with `~` being the home directory in Linux. (Just checked above and you said Windows 10, so ignore this 👀 ).

Are you absolutely sure you've explicitly allowed it through your firewall? Do you have another that comes with your antivirus?

**Comment by Daimonicon** [comment]
>It won't appear in the manager if manually installed, however will be loaded upon starting the game.

OK, I'll test it as described.

> I assumed you were running Linux since you said the path was ~\steamapps\common\Valheim\BepInEx\plugins. with ~ being the home directory in Linux. (Just checked above and you said Windows 10, so ignore this 👀 ).

ah, no, it's Windows 10 :-)

> Are you absolutely sure you've explicitly allowed it through your firewall? Do you have another that comes with your antivirus?

I have unblocked it to the Windows Firewall. I also have Malwarebytes, but it is currently deactivated. To be on the safe side, I have explicitly unblocked it under Defender and MB, i.e. the folder, the exe and the URL.

**Comment by ebkr** [comment]
Any luck if you run the manager as admin?

**Comment by Daimonicon** [comment]
BepInEx and the mods are now in the profile folder and when I click "Start modded" BepInEx hangs. The app is started as admin.

![BepInEx](https://user-images.githubusercontent.com/84905652/119822004-7984aa80-bef3-11eb-876a-fff32e3f9989.PNG)

**Comment by ebkr** [comment]
Press `ctrl`+`shift`+`i` and go to the Networks tab.
Then back on the manager screen, go to Settings and click the `Refresh online mod list`.

You should see a request fail in the networks tab. Click it and send a screenshot.

**Comment by Daimonicon** [comment]
After the game hangs or better BepInEx starts the game after about 5 min. anyway, but bepinex spams several errors "NullReferenceException". If the log file helps, I'll send it to you ?

And for the network tab I get the following :
![network_tab](https://user-images.githubusercontent.com/84905652/119824081-cec1bb80-bef5-11eb-9733-13dcc56873d8.PNG)

**Comment by ebkr** [comment]
Ah so it looks like you just have real slow internet. If you join this discord I'll send you a build with an increased duration and we'll see if that solves it.

https://discord.com/invite/jE2zWHY

**Comment by Daimonicon** [comment]
hmm, on the contrary, the line is actually very fast (1000 mbit) but I can't 100% rule out setting errors.

But I'm happy to try it with Discord.

**Comment by Daimonicon** [comment]
ok bin bei discord als "Daimonicon"

**Comment by Daimonicon** [comment]
it's the same as before

![network_tab_2](https://user-images.githubusercontent.com/84905652/119832651-adb19880-befe-11eb-9803-73b8538fd01c.PNG)

**Comment by Daimonicon** [comment]
Jupp was NetLimiter
