### ISSUE TITLE
[FEATURE REQUEST] - "Start in Offline Mode" option

### ISSUE THREAD

**Issue by TheRiverElder** [ebkr/r2modmanPlus#568]
**What problem does the feature request solve?**
It spent minutes (even longer) to wait r2modman "Connecting to Thunderstore" even when the internet is totally off.

So could there be an option for us to start r2modman in offline mode (Is there offline mode for r2modman?) manually, so that we don't need just wait to fail connecting to the server when playing for single player or the network is disabled.

**Comment by ebkr** [comment]
This should already exist?

![image](https://user-images.githubusercontent.com/10426228/124789388-249c7100-df42-11eb-890b-32818381945a.png)

**Comment by TheRiverElder** [comment]
It may turns out to be that it's the disk problems caused by the blue screen made the program stuck. I tried after a normal reboot, and it works. Sorry to bother you for this. It's really a good and convenient mod manager : ）
