### ISSUE TITLE
[BUG] - Can zoom out, not zoom in

### ISSUE THREAD

**Issue by APPARENTLY-OK** [ebkr/r2modmanPlus#570]
Using Ctrl+- allows you to zoom out, however now you can't zoom in using Ctrl-+
I did this out of curiosity and now I'm using ant zoom

**Comment by ebkr** [comment]
It's `ctrl`+`shift`+`=` for some reason (thanks Electron).
Alternatively `ctrl`+`0` to go back to the original zoom level.
Lastly, you can press `alt` and go to `View > Actual size`

**Comment by APPARENTLY-OK** [comment]
you're a life saver
