### ISSUE TITLE
[BUG] - WHITE SCREEN

### ISSUE THREAD

**Issue by monkeyman1663** [ebkr/r2modmanPlus#571]
**Describe the bug**
i start r2modman and get a white screen...program seems to be working but i cant see anything, i tried re-installing but didnt work..i also waited for like 20 mins and didnt work

**To Reproduce**
Opening r2modman
![modman](https://user-images.githubusercontent.com/86580703/123568293-04c2bb80-d792-11eb-936d-bd91dc23e112.png)

**Comment by monkeyman1663** [comment]
![modman2](https://user-images.githubusercontent.com/86580703/123582443-d356e980-d7ab-11eb-9d14-bbc2955a9582.png)

heres with console showing

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/wiki/Error:-White-screen-on-startup#corrupted-settings-on-update
