### ISSUE TITLE
Can't connect to Thunderstore

### ISSUE THREAD

**Issue by TheBeanBurrito2** [ebkr/r2modmanPlus#574]
The mod manager will not connect to Thunderstore no matter what has been tried. Put it through the firewall already and still isn't working.

**Comment by ebkr** [comment]
Have you tried running as admin?
How about clicking continue offline, then going to `Settings -> Refresh online mod list`

**Comment by TheBeanBurrito2** [comment]
Tried admin and it didn't work either. Then we stopped messing with it for
a bit then next time I saw him it was working just fine. Not sure what
fixed it but it is fixed now. Thanks for the help!
