### ISSUE TITLE
[BUG] - "Mechnica" instead of "Mechanica" during Directory Selecting

### ISSUE THREAD

**Issue by Spyrox17** [ebkr/r2modmanPlus#587]
**Describe the bug**
Mod loader is searching for "Mechnica.exe" instead of the correct "Mech**a**nica.exe", resulting in being unable to load mods into the game correctly as it cannot find the actual exe.

**To Reproduce**
1. Select the Mechanica profile
2. Go to settings
3. Click on "Change Mechanica Directory"
4. Find the correct Mechanica Directory
5. Select proper folder

**Expected behavior**
The loader to accept the correct exe

**Screenshots**
![Issue](https://user-images.githubusercontent.com/35882822/127300287-13e60abd-e214-4d5a-a6f6-1d22bc660ed3.png)

**Additional context**
You can get around the issue by changing the exe to Mechnica, selecting it in the mod loader, and then changing it back to the correct name and then starting modded.

**Comment by ebkr** [comment]
Oops, thanks for the heads up.
