### ISSUE TITLE
[BUG] - When saving a config, 10 config files are saved instead of just the one I edit.

### ISSUE THREAD

**Issue by JamieRCHI** [ebkr/r2modmanPlus#588]
**Describe the bug**
When I click on the Save button to save my changes to a single config file, 10 apparently random config files are also saved. This means that the option to sort by last updated does not work.
Note: I am using this with the Dyson Sphere Program game.
Edit: It seems to work better if I close R2ModmanPlus and then reopen.
        Is the time value in the Date Modified field rounded in some way to cause this?

**To Reproduce**
1. You may need more than 10 mods installed or at least more than one.
2. Click on the Edit Configs button.
3. Edit the config for any mod.
4. Click on Save.
5. Go to the mod location (in my case AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\Default\BepInEx\config) and view in Windows Explorer and Sort by Date with View Details enabled.
6. 10 of the config files have been updated instead of just the one. All with the exact same value in the Date Modified column.

**Expected behavior**
Only the config file I changed should be updated.

**Comment by ebkr** [comment]
I don't appear to be able to reproduce it.
![image](https://user-images.githubusercontent.com/10426228/128631860-37374c51-c372-4c5c-85b8-52f789aabbe9.png)

**Comment by JamieRCHI** [comment]
The picture you posted reproduces the problem exactly. 10 or more of the files you show have the exact date and time stamp. This is Not normal. Only the recent config file you edited should have an updated time stamp. If I go to Explorer and edit one config file with a text editor, only one file has a new date/time stamp. As you have shown with your picture, 11 files have the exact same date/time stamp when edited within R2ModmanPlus.

**Comment by ebkr** [comment]
No, look at the date those files were modified vs the file highlighted.

Those files were generated from an initial run of BepInEx.

**Comment by JamieRCHI** [comment]
Ok, Thanks. 
I guess that makes sense if all the mods were active when BepInEx was first run. 
For me, I only added 1 or 2 mods at a time, so I should not have any config files with the same exact date/time.

Could this happen if several mods are updated at the same time? Usually only one or two update at a time, but a few days ago several updated at the same time.

Other than that, files seem to update ok when edited in the mod manager now.  Thanks for your assistance.

**Comment by ebkr** [comment]
Yeah, there may be new config value added which needs to be included in the file which in turn would cause it to update
