### ISSUE TITLE
[BUG] - Unable to launch H3VR as modded game

### ISSUE THREAD

**Issue by BurgerBoiOG** [ebkr/r2modmanPlus#594]
**Describe the bug**
When I click "Start Modded" in r2modman in h3vr, it launches the game in vanilla and the command box shows the attached error.
![Screenshot 2021-08-09 232344](https://user-images.githubusercontent.com/88698710/128805072-00f5a62c-db9e-4e2c-b0fa-a49640cd5e80.jpg)

I have tried uninstalling the game and all the mods and re-installing but the issue still persists. Also, the error seems to say my game is not up to date but in fact it is.

**Comment by ebkr** [comment]
Change to one of the alpha branches

**Comment by BurgerBoiOG** [comment]
How do I do that?

**Comment by ebkr** [comment]
Right click the game on steam
Go to the betas tab
Switch to one of the alpha branches
