### ISSUE TITLE
[BUG] - R2ModMan cannot launch mods under Steam Proton

### ISSUE THREAD

**Issue by Frityet** [ebkr/r2modmanPlus#611]
**Describe the bug**
I have installed a bunch of mods for H3VR, and I attempt to launch the game with `Start Modded`, but presumably because I am running Steam Proton, the game does not run

**To Reproduce**
1. Use a Linux Distro
2. Install Steam Proton
3. Install mods
4. Press `Start Modded`

**Expected behavior**
I expected H3VR to start up with mods

**Comment by ebkr** [comment]
Might be something to do with it failing to find the user.reg file.
Which distro?

**Comment by Frityet** [comment]
Garuda (Arch) (i am really sorry, i was peer pressured into installing it and i can't change because my usb broke)

**Comment by Frityet** [comment]
nvm it works now for some reason
