### ISSUE TITLE
[FEATURE REQUEST] - Change Data Location from C: Drive.

### ISSUE THREAD

**Issue by RaynorCZE** [ebkr/r2modmanPlus#620]
**What problem does the feature request solve?**
Limitation of space, since I believe I am not the only one who utilizes C Drive as System only Drive therefore it does not have as much space as other Drives (my example: C: System drive (125 GB), F: HDD (1TB), D: SSD (1TB) ) 

Thanks in advance

**Comment by ebkr** [comment]
This is already a feature.

Settings -> Change data folder directory

**Comment by RaynorCZE** [comment]
> This is already a feature.
> 
> Settings -> Change data folder directory

oh yeah sorry somehow I missed that

Thanks a lot
