### ISSUE TITLE
[BUG] - Risk of Rain 2 not starting with mods due to external steamapps path

### ISSUE THREAD

**Issue by Compile-Time** [ebkr/r2modmanPlus#630]
**Describe the bug**
Steam has the ability to define additional steam library folders. When a Proton game is in such an external library folder r2modman fails to load the installed mods and simply starts the game normally. What makes this issue especially bad is the fact that the end user does not get an error message when that happens. So the user is simply left wondering what went wrong.

Based on the code I observed two problems:
1. The `libraryfolders.vdf` is not correctly parsed for Linux. Because of this r2modman is not able to find the manifest file for the game.
2. The error for not being able to find the manifest file is _not_ displayed to the end user.

**To Reproduce**
1. Start a Proton game with mods that is installed on a path different to `.local/share/Steam/steamapps`
2. Wait until the game starts
3. Check if the game started with all enabled mods

**Expected behavior**
The game should start with all enabled mods.

**Comment by ebkr** [comment]
Hey, you should be able to set the game directory manually via the manager settings.

**Comment by Compile-Time** [comment]
> Hey, you should be able to set the game directory manually via the manager settings.

Yeah, except that directory is not used to find the manifest. The code uses the paths of the `libraryfolders.vdf` for the manifest search and if the parsed manifest is not correctly interpreted, it causes the search to fallback to the default steamapps path.

> Failing to parse the libraryfolders.vdf file isn’t shown to the user because there’s nothing they can do. Instead it’ll fail silently and should prompt to set the directory manually when attempting to start modded.

This makes sense, but because of the above fact I have observed it ends up not showing anything in the UI and simply starts the game without mods.

**Comment by ebkr** [comment]
Ah, that just reminded me that the libraryfolders.vdf format changed over the past few Steam updates. The Windows resolver supports the new format however I didn't change it for Linux afaik. This should be a pretty trivial fix at least.

**Comment by Compile-Time** [comment]
I created a PR for this issue: #631

**Comment by ebkr** [comment]
You beat me to it on this one, thanks! Merged into the develop branch.
If you've found anything else or want to talk about Linux support then feel free to join the r2modman discord.
https://discord.gg/jE2zWHY

**Comment by Compile-Time** [comment]
Thanks for merging! Closing
