### ISSUE TITLE
[BUG] - Manifest search error is not shown in UI

### ISSUE THREAD

**Issue by Compile-Time** [ebkr/r2modmanPlus#632]
**Describe the bug**
This relates to #630. When the manifest of a game cannot be found r2modman simply starts the game without mods. This makes it hard to troubleshoot issues for users that don't know how to read code and to run r2modman in dev mode.

**To Reproduce**
1. Start a Proton game with an external steam library
2. As a developer watch the value of `manifestLocation` in `linux/GameDirectoryResolver.isProtonGame()` or `linux/GameDirectoryResolver.ensureWineWillLoadBepInEx()`
3. The game will start with no mods
4. `manifestLocation` will contain an R2Error

**Expected behavior**
An error should be shown that the manifest could not be found in the searched locations. This would make it easier for a user to report an issue.

**Comment by Compile-Time** [comment]
PR for the Issue: #633

**Comment by ebkr** [comment]
There's a very slight formatting issue but I'll fix that on my end.
Merged, thanks again!

**Comment by Compile-Time** [comment]
Closing
