### ISSUE TITLE
Profiles and cache are cleared on update

### ISSUE THREAD

**Issue by blazingdrummer** [ebkr/r2modmanPlus#66]
Should still have the opportunity to backup files before restarting the program though. Would appreciate confirmation that this isn't just on my end, and that other people have experienced it.

Feel free to ping/message me on Discord @blazingdrummer#1929.

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/commit/d26596118bf0a64748599ee1777e32240e048465
