### ISSUE TITLE
[BUG] - .appimage cannot see /mnt/ and looks for /media/

### ISSUE THREAD

**Issue by MANTISxB** [ebkr/r2modmanPlus#668]
Bug: 
After .appimage is integrated and run (garuda linux), when selecting "Run Modded" this error pops up.

"Error
An error occured whilst searching Steam library locations
ENOENT: no such file or directory, scandir '/run/media/"USERNAME/"DRIVE"/Steam/steamapps'"

**To Reproduce**
1. Set location of riskofrain.exe
2. Select Start Modded from R2Modman
3. Error occurs

**Expected behavior**
Should launch from /mnt/ instead of looking for /media/

**Additional context**
First time running this from garuda linux (originally running on Linux Mint) but now the program will not launch ROR2 at all and throws the error.

**Comment by ebkr** [comment]
Does it resolve itself if you set the directories manually in the manager settings?

**Comment by Fidgetcetera** [comment]
Got a friend who's having an error that seems about the same, running Manjaro (maybe this is weirdly common to arch distros??). Her steamapps folder is absolutely nowhere near where it's trying to find it in /run/media, and the log appears to not show anything past a previous, successful launch. This continued to happen through completely wiping the profile data from the ~/.config/r2modmanPlus-local folder.
Looks like the same error:
```
Error
An error occured whilst searching Steam library locations
ENOENT: no such file or directory, scandir '/run/media/cricketm/Storage/Steam/steamapps'
```

**Comment by Xeranok** [comment]
> Got a friend who's having an error that seems about the same, running Manjaro (maybe this is weirdly common to arch distros??). Her steamapps folder is absolutely nowhere near where it's trying to find it in /run/media, and the log appears to not show anything past a previous, successful launch. This continued to happen through completely wiping the profile data from the ~/.config/r2modmanPlus-local folder. Looks like the same error:
> 
> ```
> Error
> An error occured whilst searching Steam library locations
> ENOENT: no such file or directory, scandir '/run/media/cricketm/Storage/Steam/steamapps'
> ```

i definitely didnt have this issue until i used an arch distro, the way i fixed it was removing the directory that doesnt exist from all copies of libraryfolders.vdf on my system.
