### ISSUE TITLE
[BUG] - DSP plugins folder disappeared

### ISSUE THREAD

**Issue by JamieRCHI** [ebkr/r2modmanPlus#683]
**Describe the bug**
Dyson Sphere Program: BlueprintTweaks Mod: LDBTool.dll missing
Somehow the steamapps\common\Dyson Sphere Program\BepInEx\plugins folder disappeared and some of the older mods quit working as a result. I am not convinced that this program caused this, but a mod developer suggested the mod manager might be at fault.

**To Reproduce**
Not sure how this happened. 

**Expected behavior**
Many of the newer mods in DSP still require some of the older mods to function. Such as LDBTool. 

Even though the newer mods should be using 
AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\Default\BepInEx\config,
the steamapps\common\Dyson Sphere Program\BepInEx\plugins folder should remain.

The Mod Manager should verify files when a mod is installed and pop up an error dialog if the destination file or folder of the mod does not exist. A repair option to check and verify for missing folders  and mods would be helpful.

**Work Around**
I was able to find and restore the LDBTool.dll file from the AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\cache folder.

**Comment by ebkr** [comment]
I don’t think this is a manager issue so much as a computer specific problem. Sounds like your antivirus may have removed it, especially if it worked previously.

The manager doesn’t touch the files unless you’re installing/updating that mod. It doesn’t remove files unless you specifically click uninstall, and those are scoped to specific subdirectories (so uninstalling mod X won’t touch mod Y unless Y depends on X).

In terms of verifying and reinstalling, just export your profile and reimport.

**Comment by ebkr** [comment]
Ah also, re-reading this and the manager doesn't even touch `steamapps\common\Dyson Sphere Program\BepInEx\plugins`.
So it's entirely non-related to the manager.

**Comment by JamieRCHI** [comment]
Thanks. Just a shot in the dark. Windows Defender is set to ignore the entire drive that my games have been installed on, and in any case would have only removed the DLL and never the entire folder. It would have ignored the other files and there would have been something left.

It probably was not an update to the game that did this. If so others would have seen this happen as well.

So in this game it must be the BepinEX mod that defines where all other DSP mods go. Maybe that mod is what is causing the problem I saw.
