### ISSUE TITLE
Allow profiles to include mods that are disabled

### ISSUE THREAD

**Issue by blazingdrummer** [ebkr/r2modmanPlus#69]
This would be an extremely useful feature for current/future modpack creators who want to include mods that imitate Artifacts like ChestItemPicker, Sacrifice, and SpiteMod or unfinished characters like PlayableScavenger, BootlegChef, or SniperRework, but don't want them to be enabled by default.

Feel free to ping/message me on Discord @blazingdrummer#1929.

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/commit/2bad2546d56f2616fcae8f82ccde589acf832777
