### ISSUE TITLE
'Start Modded' says Risk of Rain 2 is launching but game never launches

### ISSUE THREAD

**Issue by mpattik** [ebkr/r2modmanPlus#698]
When I click Start Modded or Start Vanilla buttons a pop-up appears telling me the game is launching via Steam as expected. However the game never launches.

![image](https://user-images.githubusercontent.com/43732347/147629557-fc217902-f1bb-429c-ad9b-bd247686348b.png)

I do not receive any errors. The pop-up occurs as it should, but the game simply never launches. 
I installed r2modman as an administrator. I am running r2modman as administrator. I have updated the launch parameters through r2modman settings. I have run the preloader fix. I have updated the Steam and Risk of Rain 2 directories. I have uninstalled and reinstalled both Risk of Rain 2 and r2modman multiple times. I own a legitimate version of the game. Steam, Risk of Rain 2, and r2modman are all installed on my C drive.

Possible issues:
When I verify the integrity of the game files through Steam it says 100% valid, but when running the preloader fix through r2modman it says 107 files missing.
I have added/altered my PATH various times when using virtual environments, which could be an issue.
Maybe an issue with Steam permissions? I know Steam can cause unexpected problems with modding at times.
I noticed if I completely exit steam that r2modman does not run Steam despite saying it is.

**Comment by ebkr** [comment]
This likely means a problem with the steam directory. You can open file location of steam via task manager to verify.

**Comment by qkweint** [comment]
I had a very similar issue on linux, what I did is I re-installed risk of rain 2 into the default steam directory rather than a custom one which fixed the issue.
