### ISSUE TITLE
"Start modded" and "Start vanilla" buttons could stand out more

### ISSUE THREAD

**Issue by blazingdrummer** [ebkr/r2modmanPlus#70]
The selections are currently the exact same appearance as any of the other options, which caused me to accidentally click them a few times at first. My suggestions would be make them bold text, give them a background color, or maybe just a border to distinguish them from the other buttons. Now that I've gotten used to them, it's not a problem, so maybe I was just too dumb 😁 and it wouldn't be worth the time. Either way, just thought I'd mention it.

Feel free to ping/message me on Discord @blazingdrummer#1929.

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/commit/63bc68f333ed6f3a3b81cd135782b9503c14c81c
