### ISSUE TITLE
Valheim Modded - "Steam Not Initialized" ERROR

### ISSUE THREAD

**Issue by LMNTAL3327** [ebkr/r2modmanPlus#705]
Everytime i try to run Valheim modded on the r2rmodmanager launcher it comes up with steam not initialized. I dont really get all this stuff as im new to pc. I downloaded the r2rmodmanager, installed the mods i wanted through the manager, and then attempted to play. It loads the game but then gets stuck on the game title and then the mouse wheel just spins and nothing happens. The launcher says Steam not Initialized. Ive tried launching with steam already open (i own the game) and have also tried launching without steam open and both produce similar results. If i load without opening steam first then nothong happens and i get the title crash, if i load with steam already open then i get a red box and nothing happens.

Any help would be appreciated.

![16424278556224609559769378496597](https://user-images.githubusercontent.com/97895002/149781874-a5841a88-a99e-49df-ac4a-4bd91fa2ec36.jpg)

![16424279286085913765019041804200](https://user-images.githubusercontent.com/97895002/149782020-a4edfe9d-e9b9-4adb-bf53-2a4abf7ede95.jpg)

**Comment by ebkr** [comment]
That red error message is because you clicked start modded whilst the game was already running

**Comment by LMNTAL3327** [comment]
Cheers man i appreciate that  but any ide why it wont start a modded gamee
even when the game isnt already open? Like nothing ive tried will get it to
start. It only lets me pkay vanilla by going on steam and starting the game
that way

**Comment by ebkr** [comment]
Can you send your log?
(Settings -> Copy log file contents to clipboard)

You may need to use pastebin or something

**Comment by LMNTAL3327** [comment]
[Message:   BepInEx] BepInEx 5.4.17.0 - valheim (14/01/2022 20:43:23)
[Info   :   BepInEx] Running under Unity v2019.4.31.12409535
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.17.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 25 plugins to load
[Info   :   BepInEx] Loading [Craft From Containers 2.2.1]
[Info   :   BepInEx] Loading [Jotunn 2.4.6]
[Info   :    Jotunn] Initializing LocalizationManager
[Info   :    Jotunn] Initializing CommandManager
[Info   :    Jotunn] Initializing InputManager
[Info   :    Jotunn] Initializing SkillManager
[Info   :    Jotunn] Initializing PrefabManager
[Info   :    Jotunn] Initializing ItemManager
[Info   :    Jotunn] Initializing PieceManager
[Info   :    Jotunn] Initializing MockManager
[Info   :    Jotunn] Initializing KitbashManager
[Info   :    Jotunn] Initializing GUIManager
[Info   :    Jotunn] Initializing KeyHintManager
[Info   :    Jotunn] Initializing ZoneManager
[Info   :    Jotunn] Initializing NetworkManager
[Info   :    Jotunn] Initializing SynchronizationManager
[Info   :    Jotunn] Initializing RenderManager
[Info   :    Jotunn] Initializing MinimapManager
[Info   :    Jotunn] Jötunn v2.4.6 loaded successfully
[Info   :   BepInEx] Loading [BoneAppetit 3.1.0]
[Message:Boneappetit.BoneAppetit] Prepping Kitchen...
[Message:Boneappetit.BoneAppetit] Big thanks to MeatwareMonster!
[Info   :   BepInEx] Loading [Valharvest 1.7.1]
[Info   :Valharvest.Main] Preparing the plants...
[Info   :   BepInEx] Loading [OdinArchitect 0.0.2]
[Info   :OdinArchitect.OdinArchitect] Assets [] loaded succesfully
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinArchitect.OdinArchitect.OA_AddCustomPieces () (at <535f2e27ff35425cb100c9c618315293>:0)
OdinArchitect.OdinArchitect.Awake () (at <535f2e27ff35425cb100c9c618315293>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Info   :   BepInEx] Loading [OdinArchitect 0.1.3]
[Info   :OdinArchitect.OdinArchitect] Assets [] loaded succesfully
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinArchitect.OdinArchitect.OA_AddCustomPieces () (at <535f2e27ff35425cb100c9c618315293>:0)
OdinArchitect.OdinArchitect.Awake () (at <535f2e27ff35425cb100c9c618315293>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Info   :   BepInEx] Loading [CraftyCarts 2.1.0]
[Info   :   BepInEx] Loading [SkToolbox 1.10.5.0]
[Info   :   BepInEx] Loading [Digitalroot Plug-in Info 1.4.1]
[Info   :   BepInEx] Loading [Hugo's Armory 6.1.0]
[Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.6]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.0.14]
[Info   :   BepInEx] Loading [JotunnBackpacks 2.0.0]
[Info   :JotunnBackpacks.BackpackAssets] Embedded resources: JotunnBackpacks.AssetsEmbedded.eviesbackpacks
[Info   :   BepInEx] Loading [Valheim Plus Build Expansion 1.0.8]
[Info   :   BepInEx] Loading [ValheimExpanded: Libs + Core Module 0.5.2]
[Info   :   BepInEx] Loading [ValheimExpanded: + Materials Module 0.5.2]
[Info   :   BepInEx] Loading [ValheimExpanded: + Armaments Module 0.5.2]
[Info   :   BepInEx] Loading [ValheimExpanded: + Mechanics Module 0.5.2]
[Info   :   BepInEx] Loading [ValheimExpanded: Weapons Module 0.4.1]
[Info   :ValExWeapons.Setup] Embedded resources: ValExWeapons.zweapons
[Info   :ValExWeapons.Setup] zweapons (UnityEngine.AssetBundle)
[Info   :   BepInEx] Loading [Mod for remove raids 1.0.0]
[Info   :   BepInEx] Loading [Valheim Plus 0.9.9]
[Info   :Valheim Plus] Trying to load the configuration file
[Info   : Unity Log] Loading config section AdvancedBuildingMode
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section AdvancedEditingMode
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Bed
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Beehive
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Building
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Deconstruct
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Inventory
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Items
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Fermenter
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section FireSource
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Food
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Smelter
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Furnace
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Hotkeys
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Kiln
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Windmill
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section SpinningWheel
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Map
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Player
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Server
[Info   : Unity Log]  Loading key maxPlayers
[Info   : Unity Log]  Loading key disableServerPassword
[Info   : Unity Log]  Loading key enforceMod
[Info   : Unity Log]  Loading key serverSyncsConfig
[Info   : Unity Log]  Loading key serverSyncHotkeys
[Info   : Unity Log] Loading config section Stamina
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section StaminaUsage
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Workbench
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Time
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Ward
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section StructuralIntegrity
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Tameable
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Hud
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Experience
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Camera
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Game
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Wagon
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Gathering
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Pickable
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Durability
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Armor
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section FreePlacementRotation
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Shields
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section FirstPerson
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section GridAlignment
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section CraftFromChest
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section ValheimPlus
[Info   : Unity Log]  Loading key mainMenuLogo
[Info   : Unity Log]  Loading key serverBrowserAdvertisement
[Info   : Unity Log] Loading config section PlayerProjectile
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section MonsterProjectile
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section GameClock
[Info   : Unity Log]  Section not enabled
[Info   : Unity Log] Loading config section Brightness
[Info   : Unity Log]  Section not enabled
[Info   :Valheim Plus] Configuration file loaded succesfully.
[Info   :Valheim Plus] ValheimPlus [0.9.9] is up to date.
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.0]
[Info   :   BepInEx] Loading [Epic Valheims Additions - by Huntard 1.4.3]
[Info   :EpicValheimAdditions.Core] Loaded Prefabs
[Info   :EpicValheimAdditions.Core] Loaded CraftingPieces
[Info   :EpicValheimAdditions.Core] Loaded Ingots/scales/ore
[Info   :EpicValheimAdditions.Core] Loaded MiscItems
[Info   :EpicValheimAdditions.Core] Loaded BossObjects
[Warning:Jotunn.Managers.ItemManager] Custom item BowFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item AtgeirFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SledgeFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item BattleaxeFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SpearFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item KnifeFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item MaceFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SwordFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item ShieldFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item ShieldFrometalTower already added
[Warning:Jotunn.Managers.ItemManager] Custom item AxeFrometal already added
[Warning:Jotunn.Managers.ItemManager] Custom item PickaxeFrometal already added
[Info   :EpicValheimAdditions.Core] Loaded FrometalWeapons
[Warning:Jotunn.Managers.ItemManager] Custom item BowFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item AtgeirFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SledgeFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item BattleaxeFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SpearFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item KnifeFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item MaceFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SwordFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item ShieldFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item ShieldFlametalTower already added
[Warning:Jotunn.Managers.ItemManager] Custom item AxeFlametal already added
[Warning:Jotunn.Managers.ItemManager] Custom item PickaxeFlametal already added
[Info   :EpicValheimAdditions.Core] Loaded FlametalWeapons
[Warning:Jotunn.Managers.ItemManager] Custom item BowHeavymetal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SledgeHeavymetal already added
[Warning:Jotunn.Managers.ItemManager] Custom item BattleaxeHeavymetal already added
[Warning:Jotunn.Managers.ItemManager] Custom item SpearHeavymetal already added
[Warning:Jotunn.Managers.ItemManager] Custom item MaceHeavymetal already added
[Warning:Jotunn.Managers.ItemManager] Custom item PickaxeHeavymetal already added
[Info   :EpicValheimAdditions.Core] Loaded HeavymetalWeapons
[Info   :EpicValheimAdditions.Core] Loaded Custom Recipes
[Info   :EpicValheimAdditions.Core] Loaded Locations
[Info   :   BepInEx] Loading [BuildingUnleashed 5.4.1600]
[Info   :   BepInEx] Loading [UpgradeWorld 1.9.0]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 01/17/2022 13:48:08: Starting to load scene:start

[Info   : Unity Log] (SkToolbox) ->  (CONTROLLER) ->  (NOTIFY) -> LOADING... | WAITING FOR TOOLBOX.  
[Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) ->  (NOTIFY) -> LOADING... | MODULES LOADING...  
[Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) -> Apologies, command aliasing was broken by Hearth and Home and is disabled this patch. Fix is in progress.  
[Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) ->  (MODULE) ->  (NOTIFY) -> NAME: PLAYER | STATUS: READY  
[Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) ->  (MODULE) ->  (NOTIFY) -> NAME: WORLD | STATUS: READY  
[Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) ->  (MODULE) ->  (NOTIFY) -> NAME: CC CONTROLLER | STATUS: READY  
[Info   : Unity Log] (SkToolbox) ->  (TOOLBOX) ->  (NOTIFY) -> 3 MODULES LOADED | TOOLBOX READY.  
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: com.raelaziel
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Jotunn.Utils.BepInExUtils.GetDependentPlugins (System.Boolean includeJotunn) (at <a0a0545b4d9540de992f7837c66808f1>:0)
Jotunn.Managers.SynchronizationManager.FejdStartup_Awake (On.FejdStartup+orig_Awake orig, FejdStartup self) (at <a0a0545b4d9540de992f7837c66808f1>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<FejdStartup::Awake>?1912949888(FejdStartup)

[Warning: Unity Log] 01/17/2022 13:48:12: Missing audio clip in music respawn

[Info   : Unity Log] 01/17/2022 13:48:12: Steam not initialized

**Comment by LMNTAL3327** [comment]
There you go man, copied and pasted the log file

**Comment by ebkr** [comment]
One of your mods by raelaziel is causing the issue. Try disabling them

**Comment by LMNTAL3327** [comment]
okay man thank you ill try work out which one. Thanks for the help!!

**Comment by ebkr** [comment]
Is it alright to close this issue now?

**Comment by LMNTAL3327** [comment]
Hry sorry man i completely forgot. I got lost in Valheim all over agsin
thanks to your Modloader. Thanks man!! Feel free to close

**Comment by ebkr** [comment]
Ah no worries, glad it's sorted!
