### ISSUE TITLE
[FEATURE REQUEST] - Button on Profile Select Page to return to Game select

### ISSUE THREAD

**Issue by nathangeranis** [ebkr/r2modmanPlus#715]
**What problem does the feature request solve?**
Adding a button to the Profile Select page to return to game select would mitigate having to load a profile,  go to Settings -> Other -> Change Game.

**Comment by ebkr** [comment]
Hey, thanks for raising the issue.

This is actually already done for the next release!
![image](https://user-images.githubusercontent.com/10426228/152707538-0bfa5204-9296-4e60-b59a-1a63138a32d5.png)

Going to close this off as already done. Should be released next weekend (hopefully).
