### ISSUE TITLE
[BUG] - Can't export profile as code.

### ISSUE THREAD

**Issue by HarmlessOrange** [ebkr/r2modmanPlus#717]
![help](https://user-images.githubusercontent.com/57143695/153370169-74ec9d34-ec0b-43bd-acaa-f31032dfc2b5.png)

For some reason this only applies to ROUNDS, if I try Risk of Rain 2 it works just as intended.

Making a new ROUNDS profile with the same mods didn't work.

Making a new _empty_ ROUNDS profile makes the export as code work.

Exporting as file still works.

**Comment by ebkr** [comment]
This usually means that the profile is too large.
Profile code exports can currently only be < 2MB. If your file exports is larger than that then it'll fail.

**Comment by HarmlessOrange** [comment]
That explains everything, thanks.
