### ISSUE TITLE
Clicking on an entry's dropdown arrow sends you to the top of the page

### ISSUE THREAD

**Issue by blazingdrummer** [ebkr/r2modmanPlus#72]
This is just a minor annoyance. Clicking anywhere else on the entry retains your position on the page, which would be the desired behavior, so this isn't an urgent fix. The current behavior is just counterintuitive.

Feel free to ping/message me on Discord @blazingdrummer#1929.

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/commit/db199540a1ab8fdaa626ce783c8da5468f9e9a76
