### ISSUE TITLE
Can`t start  modded

### ISSUE THREAD

**Issue by ShuiRen77** [ebkr/r2modmanPlus#728]
An error like this occurred
![I99T~AH36MXG}U3~J~ACF65](https://user-images.githubusercontent.com/76271036/155323690-9bb98d98-9fa3-4b78-8083-8fb8085b500d.png)

setting->locatiions   Here becomes the following
![52 A EU7EJ%3BSK%MI}LT}I](https://user-images.githubusercontent.com/76271036/155323793-c564b63d-3bc2-4632-b10d-b4c51e1837a3.png)

how to get back to normal  like this
![7}7BLO0(JJZ~48_XS@2@K@D](https://user-images.githubusercontent.com/76271036/155324450-b920f7c7-b9b4-4c81-ad9e-d7273855b5f9.png)

**Comment by ebkr** [comment]
Settings -> Change game

Make sure the `Game` tab is selected and not `Server`

**Comment by ShuiRen77** [comment]
> 设置 -> 更改游戏
> 
> 确保`Game`选项卡被选中而不是`Server`

thanks, solved
