### ISSUE TITLE
[BUG] - Issue title

### ISSUE THREAD

**Issue by Cxboxg** [ebkr/r2modmanPlus#733]
[Error  : Unity Log] NotImplementedException: stub
Stack trace:
ABearCodes.Valheim.CraftingWithContainers.Smelting.SmelterPatch.SmelterOnAddOreAreaSearch (Smelter __instance, Switch sw, Humanoid user, ItemDrop+ItemData item, ZNetView ___m_nview, System.Boolean& __result) (at <697b90d1b592472e8017cb3be328c588>:0)
(wrapper dynamic-method) Smelter.DMD<Smelter::OnAddOre>(Smelter,Switch,Humanoid,ItemDrop/ItemData)
Switch.Interact (Humanoid character, System.Boolean hold, System.Boolean alt) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

Hello i play r2modmanwith valheim can anyone say what this mean cause it plobs everytime up i want to put wood in the charcoal

**Comment by ebkr** [comment]
> ABearCodes.Valheim.CraftingWithContainers

That’s a problem with CraftingWithContainers. Not a manager issue
