### ISSUE TITLE
Add buttons to collapse/expand all entries

### ISSUE THREAD

**Issue by blazingdrummer** [ebkr/r2modmanPlus#74]
This would allow you to browse mods quickly while seeing their descriptions, as well as enabling/disabling large numbers of mods more easily.

Feel free to ping/message me on Discord @blazingdrummer#1929.

**Comment by ebkr** [comment]
https://github.com/ebkr/r2modmanPlus/commit/db199540a1ab8fdaa626ce783c8da5468f9e9a76
