### ISSUE TITLE
[FEATURE REQUEST] - Expand Readme.md

### ISSUE THREAD

**Issue by Matthew-E-Gould** [ebkr/r2modmanPlus#740]
Could we have a section at the bottom of the readme.md on how to set up a dev env? I've not built with this exact env and would love to contribute.

**Comment by ebkr** [comment]
Does https://github.com/ebkr/r2modmanPlus/blob/master/BUILDING.md not cover that?

**Comment by Matthew-E-Gould** [comment]
Ah must have missed that, thanks for the link
