### ISSUE TITLE
[BUG] - Config folder not being created for Randomsurvivors mod

### ISSUE THREAD

**Issue by xmedievaldragonx** [ebkr/r2modmanPlus#745]
I am trying to use the randomsurvivors mod by LuaFubuki. The mod makes heavy use of the config folder to generate the random survivors. I have started the game over 10 times now, including uninstalling and reinstalling the mod, downloading previous versions of the mod, and restarting my computer, and still there is no config folder being created. I have config folders for all the other mods I have downloaded, but for some reason this mod is giving me trouble. Is there any way to fix this issue or is it a bug with the mod? Any help would be greatly appreciated.

**Comment by ebkr** [comment]
It's likely an issue with the mod due to the game update

**Comment by xmedievaldragonx** [comment]
gotcha thanks
