### ISSUE TITLE
[BUG] - Installer creates desktop shortcut

### ISSUE THREAD

**Issue by KittenRaee** [ebkr/r2modmanPlus#755]
**Describe the bug**
A desktop shortcut is created on a desktop without user prompt or input during software installation

**To Reproduce**
1. Install the software normally.
2. A desktop shortcut is added, despite being not wanted.

**Expected behavior**
No shortcut should ever be created without explicit permission and knowledge of a user.

**Screenshots**
![image](https://user-images.githubusercontent.com/23376922/161055469-e9a412e5-b16a-4a3a-8dcc-83c9138192ee.png)

**Comment by ebkr** [comment]
The installer isn’t managed by me, it’s NSIS.
I can take a look at options but the answer is probably that I can’t do anything about this.
