### ISSUE TITLE
Crashing issues with Fedora 35

### ISSUE THREAD

**Issue by Synthie** [ebkr/r2modmanPlus#757]
So I recently moved to Fedora from Debian, Modman worked great on Debian 11 however whenever I launch it on Fedora 35 it instantly crashed when I launched it. Here's the error I get

(node:5650) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
starting server on  /tmp/app.r2mm 
starting TLS server false
starting server as Unix || Windows Socket
[5650:0403/143020.780321:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[1]    5650 trace trap (core dumped)  r2modman

Edit: It turns out the issue was I was launching it using Wayland instead of xorg. Once I changed to xorg everything worked beautifully

**Comment by Justsnoopy30** [comment]
All users on newly released Ubuntu 22.04 will crash because of this. The electron version of r2modman needs to be updated to electron 13 or later to fix it.

**Comment by Justsnoopy30** [comment]
Same issue as #735

**Comment by ToonLunk** [comment]
Same issue here with Pop!_OS. I installed the AppImage version and it worked, but the .deb just crashes on startup.

**Comment by ToonLunk** [comment]
@Synthie how did you get that error prompt? Is there a way to see logs of r2modman?
