### ISSUE TITLE
[BUG] - start_game_bepinex.sh: No such file or directory

### ISSUE THREAD

**Issue by CyberShadow** [ebkr/r2modmanPlus#763]
Thank you for your work on this tool! I'm having some trouble getting it to work with Risk of Rain 2 on Linux.

**Describe the bug**
r2modman instructs users to configure the launch command to point to the `linux_wrapper.sh` script it creates. This script in turn attempts to launch a `start_game_bepinex.sh` script, but such a script does not exist.

This causes launching the game to fail with an error such as:

    .../.config/r2modmanPlus-local/RiskOfRain2/linux_wrapper.sh: line 46: .../.config/r2modmanPlus-local/RiskOfRain2/profiles/Default/start_game_bepinex.sh: No such file or directory

**To Reproduce**
1. Run the AppImage on Linux.
2. Select "Risk of Rain 2".
3. At the "Getting started on linux" screen, click "Copy to clipboard".
4. Configure the game's launch options in Steam as described.
5. Select the default profile.
6. Install e.g. the ShareSuite mod.
7. Click "Start modded".
8. See that Steam fails to launch the game, and in its terminal, one can see the error above.

**Expected behavior**
Should work.

**Screenshots**
N/A

**Additional context**
Distribution is Arch Linux.

**Comment by CyberShadow** [comment]
I got it to work by additionally doing:

- Run `winecfg` in the prefix, and add an entry in the Libraries tab for winhttp, setting it to "native then built-in".
- Copy the launch parameters as shown in r2modmad settings (the Windows version as it is running in the Proton prefix), and paste them in Steam's launch parameters.

Maybe this information will help someone.

**Comment by albanD** [comment]
Thanks for sharing this @CyberShadow  This is definitely more challenging to run than I expected.

I was curious if you had any hints on how to debug issues with this.
In particular, even after doing the same things you mention above, the game starts without mods.

The steam logs don't mention anything and trying to launch the exe by hand via `protontricks-launch` fails even in vanilla (I get a black screen for a couple seconds and then it exits without any obvious error in the command line logs).
Also changing the `doorstop_config.ini` to `redirectOutputLog=true` within the prefix does not lead to a log file being created..

Would you have any tips on how to debug why the game launch without mods and generally the doorstop arg seems to do nothing?

**Comment by CyberShadow** [comment]
Hi, sorry, it's been a while. I don't know what's causing the problem in your case, but either way it's important that Wine loads the fake winhttp DLL which performs the mod loading. You could try playing with WINEDEBUG to see what it's doing to make sure that's the case.

**Comment by albanD** [comment]
Thanks for the hint, it was indeed the issue. Not sure why but the steam logs showed that winhttp was not found in the game's path.
I copy pasted the dll from the mod install to the root of the game and now it is found and it works.

That was quite an adventure!

**Comment by tachroneus** [comment]
put a fix i found in the issue by pe1uca for the .sh file. here it is linked:
https://github.com/ebkr/r2modmanPlus/issues/783#issuecomment-4274218627
