### ISSUE TITLE
[BUG] - Installing R2ModMan breaks TMM links in Firefox

### ISSUE THREAD

**Issue by Bucketsmith** [ebkr/r2modmanPlus#767]
Installing r2modman after TMM will make it so Firefox no longer opens the links via TMM, but via r2modman.

1. Go to thunderstore
2. Click on any mod to download
3. ???

I expected that uninstalling r2modman would revert the link behaviour in my browser to point to TMM.
(I wanted to see what was different about R2MM, but there are no differences.)

**Comment by ebkr** [comment]
Not a bug. They both register to the same handler.

Opening TMM will likely fix the issue, otherwise just reinstall TMM.
