### ISSUE TITLE
[FEATURE REQUEST] - Option to tag uploads to r2 as a Modpack

### ISSUE THREAD

**Issue by HuniPotter** [ebkr/r2modmanPlus#770]
I was wondering if you would please consider adding an option to tag uploads to R2 as a mod-pack so that users can seperate Modpacks and Mods when looking through the online section. I often find it hard to browse for new and updated mods when the amount of modpacks being uploaded greatly exceeds the amount of new mods in volume.

**Comment by ebkr** [comment]
You can exclude modpacks using the filter categories option in the top right when on the online tab
