### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by minyassa** [ebkr/r2modmanPlus#807]
**Describe the bug**
When I click on the R2MM desktop icon to start it, I immediately get this error window:
[https://media.discordapp.net/attachments/885286780725784597/993631886842794055/unknown.png](https://media.discordapp.net/attachments/885286780725784597/993631886842794055/unknown.png)

**To Reproduce**
1. Go to desktop
2. Double-click on R2MM desktop icon

**Expected behavior**
I expect it to open the program, as it has been doing up until this afternoon.

**Screenshots**
[https://media.discordapp.net/attachments/885286780725784597/993631886842794055/unknown.png](https://media.discordapp.net/attachments/885286780725784597/993631886842794055/unknown.png)

**Additional context**
It was working just fine last night, I used it to run Valheim and then shut down both programs and Steam this morning before turning computer off. Booted up a little while ago and opened Discord, then attempted to open R2MM and this happened.

**Comment by ebkr** [comment]
The latest release has issues with Win 7. I’ll get around to testing some builds which revert some dependency upgrades which should sort this. In the meantime you’ll likely have to use a portable version of the manager which you can find on the GitHub releases. The last version that’ll work for you currently is 3.1.29

**Comment by minyassa** [comment]
Thank you very much. That version works perfectly for me still.

**Comment by TBOPELl** [comment]
Hello. I have the same problem with version 3.1.31. However - if you install a previously working version 3.1.29, then r2modman automatically updates it to the latest (3.1.31) version. Because of this, the game cannot be launched normally.
How can I disable r2modman auto-update so that it doesn't update to a non-working version???

**Comment by xiaoxiao921** [comment]
> Hello. I have the same problem with version 3.1.31. However - if you install a previously working version 3.1.29, then r2modman automatically updates it to the latest (3.1.31) version. Because of this, the game cannot be launched normally. How can I disable r2modman auto-update so that it doesn't update to a non-working version???

Kinda sad you never got an answer from any maintainers of this, but the solution is to use the non Setup.exe
available here https://github.com/ebkr/r2modmanPlus/releases/download/v3.1.29/r2modman-3.1.29.exe
this one doesnt auto update
