### ISSUE TITLE
[BUG] - Issue installing BepInEx for GTFO

### ISSUE THREAD

**Issue by Aceolu** [ebkr/r2modmanPlus#824]
**Describe the bug**
Ever since the latest update for BepInEx (BepInEx 3.0.0, based on BepInEx 6.0.0-be.648) for GTFO on Thunderstore, the game is unable to boot modded.

All that happens is an window pop-up that just displays "Failed to start BepInEx" along with creating a preloader log which has the following:
[preloader_20220819_145305_263.log](https://github.com/ebkr/r2modmanPlus/files/9385709/preloader_20220819_145305_263.log)

BepInEx was updated using the r2modmanager, and verifying the game's files, reinstalling the game, reinstalling the modmanager.

**To Reproduce**
Simply installing BepInEx v.3.0.0.0 via the r2modmanager, and clicking "Start modded"

**Expected behavior**
The game boots with whatever mods enabled

**Additional context**
Installing the same version of BepInEx manually into the game's steam folder outside of r2modmanager does allow the game to boot regularly, but does not allow any usage of r2modmanager's features. There was also a recent minor update to GTFO itself, but this issue was happening beforehand, and is therefore unrelated.

**Comment by MythicManiac** [comment]
Most of the mods broke when GTFO updated BepInEx to 3.0.0, so the game failing to boot modded is expected. That said, if you aren't able to launch the game modded with only BepInEx installed, that'd be a problem.

**Comment by HeavyDeception** [comment]
Do you have sideloader installed evertime I install it I can get anything to run but every mod uses it. this is the error I get.
[LogOutput.log](https://github.com/ebkr/r2modmanPlus/files/9389974/LogOutput.log)

**Comment by Aceolu** [comment]
> 

That is the problem yes, I only have BepInEx installed when this issue happens

**Comment by PurpleFuzzBall** [comment]
https://gtfo-modding.gitbook.io/wiki/guides/bepinex-fixing-mod-manager

**Comment by MythicManiac** [comment]
For what it's worth, Thunderstore Mod Manager should have this fixed in the latest release (1.18.0) which should be fully published by end of tomorrow.

**Comment by PurpleFuzzBall** [comment]
> For what it's worth, Thunderstore Mod Manager should have this fixed in the latest release (1.18.0) which should be fully published by end of tomorrow.

Its been 5 days since this was said and there is still no update. 😞

**Comment by MythicManiac** [comment]
> > For what it's worth, Thunderstore Mod Manager should have this fixed in the latest release (1.18.0) which should be fully published by end of tomorrow.
> 
> Its been 5 days since this was said and there is still no update. 😞

It should definitely be out by now, I'm not sure what schedule Overwolf uses to check for updates but I'd see about manually updating it if I were you (e.g. re-download or such)

**Comment by ebkr** [comment]
This should be sorted. Is this alright to close?
