### ISSUE TITLE
[BUG] - Crashing while playing/after minutes of playing

### ISSUE THREAD

**Issue by Lunethh** [ebkr/r2modmanPlus#826]
Hi, so recently I started playing this mod with my friend, everything works fine but the only issue is that during the game, after a couple of minute, I would say after 10/20 minutes, the game stops, freezes and crashes. I first tried to host the room then him but its the same issue everytime, I wanted to ask here if this is a common issue that can be fixed somehow or there's something "strange" regarding this? Please tell me there's a fixing to this issue :') thanks.

**Comment by ebkr** [comment]
This is usually just caused by certain mods you'd have installed. You haven't provided much information otherwise however the discord servers relating to the modding communities for the game would be able to help more with any issues
