### ISSUE TITLE
Indicate somewhere that 3.1.29 is the latest working version for windows 7

### ISSUE THREAD

**Issue by xiaoxiao921** [ebkr/r2modmanPlus#831]
Atleast in the readme, ideally handled at runtime too instead of this 
![image](https://user-images.githubusercontent.com/837334/187082801-315b7641-7037-4ee2-9a61-60a6debc257b.png)

**Comment by xiaoxiao921** [comment]
Looks like its a duplicate of https://github.com/ebkr/r2modmanPlus/issues/807
but I blame it because of the horrible title name that never got properly renamed

**Comment by ebkr** [comment]
Win 7 support is reinstated as of 3.1.32
