### ISSUE TITLE
[BUG] - Upgrade to 3.1.32 Lost all of my profiles, won't let me select custom profile folders

### ISSUE THREAD

**Issue by nonplayer** [ebkr/r2modmanPlus#836]
**Describe the bug**
I just did the automatic update to 3.1.32 on Win10, and after starting back up all of my favorites are cleared, and all of my profiles missing. I checked my files, they are still on-disk, but r2modman is now pointing at a different location.

Making matters worse, the app won't let me change the mod directories. When I try to select the previous custom install dir (on my dedicated G drive), it won't let me, giving me an error telling that the directory is not empty. Well of course it's not empty, that's where my profiles are!

How do I fix this, and better yet prevent it from happening again?

**Comment by nonplayer** [comment]
I was able to get it working by moving all of the previous profiles out of the desired location, then selecting, then closing r2, then moving everything back in, and restarting. It still lost all my faves, but I got most of the mods back, all but the manual imports, which I then had to manually re-import, which was another bit of a slog.

I'd really like to prevent this in the future, because now I'm going to worry that every new forced automatic update of r2modman will again wipe all my settings and start over.

**Comment by jonnyawsom3** [comment]
Same here, seems to be using a default path into `AppData\Roaming\r2modmanPlus-local` instead of the previous install's set path

**Comment by LazyBoot** [comment]
Same thing happened to me
settings got reset and had to do the workaround to get the profile folder set correctly again

**Comment by gregest** [comment]
Not much I can say other than it also happened to me, however what nonplayer said to work around it did work   

move the game profiles out from the folder you want the mods to be in, select it in r2mm and then move all the profiles back

**Comment by ebkr** [comment]
See the response [here](https://github.com/ebkr/r2modmanPlus/issues/823#issuecomment-1606264848)
