### ISSUE TITLE
[BUG] - Crashes on startup

### ISSUE THREAD

**Issue by ZephaniahNoah** [ebkr/r2modmanPlus#840]
**Describe the bug**
Window opens for a second then closes.

**To Reproduce**
Double click the appimage

**Expected behavior**
It worky

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/14168013/190304367-576c0e3f-a0e9-4ee2-a4b5-99762dee93e5.png)

**Additional context**
Running on Xubuntu 22.04

**Comment by krypton1101** [comment]
AppImage and pacman installer are doing same
Arch

**Comment by ebkr** [comment]
Does it work when running with —no-sandbox?

**Comment by krypton1101** [comment]
Yes, thank you!
