### ISSUE TITLE
[BUG] - Doesn't Work With Native Linux EtG on Steam

### ISSUE THREAD

**Issue by Yishaijah** [ebkr/r2modmanPlus#842]
Doesn't work with the native Linux build of Enter the Gungeon on Steam. Using the 3.1.32 AppImage on Linux Mint 20.3.

The paths seem to be set correctly and I pasted the wrapper path and %command% thing into the Steam launch options like it asked, but the game won't launch through the mod manager nor directly through Steam. I tried the preloader fix and it says that the directory is invalid and it "could not find either of EtG.exe", even though the path is correct and the "EtG.x86" and "EtG.x86_64" files are in there.

**Comment by ExoPlant** [comment]
Hello! I went through similar troubles! I have a solution for you, but it's more of a workaround to be honest.

1. Find your profile folder, usually at `~/.config/r2modmanPlus-local/ETG/profiles/<PROFILE_NAME>`
2. Copy every file within there to your Enter The Gungeon installation folder, usually at `~/.local/share/Steam/steamapps/common/Enter The Gungeon/`
3. Set your launch command in Steam to `./start_game_bepinex.sh %command%`
4. If that doesn't work (doesn't launch or bepinex doesn't like), remove the `%command%` from your launch options

**Comment by Yishaijah** [comment]
> Hello! I went through similar troubles! I have a solution for you, but it's more of a workaround to be honest.
> 
>     1. Find your profile folder, usually at `~/.config/r2modmanPlus-local/ETG/profiles/<PROFILE_NAME>`
> 
>     2. Copy every file within there to your Enter The Gungeon installation folder, usually at `~/.local/share/Steam/steamapps/common/Enter The Gungeon/`
> 
>     3. Set your launch command in Steam to `./start_game_bepinex.sh %command%`
> 
>     4. If that doesn't work (doesn't launch or bepinex doesn't like), remove the `%command%` from your launch options

It worked! Thanks!

**Comment by ExoPlant** [comment]
@ebkr Are you closing this because you fixed this or because of the above workaround? If it's because of the workaround, I request you reopen this issue as that is not a fix, and ruins the point of profiles entirely

**Comment by ebkr** [comment]
It's extremely likely that it's just a configuration error.
If `./start_game_bepinex.sh` works when hard-coded, it's likely an incorrect directory in the manager settings as when clicking start modded, that file is copied to the specified game directory.

There are instructions on linking the correct one if this is incorrect in the help section within the manager.

Happy to re-open if this doesn't solve it.

**Comment by ExoPlant** [comment]
> It's extremely likely that it's just a configuration error. If `./start_game_bepinex.sh` works when hard-coded, it's likely an incorrect directory in the manager settings as when clicking start modded, that file is copied to the specified game directory.
> 
> There are instructions on linking the correct one if this is incorrect in the help section within the manager.
> 
> Happy to re-open if this doesn't solve it.

That doesn't work. I tried everything similar to that to try and get it to work, but ended up resorting to copying the files etc

**Comment by ExoPlant** [comment]
I'll spin up a reproducable env later and see if I can isolate the issue

**Comment by EmeraldSnorlax** [comment]
hi, id like to add that this issue still affects me. the linux version does not ship an .exe. r2modman wants an .exe, and as such the game just doesn't launch. im curious as to why this issue was closed because it doesn't look like it was actually fixed other than just telling them to hardcode the path lol
