### ISSUE TITLE
[BUG] - r2modman directory mixup Linux

### ISSUE THREAD

**Issue by xFaraday** [ebkr/r2modmanPlus#844]
**Describe the bug**
When manually specifying the steam directory on linux expects a steam executable.

**To Reproduce**
1. Select profile for game
2. go to settings
3. find steam directory location
4. at this point it only allows you to select an executable

**Expected behavior**
Allows you to select the directory instead

**Comment by ebkr** [comment]
It infers it from the executable. Originally it was a directory selection however users found that more confusing than just picking the executable.
