### ISSUE TITLE
[BUG] - Unable to select any game on the r2modman main page

### ISSUE THREAD

**Issue by SFKiseki** [ebkr/r2modmanPlus#876]
**Describe the bug**
No game is displayed and nothing can be selected on the main page

**To Reproduce**
1. Running r2modman (both non-admin and admin mode does not do anything)

**Expected behavior**
An array of games should be seen and they should be able to be selected

**Screenshots**
https://media.discordapp.net/attachments/503742358563717140/1043864300126744576/image.png?width=1202&height=676

**Additional context**
r2modman has been reinstalled before sending this ticket

**Comment by ebkr** [comment]
For anyone else who comes across this, follow the corrupted settings guide here: https://github.com/ebkr/r2modmanPlus/wiki/Error:-White-screen-on-startup#corrupted-settings-on-update
