### ISSUE TITLE
[BUG] - naming possibly wrong? (directory --> executable)

### ISSUE THREAD

**Issue by pcace** [ebkr/r2modmanPlus#899]
shouldnt the naming in settings be 
`Change Steam executable` and not `Change Steam directory`?

![60-638B9380-F-1F1CB760 Kopie](https://user-images.githubusercontent.com/1011875/205456033-c3b0f4c3-1571-4bac-9267-1e622144a2a2.jpg)

**Comment by ebkr** [comment]
I don't think so as that area shows the directory. You just have to select the executable because that's more familiar for most people.
