### ISSUE TITLE
[FEATURE REQUEST] - shortcut creator on help section

### ISSUE THREAD

**Issue by RubenPX** [ebkr/r2modmanPlus#903]
**What problem does the feature request solve?**
This will be more confortable for windows users (maybe for linux and mac)

I suggest make shortcut in desktop folder

**Additional information (optional)**
Maybe this library can help https://www.npmjs.com/package/windows-shortcuts

**Screenshot example**
![image](https://user-images.githubusercontent.com/23123160/205885007-5a1aa3d3-0ebd-4d50-91cb-07592816f701.png)

**Comment by ebkr** [comment]
I don't believe shortcuts are particularly helpful. They help you launch the game quicker but have the following issues:
1. Clutter on the desktop (unless moved to a folder, but then you're still navigating elsewhere)
2. You won't be made aware of any mods with updates. Especially bad when a game update is released and requires some mods to be updated.
3. Deleting a profile will break the shortcut and it won't be removed
