### ISSUE TITLE
[BUG] - Crash on startup

### ISSUE THREAD

**Issue by GuySandler** [ebkr/r2modmanPlus#909]
**Describe the bug**
it crashes on launch

**To Reproduce**
1. open

**Expected behavior**
not crash

**Screenshots**
it opens then closes after about 1 sec

**Additional context**
non

**Comment by ebkr** [comment]
Platform?
Have you tried re-installing?

**Comment by ZumixUwU** [comment]
I am having the same problem. I use it on linux (pop!os). I tried re-installing it one time already.

**Comment by GuySandler** [comment]
> Platform? Have you tried re-installing?

I tried using the appimg and the .deb, they both have the same result

**Comment by ebkr** [comment]
Can you both try running with the `--no-sandbox` argument

**Comment by GuySandler** [comment]
> --no-sandbox

yes that works now
