### ISSUE TITLE
[Question] modded Valheim under Linux with WINE

### ISSUE THREAD

**Issue by qube-03** [ebkr/r2modmanPlus#918]
hi! i'd love to play Valheim modded on Linux yet i usually play the game with Proton GE for improved performance as the actual linux version struggles for me.

i use the steam flatpak version, r2modman from the AUR as im on Artix Linux, Kernel 6.0.11.zen1-1 and as mentioned Valheim under Wine (Proton GE downloaded with Protonup-qt) by using the option "Force the use of an accesibility tool" in steam.

ive specified in the configuration where Valheim is installed and where the steam flatpak directory is, yet the game still launches in vanilla, i assume because the linux version looks for the linux executable "valheim.x86_64", which isnt there

any help is appreciated!

**Comment by ebkr** [comment]
Apologies for the late reply, this should now be working as of 3.1.37.

One thing to note though is that we don't provide packages via the AUR. Official releases are only on this GitHub and on Thunderstore as ebkr/r2modman.

**Comment by ebkr** [comment]
Oops, re-opening in case there are any further issues/comments on this

**Comment by ebkr** [comment]
As no further response, closing.
