### ISSUE TITLE
r2modmanPlus does not launch the game

### ISSUE THREAD

**Issue by Dreregon** [ebkr/r2modmanPlus#92]
For some reason it does not launch the game when "Start Modded" or "Start Vanilla" buttons are pressed
And i've checked, the path to the Risk Of Rain 2 Install is correct

Also, my RoR2 install is not on my C drive with steam, its on another drive.
Clicking the links in the help tab does not work either.

![2020-02-15_12-13-34](https://user-images.githubusercontent.com/34719169/74586889-9e9a2600-4fec-11ea-80f4-64729acbb418.gif)
![2020-02-15_12-19-28](https://user-images.githubusercontent.com/34719169/74586964-7101ac80-4fed-11ea-90c1-d0e91c17a156.gif)

(I know that the gifs are not really showing that nothing is happening but really, nothing's happening)

**Comment by ebkr** [comment]
Have you set the Steam directory and Risk of Rain 2 directory in the manager settings?

**Comment by Dreregon** [comment]
Yes, and when i click both of the Locate folder buttons they open the right folders
![2020-02-15_14-32-40](https://user-images.githubusercontent.com/34719169/74588834-14f45380-5000-11ea-9253-0c1167d21924.gif)

**Comment by ebkr** [comment]
Have you also changed the install mode from Symlink to Legacy?

**Comment by Dreregon** [comment]
yep, that changed nothing :/

**Comment by ebkr** [comment]
Do you own the game on Steam?

**Comment by Dreregon** [comment]
Of course !
Also, i just installed r2mmp on my other computer and it worked here, so i only have the problem on one computer

**Comment by ebkr** [comment]
Try reinstalling the game? Its fixed a few issues before

**Comment by Dreregon** [comment]
Just tried it, even reinstalled r2mmp, got an error that i didn't get on my other computer. even after linking the ror2 folder still nothing
![image](https://user-images.githubusercontent.com/34719169/74589266-22abd800-5004-11ea-8553-6d61f8b09048.png)

**Comment by ebkr** [comment]
1. Try restarting your PC?
2. Can you run powershell normally?
3. Have you tried running the manager as admin?

**Comment by Dreregon** [comment]
1. yes, countless times x)
2- yep, even tried the command of the error 
![image](https://user-images.githubusercontent.com/34719169/74592266-cf478300-501f-11ea-8d9f-f37a48197163.png)
3. also yes, nothing changes...

I do know that my computer is acting a bit funky, (for instance deleting a 20GB game for no reason)
so *maybe* my computer is to blame...

**Comment by ebkr** [comment]
For now, it won't fix the issue, but it could get us back to the original issue, go to:
Settings -> Browse data folder, and delete both folders in there.

**Comment by Dreregon** [comment]
and thats where its gets complicated too, this button does not work either :/

(i'm sorry if i'm wasting your time btw)

**Comment by ebkr** [comment]
No worries, that's what I'm here for.

Can you try uninstalling, and re-installing as an admin?

**Comment by Dreregon** [comment]
tried it, changed nothing.

**Comment by ebkr** [comment]
What OS are you running on?

**Comment by Dreregon** [comment]
Windows 10 1909 build 18363.535

**Comment by ebkr** [comment]
Huh, are you still getting the powershell error?

**Comment by Dreregon** [comment]
yep, as long as i don't locate the ror2 folder, after i do that, the error does not appears anymore

**Comment by ebkr** [comment]
Check your RoR2 folder, is the r2modman folder there with a BepInEx folder inside?

**Comment by Dreregon** [comment]
everything is there (even the data folders)
I just noticed that the new Windows terminal throws an error when it tries to load powershell
(and everything that tries to use it)
![image](https://user-images.githubusercontent.com/34719169/74593085-1b96c100-5028-11ea-8480-28206db9ad24.png)
![image](https://user-images.githubusercontent.com/34719169/74593127-6284b680-5028-11ea-954e-3be437d079e4.png)

so, i will look into that and i'll send another message if i find anything :|

**Comment by ebkr** [comment]
Since everything is there, follow the part in the help section within the manager for launching through Steam.

For now, you'll be able to manage your mods, but you'll have to start the game using Steam.
Any time you want to change something, you'll have to "attempt" to re-run the game modded using the manager.

I'm sorry there isn't a better solution for this, but it'll at least let you keep modding temporarily until you've fixed the powershell issue.

**Comment by Dreregon** [comment]
So, i just did my researches and the launching problem is **indeed** because of powershell (bad path or something like that) (the Browse data folder btn still doesn't works, but i know where it is located so thats not a big deal)

To fix my issue, i launched powershell, then typed this command : **[environment]::setEnvironmentVariable('PATH',"$env:path;C:\Windows\System32\WindowsPowerShell\v1.0", 'm')**
(Following this : https://stackoverflow.com/questions/27650740/powershell-is-not-recognized-as-an-internal-or-external-command )

For now it works, i'll see tomorrow after some reboots of my pc, then i'll close the issue.
Anyway, thanks for the help !
(also your mod manager **is** the best one 👀 )

**Comment by ebkr** [comment]
Thanks! Let me know if you get any further problems with the manager.

A thumbs up on Thunderstore is the best way to help others find the manager, but of course, you don't have to.

**Comment by pa-5imon** [comment]
hey a had a error while launching V Rising modded with r2modman, the game do not start
![image](https://github.com/ebkr/r2modmanPlus/assets/75097309/294e21a4-38a5-4cfe-ac65-57e168da1971)
