### ISSUE TITLE
[BUG] - R2ModMan stuck in "Game Selection" Menu

### ISSUE THREAD

**Issue by Conga0** [ebkr/r2modmanPlus#930]
**Describe the bug**
R2ModMan opens to the game selection menu everytime I open it, but the menu is blank, I can not exit out of it and can not navigate to any other ui screen.

**To Reproduce**
1. Go to settings
2. Click on Game Selection
3. R2Modman will now be stuck in game selection menu with no other options, only Game | Server buttons will appear

**Expected behavior**
I expected a list of games to appear to change my mod manager to, particularly core keeper

**Screenshots**
![image](https://user-images.githubusercontent.com/43751663/210177981-01450342-e645-49fc-9539-9da3f1d30ac1.png)

**Comment by sideG1030** [comment]
Same issue. It was working fine on 28th of Dec, but on 31st of Dec I encountered the same problem, which exists still. I have tried reinstalling R2ModMan, I tried deleting the R2ModMan folder from \Local, but nothing worked so far.

**Comment by sideG1030** [comment]
This helped (but unistalling didn't)
Press Ctrl+Shift+I (Alternatively press Alt and go to View -> Toggle Developer Tools).
Go to the Applications tab. Potentially behind a >> listing.
Expand IndexedDB.
Delete the Settings entry.
Restart the manager.

**Comment by ebkr** [comment]
This should now be resolved as of 3.1.36

**Comment by Kaldrin** [comment]
> This helped (but unistalling didn't) Press Ctrl+Shift+I (Alternatively press Alt and go to View -> Toggle Developer Tools). Go to the Applications tab. Potentially behind a >> listing. Expand IndexedDB. Delete the Settings entry. Restart the manager.

THANK YOU
