### ISSUE TITLE
[BUG] - Deb Package Crashes on Startup

### ISSUE THREAD

**Issue by RhymeJob** [ebkr/r2modmanPlus#938]
**Describe the bug**
When installed through the deb package on Ubuntu 22.10 and apparently PopOS 22.04 r2modman opens a window briefly before crashing. None of the GUI is loaded while the window is up.

**To Reproduce**
1. Install deb package through Ubuntu's GUI installer.
2. Open program from GNOME menu.

Let me know if you need anything else.

**Comment by gibarel1** [comment]
Had the same problem with the AUR package and many versions of the appimage. On their discord they told me to to try `r2modman --no-sandbox` from the terminal and it worked.
I got the output `[20827:0109/140704.054160:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.` when running without parameters.

**Comment by Devilsmaul** [comment]
got the same problem with message:

> x@x-pc:~/Downloads$ r2modman 
> xdg-settings: default-url-scheme-handler not implemented for xfce
> starting server on  /tmp/app.r2mm 
> starting TLS server false
> starting server as Unix || Windows Socket
> [7778:0117/204612.318037:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.

im on
OS: Linux Mint 21.1 x86_64 
DE: Xfce 4.16
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A 

`r2modman --no-sandbox`
works for me also!

**Comment by ebkr** [comment]
It's related to the Electron version, however I can't update to the latest one without dropping Windows 7 support. `--no-sandbox` or potentially `--no-gpu-sandbox` will resolve the issue
