### ISSUE TITLE
[BUG] - ZIP extraction is flat and ignores the actual folder structure

### ISSUE THREAD

**Issue by Vl4dimyr** [ebkr/r2modmanPlus#944]
**Describe the bug**
When installing a mod that has a folder structure inside the ZIP, the folder structure is ignored and all files are put into the target directory. This breaks paths inside the mod, so that resources cannot be loaded. This issue can be bypassed by using embedded resources, but nonetheless this should be fixed in r2modman, in my opinion!

Example:

Actual folder structure (inside the ZIP file):

```
.
├── Assets
│   ├── Translations
│   │   └── English
│   │       └── english.json
│   └── tombstone.png
├── README.md
├── TombstoneHelper.dll
├── icon.png
└── manifest.json
```

Folder structure created by r2modman (in .../BepInEx/plugins/Vl4dimyr-TombstoneHelper):

```
.
├── README.md
├── TombstoneHelper.dll
├── english.json
├── icon.png
├── manifest.json
└── tombstone.png
```

**To Reproduce**
1. Go to https://valheim.thunderstore.io/package/Vl4dimyr/TombstoneHelper/
2. Click on the "Install" button next to `Version 1.0.0`

**Expected behavior**
r2modman should preserve the folder structure.

**Comment by MythicManiac** [comment]
This is intended behavior to keep backwards compatibility. See here: https://github.com/ebkr/r2modmanPlus/wiki/Structuring-your-Thunderstore-package
