### ISSUE TITLE
[BUG] - Config editor includes files from dotnet folder

### ISSUE THREAD

**Issue by UntiIted** [ebkr/r2modmanPlus#946]
**Describe the bug**
dotnet folder files get included in config editor, which should only list mods configuration

**To Reproduce**
1. Create a new profile and install bepinex pack mod (if it is game specific, try BepInExPack_GTFO for GTFO)
2. Go to Config editor (launching game shouldn't be required)
3. See dotnet files included in editor

**Expected behavior**
Config editor should only list mod configuration files

**Screenshots**

![image](https://user-images.githubusercontent.com/47327388/213209358-09781df4-c083-4e27-ba2c-935dee8f619c.png)

**Additional context**

**Comment by MythicManiac** [comment]
The challenge here is that the manager doesn't have any good way to know what files are configs related to mods and what are not.

How come there are dotnet files in your config directory in the first place?

**Comment by ebkr** [comment]
@MythicManiac This was brought up in the GTFO discord. They seem to be required by BepInEx 6.

We should just be able to exclude reading from <profile dir>/dotnet

**Comment by MythicManiac** [comment]
> We should just be able to exclude reading from /dotnet

*2 weeks later: a mod config is now being excluded from export/import because it's placed in /dotnet directory*

But on a more serious note yeah, while I don't like yet another special rule, that probably works well enough that we should do it.
