### ISSUE TITLE
[BUG] - Valheim interactions stop working using this manager

### ISSUE THREAD

**Issue by avelopolcak** [ebkr/r2modmanPlus#962]
**Describe the bug**
I recently ported my mods over from Vortex, and any mod loaded with this manager bricks the game. I can no longer interact with objects, build, or open doors. I have the same mod list from vortex - except a few LESS. I've disabled almost every mod on the list except epic loot and better trader, and the problem persists. I was able to play with all of these mods just hours ago before switching to this mod manager. Before you ask, I performed a complete reinstall of the game, and manually installed the mods on my mod list from thunderstore using this manager. I did not copy/paste any files and no leftover configuration files were kept. Complete folder deletion before switch.

**To Reproduce**
Steps to reproduce - starting the game with this mod manager. 

I dont have any mods that effect building in any way. Can still draw a weapon and attack just not interact - loot - or use the hammer

**Comment by kevinkok** [comment]
Not sure if what you have encountered is the same as mine, but it seems that r2modman has a problem with installing mods that requires a certain folder structure. For example, the Compass mod by aedenthorn requires some assets to be placed in the "Compass" folder in the plugins folder.
When I looked at the cache folder that r2modman uses to store the downloaded mods, I can see that the files are placed in the correct structure, i.e. having the Compass folder in it. However, when I looked at the plugins folder where the mod is placed, I see that the Compass folder is gone, and all contents in the folder is copied into the root folder of the mod instead, i.e.

Expected:
```
plugins/
    AuthorName-ModName/
        Compass/
            center.png
            compass.png
        Compass.dll
        manifest.json
        ...
```

Reality:
```
plugins/
    AuthorName-ModName/
        center.png
        compass.png
        Compass.dll
        manifest.json
        ...
```

**Comment by kevinkok** [comment]
> Not sure if what you have encountered is the same as mine, but it seems that r2modman has a problem with installing mods that requires a certain folder structure. For example, the Compass mod by aedenthorn requires some assets to be placed in the "Compass" folder in the plugins folder. When I looked at the cache folder that r2modman uses to store the downloaded mods, I can see that the files are placed in the correct structure, i.e. having the Compass folder in it. However, when I looked at the plugins folder where the mod is placed, I see that the Compass folder is gone, and all contents in the folder is copied into the root folder of the mod instead, i.e.
> 
> Expected:
> 
> ```
> plugins/
>     AuthorName-ModName/
>         Compass/
>             center.png
>             compass.png
>         Compass.dll
>         manifest.json
>         ...
> ```
> 
> Reality:
> 
> ```
> plugins/
>     AuthorName-ModName/
>         center.png
>         compass.png
>         Compass.dll
>         manifest.json
>         ...
> ```

Just found that all you need to do is to put them in a "plugins" folder, then everything works as expected for my issue.
