### ISSUE TITLE
Create shortcut for desktop

### ISSUE THREAD

**Issue by thaurane** [ebkr/r2modmanPlus#964]
Having to start the mod manager each time to launch modded Valheim is kind of annoying. I would like it to be possible to create a desktop shortcut to launch modded Valheim directly. I have tried to launch Valheim through steam but only bepinexpan gets loaded with none of the mods.

You could also have it check for updates and ask the user if they want to check for updates for their mods.

**Comment by ebkr** [comment]
The best alternative here is to create a shortcut via steam and to then update the launch arguments of the shortcut by visitng the help section of the manager. I don't think this needs to be functionality that the manager provides and is something I think is best avoided as it's less ideal to prompt people to do it this way

**Comment by ebkr** [comment]
Closing as no response
