### ISSUE TITLE
[FEATURE REQUEST] - opt-out of zip flat extraction

### ISSUE THREAD

**Issue by codengine** [ebkr/r2modmanPlus#997]
Hi, I've developed and published a dotnet application on thunderstore.

One of your users tried to load the addon using r2modman and raised an issue on my github project that the archive has been flat extracted. In the end the application relies on a certain folder structure. 

While I know that there are issues already on your github and that this is done for legacy reasons, I just want to suggest that mod authors might be able to opt-out of the flat extraction, maybe using a r2modman.json in the archive, adding it to the manifest or how ever.

Let me know what you think.

**Comment by ebkr** [comment]
What's the reason for not being able to match the expected folder structure?
Additionally is this an application that a user should even be installing through the manager? Normally the only expected things to be installed are mods and configs, separate executable applications are generally not supposed to be unless they're launched by a mod.

**Comment by codengine** [comment]
I haven't seen any rules in regards to the structure of the ZIP archives except that is has to contain the manifest, a readme, the changelog and an icon. As far as I know it does not mandate "you must not have folders inside of the archives".

Despite of that, you are right that r2modman might not be the suitable mod manager to deploy the application but in contrary (I don't know r2modman, because I'm just relaying an issue that I have received), r2modman seems to also not filter for packages available on thunderstore that are not supposed to be installed using your application.

**Comment by ebkr** [comment]
Yeah it's not very clear although it only happens on occasion and so we generally just let people know what to do after the fact as it's a structure that was mainly determined because of the mod manager. Additionally TS itself doesn't impose those restrictions because it's primarily just for storing the packages.

The guide is here: https://github.com/ebkr/r2modmanPlus/wiki/Structuring-your-Thunderstore-package

> r2modman seems to also not filter for packages available on thunderstore that are not supposed to be installed using your application.

We can't filter if we're not aware of the package that shouldn't be shown.
Can you send a link to the package, I can hide it.

On that note, people can also hide their mod from the manager themselves by modifying the modExclusions.md file via PR

**Comment by codengine** [comment]
https://github.com/ebkr/r2modmanPlus/pull/998

There you go, although I would have appreciated a solution that would not end up in removing the application completely :) As I have proposed, authors my include a json file which describes how r2modman might treat the package.

**Comment by ebkr** [comment]
Thanks, added a comment on the PR and you'll also need to agree to the CLA.

With regards to:
> would not end up in removing the application completely

It doesn't de-list it from Thunderstore, just from the manager.

**Comment by codengine** [comment]
I see no difference between an application and a dll that is loaded in a Mod Framework - they can both do similar stuff.

Regarding the PR - Isn't it a bit too much asking for a license agreement for a simple line in a text document?

**Comment by ebkr** [comment]
> I see no difference between an application and a dll that is loaded in a Mod Framework - they can both do similar stuff.

Your application isn't loaded by BepInEx, therefore it's not suited to the mod manager

> Isn't it a bit too much asking for a license agreement for a simple line in a text document?

It's just standard to say that you won't withdraw the changes in the PR, it's probably overkill but it's better to have all contributors sign it

**Comment by MythicManiac** [comment]
@codengine FYI the Thunderstore package format will include more explicit control over how packages should be installed once we have the spec for that locked down. Right now the installation logic isn't really defined by Thunderstore, but rather the mod managers themselves. In the future we'll have a set of fields in the manifest that can be used to control how a package should be treated, and mod managers are expected to follow that.

Not immediately helpful here, but I figured it might be nice to know
